РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","ar",{euro:"РЁВ±Р©вЂ¦РЁР† РЁВ§Р©вЂћР©Р‰Р©в‚¬РЁВ±Р©в‚¬",lsquo:"РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ© РЁР„Р©вЂ РЁВµР©Р‰РЁВµ Р©РѓРЁВ±РЁР‡Р©Р‰РЁВ© РЁв„–Р©вЂћР©Р‰ РЁВ§Р©вЂћР©Р‰РЁС–РЁВ§РЁВ±",rsquo:"РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ© РЁР„Р©вЂ РЁВµР©Р‰РЁВµ Р©РѓРЁВ±РЁР‡Р©Р‰РЁВ© РЁв„–Р©вЂћР©Р‰ РЁВ§Р©вЂћР©Р‰Р©вЂ¦Р©Р‰Р©вЂ ",ldquo:"РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ© РЁР„Р©вЂ РЁВµР©Р‰РЁВµ Р©вЂ¦РЁР†РЁР‡Р©в‚¬РЁВ¬РЁВ© РЁв„–Р©вЂћР©Р‰ РЁВ§Р©вЂћР©Р‰РЁС–РЁВ§РЁВ±",rdquo:"РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ© РЁР„Р©вЂ РЁВµР©Р‰РЁВµ Р©вЂ¦РЁР†РЁР‡Р©в‚¬РЁВ¬РЁВ© РЁв„–Р©вЂћР©Р‰ РЁВ§Р©вЂћР©Р‰Р©вЂ¦Р©Р‰Р©вЂ ",ndash:"En dash",mdash:"Em dash",iexcl:"РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ© РЁР„РЁв„–РЁВ¬РЁРЃ Р©вЂ¦Р©вЂљР©вЂћР©в‚¬РЁРЃРЁВ©",cent:"РЁВ±Р©вЂ¦РЁР† РЁВ§Р©вЂћРЁС–Р©вЂ РЁР„",pound:"РЁВ±Р©вЂ¦РЁР† РЁВ§Р©вЂћРЁВ§РЁС–РЁР„РЁВ±Р©вЂћР©Р‰Р©вЂ Р©Р‰",curren:"РЁВ±Р©вЂ¦РЁР† РЁВ§Р©вЂћРЁв„–Р©вЂ¦Р©вЂћРЁВ©",yen:"РЁВ±Р©вЂ¦РЁР† РЁВ§Р©вЂћР©Р‰Р©вЂ ",brvbar:"РЁТ‘РЁВ±Р©Р‰РЁВ· Р©вЂ¦Р©вЂљРЁВ·Р©в‚¬РЁв„–",sect:"РЁВ±Р©вЂ¦РЁР† РЁВ§Р©вЂћР©вЂљРЁС–Р©вЂ¦",uml:"Diaeresis",copy:"РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ© РЁВ­Р©вЂљР©в‚¬Р©вЂљ РЁВ§Р©вЂћРЁВ·РЁРЃРЁв„–",ordf:"Feminine ordinal indicator",laquo:"Left-pointing double angle quotation mark",
not:"Р©вЂћР©Р‰РЁС–РЁР„ РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ©",reg:"РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ© Р©вЂ¦РЁС–РЁВ¬Р©вЂ�Р©вЂћРЁВ©",macr:"Macron",deg:"Degree sign",sup2:"Superscript two",sup3:"Superscript three",acute:"Acute accent",micro:"Micro sign",para:"Pilcrow sign",middot:"Middle dot",cedil:"Cedilla",sup1:"Superscript one",ordm:"Masculine ordinal indicator",raquo:"Right-pointing double angle quotation mark",frac14:"Vulgar fraction one quarter",frac12:"Vulgar fraction one half",frac34:"Vulgar fraction three quarters",iquest:"РЁв„–Р©вЂћРЁВ§Р©вЂ¦РЁВ© РЁВ§Р©вЂћРЁТђРЁС–РЁР„Р©РѓР©вЂЎРЁВ§Р©вЂ¦ РЁС”Р©Р‰РЁВ± РЁВµРЁВ­Р©Р‰РЁВ­РЁВ©",Agrave:"Latin capital letter A with grave accent",
Aacute:"Latin capital letter A with acute accent",Acirc:"Latin capital letter A with circumflex",Atilde:"Latin capital letter A with tilde",Auml:"Latin capital letter A with diaeresis",Aring:"Latin capital letter A with ring above",AElig:"Latin Capital letter Р“вЂ ",Ccedil:"Latin capital letter C with cedilla",Egrave:"Latin capital letter E with grave accent",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"Latin capital letter I with grave accent",
Iacute:"Latin capital letter I with acute accent",Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",ETH:"Latin capital letter Eth",Ntilde:"Latin capital letter N with tilde",Ograve:"Latin capital letter O with grave accent",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",times:"Multiplication sign",Oslash:"Latin capital letter O with stroke",
Ugrave:"Latin capital letter U with grave accent",Uacute:"Latin capital letter U with acute accent",Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",Yacute:"Latin capital letter Y with acute accent",THORN:"Latin capital letter Thorn",szlig:"Latin small letter sharp s",agrave:"Latin small letter a with grave accent",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",auml:"Latin small letter a with diaeresis",
aring:"Latin small letter a with ring above",aelig:"Latin small letter Р“В¦",ccedil:"Latin small letter c with cedilla",egrave:"Latin small letter e with grave accent",eacute:"Latin small letter e with acute accent",ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"Latin small letter i with grave accent",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"Latin small letter eth",
ntilde:"Latin small letter n with tilde",ograve:"Latin small letter o with grave accent",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",divide:"Division sign",oslash:"Latin small letter o with stroke",ugrave:"Latin small letter u with grave accent",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",
yacute:"Latin small letter y with acute accent",thorn:"Latin small letter thorn",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",
trade:"Trade mark sign",9658:"Black right-pointing pointer",bull:"Bullet",rarr:"Rightwards arrow",rArr:"Rightwards double arrow",hArr:"Left right double arrow",diams:"Black diamond suit",asymp:"Almost equal to"});