РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","cs",{euro:"Znak eura",lsquo:"PoР”РЊР“РЋteР”РЊnР“В­ uvozovka jednoduchР“РЋ",rsquo:"KoncovР“РЋ uvozovka jednoduchР“РЋ",ldquo:"PoР”РЊР“РЋteР”РЊnР“В­ uvozovka dvojitР“РЋ",rdquo:"KoncovР“РЋ uvozovka dvojitР“РЋ",ndash:"En pomlР”РЊka",mdash:"Em pomlР”РЊka",iexcl:"ObrР“РЋcenР“Р… vykР•в„ўiР”РЊnР“В­k",cent:"Znak centu",pound:"Znak libry",curren:"Znak mР”вЂєny",yen:"Znak jenu",brvbar:"PР•в„ўeruР•РЋenР“РЋ svislР“РЋ Р”РЊР“РЋra",sect:"Znak oddР“В­lu",uml:"PР•в„ўehlР“РЋska",copy:"Znak copyrightu",ordf:"Р•Р…enskР“Р… indikР“РЋtor rodu",laquo:"Znak dvojitР“Р…ch lomenР“Р…ch uvozovek vlevo",
not:"LogistickР“Р… zР“РЋpor",reg:"Znak registrace",macr:"PomlР”РЊka nad",deg:"Znak stupnР”вЂє",sup2:"Dvojka jako hornР“В­ index",sup3:"Trojka jako hornР“В­ index",acute:"Р”РЉР“РЋrka nad vpravo",micro:"Znak mikro",para:"Znak odstavce",middot:"TeР”РЊka uprostР•в„ўed",cedil:"OcР“РЋsek vlevo",sup1:"JedniР”РЊka jako hornР“В­ index",ordm:"MuР•С•skР“Р… indikР“РЋtor rodu",raquo:"Znak dvojitР“Р…ch lomenР“Р…ch uvozovek vpravo",frac14:"ObyР”РЊejnР“Р… zlomek jedna Р”РЊtvrtina",frac12:"ObyР”РЊejnР“Р… zlomek jedna polovina",frac34:"ObyР”РЊejnР“Р… zlomek tР•в„ўi Р”РЊtvrtiny",iquest:"Znak obrР“РЋcenР“В©ho otaznР“В­ku",
Agrave:"VelkР“В© pР“В­smeno latinky A s Р”РЊР“РЋrkou nad vlevo",Aacute:"VelkР“В© pР“В­smeno latinky A s Р”РЊР“РЋrkou nad vpravo",Acirc:"VelkР“В© pР“В­smeno latinky A s vokР“РЋnР”вЂєm",Atilde:"VelkР“В© pР“В­smeno latinky A s tildou",Auml:"VelkР“В© pР“В­smeno latinky A s dvР”вЂєma teР”РЊkami",Aring:"VelkР“В© pР“В­smeno latinky A s krouР•С•kem nad",AElig:"VelkР“В© pР“В­smeno latinky Ae",Ccedil:"VelkР“В© pР“В­smeno latinky C s ocР“РЋskem vlevo",Egrave:"VelkР“В© pР“В­smeno latinky E s Р”РЊР“РЋrkou nad vlevo",Eacute:"VelkР“В© pР“В­smeno latinky E s Р”РЊР“РЋrkou nad vpravo",Ecirc:"VelkР“В© pР“В­smeno latinky E s vokР“РЋnР”вЂєm",
Euml:"VelkР“В© pР“В­smeno latinky E s dvР”вЂєma teР”РЊkami",Igrave:"VelkР“В© pР“В­smeno latinky I s Р”РЊР“РЋrkou nad vlevo",Iacute:"VelkР“В© pР“В­smeno latinky I s Р”РЊР“РЋrkou nad vpravo",Icirc:"VelkР“В© pР“В­smeno latinky I s vokР“РЋnР”вЂєm",Iuml:"VelkР“В© pР“В­smeno latinky I s dvР”вЂєma teР”РЊkami",ETH:"VelkР“В© pР“В­smeno latinky Eth",Ntilde:"VelkР“В© pР“В­smeno latinky N s tildou",Ograve:"VelkР“В© pР“В­smeno latinky O s Р”РЊР“РЋrkou nad vlevo",Oacute:"VelkР“В© pР“В­smeno latinky O s Р”РЊР“РЋrkou nad vpravo",Ocirc:"VelkР“В© pР“В­smeno latinky O s vokР“РЋnР”вЂєm",Otilde:"VelkР“В© pР“В­smeno latinky O s tildou",
Ouml:"VelkР“В© pР“В­smeno latinky O s dvР”вЂєma teР”РЊkami",times:"Znak nР“РЋsobenР“В­",Oslash:"VelkР“В© pР“В­smeno latinky O pР•в„ўeР•РЋkrtnutР“В©",Ugrave:"VelkР“В© pР“В­smeno latinky U s Р”РЊР“РЋrkou nad vlevo",Uacute:"VelkР“В© pР“В­smeno latinky U s Р”РЊР“РЋrkou nad vpravo",Ucirc:"VelkР“В© pР“В­smeno latinky U s vokР“РЋnР”вЂєm",Uuml:"VelkР“В© pР“В­smeno latinky U s dvР”вЂєma teР”РЊkami",Yacute:"VelkР“В© pР“В­smeno latinky Y s Р”РЊР“РЋrkou nad vpravo",THORN:"VelkР“В© pР“В­smeno latinky Thorn",szlig:"MalР“В© pР“В­smeno latinky ostrР“В© s",agrave:"MalР“В© pР“В­smeno latinky a s Р”РЊР“РЋrkou nad vlevo",aacute:"MalР“В© pР“В­smeno latinky a s Р”РЊР“РЋrkou nad vpravo",
acirc:"MalР“В© pР“В­smeno latinky a s vokР“РЋnР”вЂєm",atilde:"MalР“В© pР“В­smeno latinky a s tildou",auml:"MalР“В© pР“В­smeno latinky a s dvР”вЂєma teР”РЊkami",aring:"MalР“В© pР“В­smeno latinky a s krouР•С•kem nad",aelig:"MalР“В© pР“В­smeno latinky ae",ccedil:"MalР“В© pР“В­smeno latinky c s ocР“РЋskem vlevo",egrave:"MalР“В© pР“В­smeno latinky e s Р”РЊР“РЋrkou nad vlevo",eacute:"MalР“В© pР“В­smeno latinky e s Р”РЊР“РЋrkou nad vpravo",ecirc:"MalР“В© pР“В­smeno latinky e s vokР“РЋnР”вЂєm",euml:"MalР“В© pР“В­smeno latinky e s dvР”вЂєma teР”РЊkami",igrave:"MalР“В© pР“В­smeno latinky i s Р”РЊР“РЋrkou nad vlevo",iacute:"MalР“В© pР“В­smeno latinky i s Р”РЊР“РЋrkou nad vpravo",
icirc:"MalР“В© pР“В­smeno latinky i s vokР“РЋnР”вЂєm",iuml:"MalР“В© pР“В­smeno latinky i s dvР”вЂєma teР”РЊkami",eth:"MalР“В© pР“В­smeno latinky eth",ntilde:"MalР“В© pР“В­smeno latinky n s tildou",ograve:"MalР“В© pР“В­smeno latinky o s Р”РЊР“РЋrkou nad vlevo",oacute:"MalР“В© pР“В­smeno latinky o s Р”РЊР“РЋrkou nad vpravo",ocirc:"MalР“В© pР“В­smeno latinky o s vokР“РЋnР”вЂєm",otilde:"MalР“В© pР“В­smeno latinky o s tildou",ouml:"MalР“В© pР“В­smeno latinky o s dvР”вЂєma teР”РЊkami",divide:"Znak dР”вЂєlenР“В­",oslash:"MalР“В© pР“В­smeno latinky o pР•в„ўeР•РЋkrtnutР“В©",ugrave:"MalР“В© pР“В­smeno latinky u s Р”РЊР“РЋrkou nad vlevo",
uacute:"MalР“В© pР“В­smeno latinky u s Р”РЊР“РЋrkou nad vpravo",ucirc:"MalР“В© pР“В­smeno latinky u s vokР“РЋnР”вЂєm",uuml:"MalР“В© pР“В­smeno latinky u s dvР”вЂєma teР”РЊkami",yacute:"MalР“В© pР“В­smeno latinky y s Р”РЊР“РЋrkou nad vpravo",thorn:"MalР“В© pР“В­smeno latinky thorn",yuml:"MalР“В© pР“В­smeno latinky y s dvР”вЂєma teР”РЊkami",OElig:"VelkР“РЋ ligatura latinky OE",oelig:"MalР“РЋ ligatura latinky OE",372:"VelkР“В© pР“В­smeno latinky W s vokР“РЋnР”вЂєm",374:"VelkР“В© pР“В­smeno latinky Y s vokР“РЋnР”вЂєm",373:"MalР“В© pР“В­smeno latinky w s vokР“РЋnР”вЂєm",375:"MalР“В© pР“В­smeno latinky y s vokР“РЋnР”вЂєm",sbquo:"DolnР“В­ 9 uvozovka jednoduchР“РЋ",
8219:"HornР“В­ obrР“РЋcenР“РЋ 9 uvozovka jednoduchР“РЋ",bdquo:"DolnР“В­ 9 uvozovka dvojitР“РЋ",hellip:"TrojteР”РЊkovР“Р… Р“С”vod",trade:"ObchodnР“В­ znaР”РЊka",9658:"Р”РЉernР“Р… ukazatel smР”вЂєР•в„ўujР“В­cР“В­ vpravo",bull:"KoleР”РЊko",rarr:"Р•В ipka vpravo",rArr:"DvojitР“РЋ Р•РЋipka vpravo",hArr:"DvojitР“РЋ Р•РЋipka vlevo a vpravo",diams:"Р”РЉernР“В© piky",asymp:"TР“В©mР”вЂєР•в„ў se rovnР“РЋ"});