РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","eo",{euro:"EР•В­rosigno",lsquo:"Supra 6-citilo",rsquo:"Supra 9-citilo",ldquo:"Supra 66-citilo",rdquo:"Supra 99-citilo",ndash:"Streketo",mdash:"Substreko",iexcl:"Renversita krisigno",cent:"Cendosigno",pound:"Pundosigno",curren:"Monersigno",yen:"Enosigno",brvbar:"Rompita vertikala streko",sect:"Kurba paragrafo",uml:"Tremao",copy:"Kopirajtosigno",ordf:"Adjektiva numerfinaР”Вµo",laquo:"Duobla malplio-citilo",not:"Negohoko",reg:"Registrita marko",macr:"Superstreko",deg:"Gradosigno",
sup2:"Supra indico 2",sup3:"Supra indico 3",acute:"Dekstra korno",micro:"Mikrosigno",para:"Rekta paragrafo",middot:"Meza punkto",cedil:"Zoeto",sup1:"Supra indico 1",ordm:"Substantiva numerfinaР”Вµo",raquo:"Duobla plio-citilo",frac14:"Kvaronosigno",frac12:"Duonosigno",frac34:"Trikvaronosigno",iquest:"renversita demandosigno",Agrave:"Latina Р”вЂ°eflitero A kun liva korno",Aacute:"Latina Р”вЂ°eflitero A kun dekstra korno",Acirc:"Latina Р”вЂ°eflitero A kun Р”вЂ°apelo",Atilde:"Latina Р”вЂ°eflitero A kun tildo",Auml:"Latina Р”вЂ°eflitero A kun tremao",
Aring:"Latina Р”вЂ°eflitero A kun superringo",AElig:"Latina Р”вЂ°eflitera ligaturo Р“вЂ ",Ccedil:"Latina Р”вЂ°eflitero C kun zoeto",Egrave:"Latina Р”вЂ°eflitero E kun liva korno",Eacute:"Latina Р”вЂ°eflitero E kun dekstra korno",Ecirc:"Latina Р”вЂ°eflitero E kun Р”вЂ°apelo",Euml:"Latina Р”вЂ°eflitero E kun tremao",Igrave:"Latina Р”вЂ°eflitero I kun liva korno",Iacute:"Latina Р”вЂ°eflitero I kun dekstra korno",Icirc:"Latina Р”вЂ°eflitero I kun Р”вЂ°apelo",Iuml:"Latina Р”вЂ°eflitero I kun tremao",ETH:"Latina Р”вЂ°eflitero islanda edo",Ntilde:"Latina Р”вЂ°eflitero N kun tildo",
Ograve:"Latina Р”вЂ°eflitero O kun liva korno",Oacute:"Latina Р”вЂ°eflitero O kun dekstra korno",Ocirc:"Latina Р”вЂ°eflitero O kun Р”вЂ°apelo",Otilde:"Latina Р”вЂ°eflitero O kun tildo",Ouml:"Latina Р”вЂ°eflitero O kun tremao",times:"Multipliko",Oslash:"Latina Р”вЂ°eflitero O trastrekita",Ugrave:"Latina Р”вЂ°eflitero U kun liva korno",Uacute:"Latina Р”вЂ°eflitero U kun dekstra korno",Ucirc:"Latina Р”вЂ°eflitero U kun Р”вЂ°apelo",Uuml:"Latina Р”вЂ°eflitero U kun tremao",Yacute:"Latina Р”вЂ°eflitero Y kun dekstra korno",THORN:"Latina Р”вЂ°eflitero islanda dorno",
szlig:"Latina etlitero germana sozo (akra s)",agrave:"Latina etlitero a kun liva korno",aacute:"Latina etlitero a kun dekstra korno",acirc:"Latina etlitero a kun Р”вЂ°apelo",atilde:"Latina etlitero a kun tildo",auml:"Latina etlitero a kun tremao",aring:"Latina etlitero a kun superringo",aelig:"Latina etlitera ligaturo Р“В¦",ccedil:"Latina etlitero c kun zoeto",egrave:"Latina etlitero e kun liva korno",eacute:"Latina etlitero e kun dekstra korno",ecirc:"Latina etlitero e kun Р”вЂ°apelo",euml:"Latina etlitero e kun tremao",
igrave:"Latina etlitero i kun liva korno",iacute:"Latina etlitero i kun dekstra korno",icirc:"Latina etlitero i kun Р”вЂ°apelo",iuml:"Latina etlitero i kun tremao",eth:"Latina etlitero islanda edo",ntilde:"Latina etlitero n kun tildo",ograve:"Latina etlitero o kun liva korno",oacute:"Latina etlitero o kun dekstra korno",ocirc:"Latina etlitero o kun Р”вЂ°apelo",otilde:"Latina etlitero o kun tildo",ouml:"Latina etlitero o kun tremao",divide:"Dividosigno",oslash:"Latina etlitero o trastrekita",ugrave:"Latina etlitero u kun liva korno",
uacute:"Latina etlitero u kun dekstra korno",ucirc:"Latina etlitero u kun Р”вЂ°apelo",uuml:"Latina etlitero u kun tremao",yacute:"Latina etlitero y kun dekstra korno",thorn:"Latina etlitero islanda dorno",yuml:"Latina etlitero y kun tremao",OElig:"Latina Р”вЂ°eflitera ligaturo Р•вЂ™",oelig:"Latina etlitera ligaturo Р•вЂњ",372:"Latina Р”вЂ°eflitero W kun Р”вЂ°apelo",374:"Latina Р”вЂ°eflitero Y kun Р”вЂ°apelo",373:"Latina etlitero w kun Р”вЂ°apelo",375:"Latina etlitero y kun Р”вЂ°apelo",sbquo:"Suba 9-citilo",8219:"Supra renversita 9-citilo",
bdquo:"Suba 99-citilo",hellip:"Tripunkto",trade:"Varmarka signo",9658:"Nigra sago dekstren",bull:"Bulmarko",rarr:"Sago dekstren",rArr:"Duobla sago dekstren",hArr:"Duobla sago maldekstren",diams:"Nigra kvadrato",asymp:"PreskaР•В­ egala"});