РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","es",{euro:"SР“В­mbolo de euro",lsquo:"Comilla simple izquierda",rsquo:"Comilla simple derecha",ldquo:"Comilla doble izquierda",rdquo:"Comilla doble derecha",ndash:"GuiР“С–n corto",mdash:"GuiР“С–n medio largo",iexcl:"Signo de admiraciР“С–n invertido",cent:"SР“В­mbolo centavo",pound:"SР“В­mbolo libra",curren:"SР“В­mbolo moneda",yen:"SР“В­mbolo yen",brvbar:"Barra vertical rota",sect:"SР“В­mbolo secciР“С–n",uml:"DiР“В©resis",copy:"Signo de derechos de autor",ordf:"Indicador ordinal femenino",laquo:"Abre comillas angulares",
not:"Signo negaciР“С–n",reg:"Signo de marca registrada",macr:"GuiР“С–n alto",deg:"Signo de grado",sup2:"SuperР“В­ndice dos",sup3:"SuperР“В­ndice tres",acute:"Acento agudo",micro:"Signo micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"SuperР“В­ndice uno",ordm:"Indicador orginal masculino",raquo:"Cierra comillas angulares",frac14:"FracciР“С–n ordinaria de un quarto",frac12:"FracciР“С–n ordinaria de una mitad",frac34:"FracciР“С–n ordinaria de tres cuartos",iquest:"Signo de interrogaciР“С–n invertido",Agrave:"Letra A latina mayР“С”scula con acento grave",
Aacute:"Letra A latina  mayР“С”scula con acento agudo",Acirc:"Letra A latina mayР“С”scula con acento circunflejo",Atilde:"Letra A latina mayР“С”scula con tilde",Auml:"Letra A latina mayР“С”scula con diР“В©resis",Aring:"Letra A latina mayР“С”scula con aro arriba",AElig:"Letra Р“вЂ  latina mayР“С”scula",Ccedil:"Letra C latina mayР“С”scula con cedilla",Egrave:"Letra E latina mayР“С”scula con acento grave",Eacute:"Letra E latina mayР“С”scula con acento agudo",Ecirc:"Letra E latina mayР“С”scula con acento circunflejo",Euml:"Letra E latina mayР“С”scula con diР“В©resis",
Igrave:"Letra I latina mayР“С”scula con acento grave",Iacute:"Letra I latina mayР“С”scula con acento agudo",Icirc:"Letra I latina mayР“С”scula con acento circunflejo",Iuml:"Letra I latina mayР“С”scula con diР“В©resis",ETH:"Letra Eth latina mayР“С”scula",Ntilde:"Letra N latina mayР“С”scula con tilde",Ograve:"Letra O latina mayР“С”scula con acento grave",Oacute:"Letra O latina mayР“С”scula con acento agudo",Ocirc:"Letra O latina mayР“С”scula con acento circunflejo",Otilde:"Letra O latina mayР“С”scula con tilde",Ouml:"Letra O latina mayР“С”scula con diР“В©resis",
times:"Signo de multiplicaciР“С–n",Oslash:"Letra O latina mayР“С”scula con barra inclinada",Ugrave:"Letra U latina mayР“С”scula con acento grave",Uacute:"Letra U latina mayР“С”scula con acento agudo",Ucirc:"Letra U latina mayР“С”scula con acento circunflejo",Uuml:"Letra U latina mayР“С”scula con diР“В©resis",Yacute:"Letra Y latina mayР“С”scula con acento agudo",THORN:"Letra Thorn latina mayР“С”scula",szlig:"Letra s latina fuerte pequeР“В±a",agrave:"Letra a latina pequeР“В±a con acento grave",aacute:"Letra a latina pequeР“В±a con acento agudo",
acirc:"Letra a latina pequeР“В±a con acento circunflejo",atilde:"Letra a latina pequeР“В±a con tilde",auml:"Letra a latina pequeР“В±a con diР“В©resis",aring:"Letra a latina pequeР“В±a con aro arriba",aelig:"Letra Р“В¦ latina pequeР“В±a",ccedil:"Letra c latina pequeР“В±a con cedilla",egrave:"Letra e latina pequeР“В±a con acento grave",eacute:"Letra e latina pequeР“В±a con acento agudo",ecirc:"Letra e latina pequeР“В±a con acento circunflejo",euml:"Letra e latina pequeР“В±a con diР“В©resis",igrave:"Letra i latina pequeР“В±a con acento grave",
iacute:"Letra i latina pequeР“В±a con acento agudo",icirc:"Letra i latina pequeР“В±a con acento circunflejo",iuml:"Letra i latina pequeР“В±a con diР“В©resis",eth:"Letra eth latina pequeР“В±a",ntilde:"Letra n latina pequeР“В±a con tilde",ograve:"Letra o latina pequeР“В±a con acento grave",oacute:"Letra o latina pequeР“В±a con acento agudo",ocirc:"Letra o latina pequeР“В±a con acento circunflejo",otilde:"Letra o latina pequeР“В±a con tilde",ouml:"Letra o latina pequeР“В±a con diР“В©resis",divide:"Signo de divisiР“С–n",oslash:"Letra o latina minР“С”scula con barra inclinada",
ugrave:"Letra u latina pequeР“В±a con acento grave",uacute:"Letra u latina pequeР“В±a con acento agudo",ucirc:"Letra u latina pequeР“В±a con acento circunflejo",uuml:"Letra u latina pequeР“В±a con diР“В©resis",yacute:"Letra u latina pequeР“В±a con acento agudo",thorn:"Letra thorn latina minР“С”scula",yuml:"Letra y latina pequeР“В±a con diР“В©resis",OElig:"Diptongo OE latino en mayР“С”scula",oelig:"Diptongo oe latino en minР“С”scula",372:"Letra W latina mayР“С”scula con acento circunflejo",374:"Letra Y latina mayР“С”scula con acento circunflejo",
373:"Letra w latina pequeР“В±a con acento circunflejo",375:"Letra y latina pequeР“В±a con acento circunflejo",sbquo:"Comilla simple baja-9",8219:"Comilla simple alta invertida-9",bdquo:"Comillas dobles bajas-9",hellip:"Puntos suspensivos horizontales",trade:"Signo de marca registrada",9658:"Apuntador negro apuntando a la derecha",bull:"ViР“В±eta",rarr:"Flecha a la derecha",rArr:"Flecha doble a la derecha",hArr:"Flecha izquierda derecha doble",diams:"Diamante negro",asymp:"Casi igual a"});