РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr-ca",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret",iexcl:"Point d'exclamation inversР“В©",cent:"Symbole de cent",pound:"Symbole de Livre Sterling",curren:"Symbole monР“В©taire",yen:"Symbole du Yen",brvbar:"Barre scindР“В©e",sect:"Symbole de section",uml:"TrР“В©ma",copy:"Symbole de copyright",ordf:"Indicateur ordinal fР“В©minin",laquo:"Guillemet franР“В§ais ouvrant",
not:"Indicateur de nР“В©gation",reg:"Symbole de marque dР“В©posР“В©e",macr:"Macron",deg:"DegrР“В©",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aigР“С�e",micro:"Symbole micro",para:"Paragraphe",middot:"Point mР“В©dian",cedil:"CР“В©dille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franР“В§ais fermant",frac14:"Un quart",frac12:"Une demi",frac34:"Trois quart",iquest:"Point d'interrogation inversР“В©",Agrave:"A accent grave",Aacute:"A accent aigР“С�e",Acirc:"A circonflexe",Atilde:"A tilde",Auml:"A trР“В©ma",
Aring:"A avec un rond au dessus",AElig:"Р“вЂ  majuscule",Ccedil:"C cР“В©dille",Egrave:"E accent grave",Eacute:"E accent aigР“С�e",Ecirc:"E accent circonflexe",Euml:"E trР“В©ma",Igrave:"I accent grave",Iacute:"I accent aigР“С�e",Icirc:"I accent circonflexe",Iuml:"I trР“В©ma",ETH:"Lettre majuscule islandaise ED",Ntilde:"N tilde",Ograve:"O accent grave",Oacute:"O accent aigР“С�e",Ocirc:"O accent circonflexe",Otilde:"O tilde",Ouml:"O trР“В©ma",times:"Symbole de multiplication",Oslash:"O barrР“В©",Ugrave:"U accent grave",Uacute:"U accent aigР“С�e",
Ucirc:"U accent circonflexe",Uuml:"U trР“В©ma",Yacute:"Y accent aigР“С�e",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a accent grave",aacute:"a accent aigР“С�e",acirc:"a accent circonflexe",atilde:"a tilde",auml:"a trР“В©ma",aring:"a avec un cercle au dessus",aelig:"Р“В¦",ccedil:"c cР“В©dille",egrave:"e accent grave",eacute:"e accent aigР“С�e",ecirc:"e accent circonflexe",euml:"e trР“В©ma",igrave:"i accent grave",iacute:"i accent aigР“С�e",icirc:"i accent circonflexe",iuml:"i trР“В©ma",
eth:"Lettre minuscule islandaise ED",ntilde:"n tilde",ograve:"o accent grave",oacute:"o accent aigР“С�e",ocirc:"O accent circonflexe",otilde:"O tilde",ouml:"O trР“В©ma",divide:"Symbole de division",oslash:"o barrР“В©",ugrave:"u accent grave",uacute:"u accent aigР“С�e",ucirc:"u accent circonflexe",uuml:"u trР“В©ma",yacute:"y accent aigР“С�e",thorn:"Lettre islandaise thorn minuscule",yuml:"y trР“В©ma",OElig:"ligature majuscule latine Р•вЂ™",oelig:"ligature minuscule latine Р•вЂњ",372:"W accent circonflexe",374:"Y accent circonflexe",
373:"w accent circonflexe",375:"y accent circonflexe",sbquo:"Guillemet simple fermant",8219:"Guillemet-virgule supР“В©rieur culbutР“В©",bdquo:"Guillemet-virgule double infР“В©rieur",hellip:"Points de suspension",trade:"Symbole de marque dР“В©posР“В©e",9658:"FlР“РЃche noire pointant vers la droite",bull:"Puce",rarr:"FlР“РЃche vers la droite",rArr:"FlР“РЃche double vers la droite",hArr:"FlР“РЃche double vers la gauche",diams:"Carreau",asymp:"Presque Р“В©gal"});