РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr",{euro:"Symbole euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret demi-cadratin",mdash:"Tiret cadratin",iexcl:"Point d'exclamation inversР“В©",cent:"Symbole cent",pound:"Symbole Livre sterling",curren:"Symbole monР“В©taire",yen:"Symbole yen",brvbar:"Barre verticale scindР“В©e",sect:"Signe de section",uml:"TrР“В©ma",copy:"Symbole Copyright",ordf:"Indicateur ordinal fР“В©minin",
laquo:"Guillemet franР“В§ais ouvrant",not:"Crochet de nР“В©gation",reg:"Symbole de marque dР“В©posР“В©e",macr:"Macron",deg:"Symbole degrР“В©",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aigu",micro:"Symbole micro",para:"Symbole pied-de-mouche",middot:"Point mР“В©dian",cedil:"CР“В©dille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franР“В§ais fermant",frac14:"Fraction un quart",frac12:"Fraction un demi",frac34:"Fraction trois quarts",iquest:"Point d'interrogation inversР“В©",Agrave:"A accent grave majuscule",
Aacute:"A accent aigu majuscule",Acirc:"A accent circonflexe majuscule",Atilde:"A caron majuscule",Auml:"A trР“В©ma majuscule",Aring:"A rond majuscule",AElig:"Ligature Р“вЂ  majuscule",Ccedil:"C cР“В©dille majuscule",Egrave:"E accent grave majuscule",Eacute:"E accent aigu majuscule",Ecirc:"E accent circonflexe majuscule",Euml:"E trР“В©ma majuscule",Igrave:"I accent grave majuscule",Iacute:"I accent aigu majuscule",Icirc:"I accent circonflexe majuscule",Iuml:"I trР“В©ma majuscule",ETH:"Lettre majuscule islandaise ED",
Ntilde:"N caron majuscule",Ograve:"O accent grave majuscule",Oacute:"O accent aigu majuscule",Ocirc:"O accent circonflexe majuscule",Otilde:"O caron majuscule",Ouml:"O trР“В©ma majuscule",times:"Symbole de multiplication",Oslash:"O barrР“В© majuscule",Ugrave:"U accent grave majuscule",Uacute:"U accent aigu majuscule",Ucirc:"U accent circonflexe majuscule",Uuml:"U trР“В©ma majuscule",Yacute:"Y accent aigu majuscule",THORN:"Lettre islandaise thorn majuscule",szlig:"Lettre minuscule allemande S dur",agrave:"A accent grave minuscule",
aacute:"A accent aigu minuscule",acirc:"A accent circonflexe minuscule",atilde:"A tilde minuscule",auml:"A trР“В©ma minuscule",aring:"A rond minuscule",aelig:"Ligature Р“вЂ  minuscule",ccedil:"C cР“В©dille minuscule",egrave:"E accent grave minuscule",eacute:"E accent aigu minuscule",ecirc:"E accent circonflexe minuscule",euml:"E trР“В©ma minuscule",igrave:"I accent grave minuscule",iacute:"I accent aigu minuscule",icirc:"I accent circonflexe minuscule",iuml:"i minuscule trР“В©ma",eth:"Lettre minuscule islandaise ED",
ntilde:"N caron minuscule",ograve:"O minuscule accent grave",oacute:"O accent aigu minuscule",ocirc:"O accent circonflexe minuscule",otilde:"O tilde minuscule",ouml:"O trР“В©ma minuscule",divide:"Symbole de division",oslash:"O barrР“В© minuscule",ugrave:"U accent grave minuscule",uacute:"U accent aigu minuscule",ucirc:"U accent circonflexe minuscule",uuml:"U trР“В©ma minuscule",yacute:"Y accent aigu minuscule",thorn:"Lettre islandaise thorn minuscule",yuml:"Y trР“В©ma minuscule",OElig:"Ligature Р•вЂ™ majuscule",
oelig:"Ligature Р•вЂ™ minuscule",372:"W accent circonflexe majuscule",374:"Y accent circonflexe majuscule",373:"W accent circonflexe minuscule",375:"Y accent circonflexe minuscule",sbquo:"Guillemet simple fermant infР“В©rieur",8219:"Guillemet-virgule supР“В©rieur culbutР“В©",bdquo:"Guillemet-virgule double infР“В©rieur",hellip:"Points de suspension",trade:"Symbole de marque commerciale",9658:"FlР“РЃche noire pointant vers la droite",bull:"Gros point mР“В©dian",rarr:"FlР“РЃche vers la droite",rArr:"Double flР“РЃche vers la droite",
hArr:"Double flР“РЃche vers la gauche",diams:"Losange noir",asymp:"Environ Р“В©gal"});