РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","gl",{euro:"SР“В­mbolo do euro",lsquo:"ComiР“В±a simple esquerda",rsquo:"ComiР“В±a simple dereita",ldquo:"ComiР“В±as dobres esquerda",rdquo:"ComiР“В±as dobres dereita",ndash:"GuiР“С–n",mdash:"Raia",iexcl:"Signo de admiraciР“С–n invertido",cent:"SР“В­mbolo do centavo",pound:"SР“В­mbolo da libra",curren:"SР“В­mbolo de moeda",yen:"SР“В­mbolo do yen",brvbar:"Barra vertical rota",sect:"SР“В­mbolo de secciР“С–n",uml:"DiР“В©rese",copy:"SР“В­mbolo de dereitos de autorР“В­a",ordf:"Indicador ordinal feminino",laquo:"ComiР“В±as latinas, apertura",
not:"Signo negaciР“С–n",reg:"SР“В­mbolo de marca rexistrada",macr:"GuiР“С–n alto",deg:"Signo de grao",sup2:"SuperР“В­ndice dous",sup3:"SuperР“В­ndice tres",acute:"Acento agudo",micro:"Signo de micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"SuperР“В­ndice un",ordm:"Indicador ordinal masculino",raquo:"ComiР“В±as latinas, peche",frac14:"FracciР“С–n ordinaria de un cuarto",frac12:"FracciР“С–n ordinaria de un medio",frac34:"FracciР“С–n ordinaria de tres cuartos",iquest:"Signo de interrogaciР“С–n invertido",Agrave:"Letra A latina maiР“С”scula con acento grave",
Aacute:"Letra A latina maiР“С”scula con acento agudo",Acirc:"Letra A latina maiР“С”scula con acento circunflexo",Atilde:"Letra A latina maiР“С”scula con til",Auml:"Letra A latina maiР“С”scula con diР“В©rese",Aring:"Letra A latina maiР“С”scula con aro enriba",AElig:"Letra Р“вЂ  latina maiР“С”scula",Ccedil:"Letra C latina maiР“С”scula con cedilla",Egrave:"Letra E latina maiР“С”scula con acento grave",Eacute:"Letra E latina maiР“С”scula con acento agudo",Ecirc:"Letra E latina maiР“С”scula con acento circunflexo",Euml:"Letra E latina maiР“С”scula con diР“В©rese",
Igrave:"Letra I latina maiР“С”scula con acento grave",Iacute:"Letra I latina maiР“С”scula con acento agudo",Icirc:"Letra I latina maiР“С”scula con acento circunflexo",Iuml:"Letra I latina maiР“С”scula con diР“В©rese",ETH:"Letra Ed latina maiР“С”scula",Ntilde:"Letra N latina maiР“С”scula con til",Ograve:"Letra O latina maiР“С”scula con acento grave",Oacute:"Letra O latina maiР“С”scula con acento agudo",Ocirc:"Letra O latina maiР“С”scula con acento circunflexo",Otilde:"Letra O latina maiР“С”scula con til",Ouml:"Letra O latina maiР“С”scula con diР“В©rese",
times:"Signo de multiplicaciР“С–n",Oslash:"Letra O latina maiР“С”scula con barra transversal",Ugrave:"Letra U latina maiР“С”scula con acento grave",Uacute:"Letra U latina maiР“С”scula con acento agudo",Ucirc:"Letra U latina maiР“С”scula con acento circunflexo",Uuml:"Letra U latina maiР“С”scula con diР“В©rese",Yacute:"Letra Y latina maiР“С”scula con acento agudo",THORN:"Letra Thorn latina maiР“С”scula",szlig:"Letra s latina forte minР“С”scula",agrave:"Letra a latina minР“С”scula con acento grave",aacute:"Letra a latina minР“С”scula con acento agudo",
acirc:"Letra a latina minР“С”scula con acento circunflexo",atilde:"Letra a latina minР“С”scula con til",auml:"Letra a latina minР“С”scula con diР“В©rese",aring:"Letra a latina minР“С”scula con aro enriba",aelig:"Letra Р“В¦ latina minР“С”scula",ccedil:"Letra c latina minР“С”scula con cedilla",egrave:"Letra e latina minР“С”scula con acento grave",eacute:"Letra e latina minР“С”scula con acento agudo",ecirc:"Letra e latina minР“С”scula con acento circunflexo",euml:"Letra e latina minР“С”scula con diР“В©rese",igrave:"Letra i latina minР“С”scula con acento grave",
iacute:"Letra i latina minР“С”scula con acento agudo",icirc:"Letra i latina minР“С”scula con acento circunflexo",iuml:"Letra i latina minР“С”scula con diР“В©rese",eth:"Letra ed latina minР“С”scula",ntilde:"Letra n latina minР“С”scula con til",ograve:"Letra o latina minР“С”scula con acento grave",oacute:"Letra o latina minР“С”scula con acento agudo",ocirc:"Letra o latina minР“С”scula con acento circunflexo",otilde:"Letra o latina minР“С”scula con til",ouml:"Letra o latina minР“С”scula con diР“В©rese",divide:"Signo de divisiР“С–n",oslash:"Letra o latina minР“С”scula con barra transversal",
ugrave:"Letra u latina minР“С”scula con acento grave",uacute:"Letra u latina minР“С”scula con acento agudo",ucirc:"Letra u latina minР“С”scula con acento circunflexo",uuml:"Letra u latina minР“С”scula con diР“В©rese",yacute:"Letra y latina minР“С”scula con acento agudo",thorn:"Letra Thorn latina minР“С”scula",yuml:"Letra y latina minР“С”scula con diР“В©rese",OElig:"Ligadura OE latina maiР“С”scula",oelig:"Ligadura oe latina minР“С”scula",372:"Letra W latina maiР“С”scula con acento circunflexo",374:"Letra Y latina maiР“С”scula con acento circunflexo",
373:"Letra w latina minР“С”scula con acento circunflexo",375:"Letra y latina minР“С”scula con acento circunflexo",sbquo:"ComiР“В±a simple baixa, de apertura",8219:"ComiР“В±a simple alta, de peche",bdquo:"ComiР“В±as dobres baixas, de apertura",hellip:"Elipse, puntos suspensivos",trade:"Signo de marca rexistrada",9658:"Apuntador negro apuntando Р“РЋ dereita",bull:"ViР“В±eta",rarr:"Frecha Р“РЋ dereita",rArr:"Frecha dobre Р“РЋ dereita",hArr:"Frecha dobre da esquerda Р“РЋ dereita",diams:"Diamante negro",asymp:"Case igual a"});