РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","hu",{euro:"EurР“С– jel",lsquo:"Bal szimpla idР“В©zР•вЂ�jel",rsquo:"Jobb szimpla idР“В©zР•вЂ�jel",ldquo:"Bal dupla idР“В©zР•вЂ�jel",rdquo:"Jobb dupla idР“В©zР•вЂ�jel",ndash:"RР“В¶vid gondolatjel",mdash:"HosszР“С” gondolatjel",iexcl:"FordР“В­tott felkiР“РЋltР“С–jel",cent:"Cent jel",pound:"Font jel",curren:"Valuta jel",yen:"Yen jel",brvbar:"HosszР“С” kettР•вЂ�spont",sect:"Paragrafus jel",uml:"KettР•вЂ�s hangzР“С– jel",copy:"SzerzР•вЂ�i jog jel",ordf:"NР•вЂ�i sorrend mutatР“С–ja",laquo:"Balra mutatР“С– duplanyР“В­l",not:"FeltР“В©teles kР“В¶tР•вЂ�jel",
reg:"Bejegyzett vР“В©djegy jele",macr:"HosszР“С”sР“РЋgi jel",deg:"Fok jel",sup2:"NР“В©gyzeten jel",sup3:"KР“В¶bР“В¶n jel",acute:"Р“вЂ°les Р“В©kezet",micro:"Mikro-jel",para:"BekezdР“В©s jel",middot:"KР“В¶zР“В©p pont",cedil:"CР“В©dille",sup1:"ElsР•вЂ�n jel",ordm:"FР“В©rfi sorrend mutatР“С–ja",raquo:"Jobbra mutatР“С– duplanyР“В­l",frac14:"Egy negyed jel",frac12:"Egy ketted jel",frac34:"HР“РЋrom negyed jel",iquest:"FordР“В­tott kР“В©rdР•вЂ�jel",Agrave:"Latin nagy A fordР“В­tott Р“В©kezettel",Aacute:"Latin nagy A normР“РЋl Р“В©kezettel",Acirc:"Latin nagy A hajtott Р“В©kezettel",Atilde:"Latin nagy A hullР“РЋmjellel",
Auml:"Latin nagy A kettР•вЂ�spont Р“В©kezettel",Aring:"Latin nagy A gyР•В±rР•В± Р“В©kezettel",AElig:"Latin nagy Р“вЂ  betР•В±",Ccedil:"Latin nagy C cedillР“РЋval",Egrave:"Latin nagy E fordР“В­tott Р“В©kezettel",Eacute:"Latin nagy E normР“РЋl Р“В©kezettel",Ecirc:"Latin nagy E hajtott Р“В©kezettel",Euml:"Latin nagy E dupla kettР•вЂ�spont Р“В©kezettel",Igrave:"Latin nagy I fordР“В­tott Р“В©kezettel",Iacute:"Latin nagy I normР“РЋl Р“В©kezettel",Icirc:"Latin nagy I hajtott Р“В©kezettel",Iuml:"Latin nagy I kettР•вЂ�spont Р“В©kezettel",ETH:"Latin nagy Eth betР•В±",Ntilde:"Latin nagy N hullР“РЋmjellel",
Ograve:"Latin nagy O fordР“В­tott Р“В©kezettel",Oacute:"Latin nagy O normР“РЋl Р“В©kezettel",Ocirc:"Latin nagy O hajtott Р“В©kezettel",Otilde:"Latin nagy O hullР“РЋmjellel",Ouml:"Latin nagy O kettР•вЂ�spont Р“В©kezettel",times:"SzorzР“РЋs jel",Oslash:"Latin O betР•В± Р“РЋthР“С”zР“РЋssal",Ugrave:"Latin nagy U fordР“В­tott Р“В©kezettel",Uacute:"Latin nagy U normР“РЋl Р“В©kezettel",Ucirc:"Latin nagy U hajtott Р“В©kezettel",Uuml:"Latin nagy U kettР•вЂ�spont Р“В©kezettel",Yacute:"Latin nagy Y normР“РЋl Р“В©kezettel",THORN:"Latin nagy Thorn betР•В±",szlig:"Latin kis s betР•В±",
agrave:"Latin kis a fordР“В­tott Р“В©kezettel",aacute:"Latin kis a normР“РЋl Р“В©kezettel",acirc:"Latin kis a hajtott Р“В©kezettel",atilde:"Latin kis a hullР“РЋmjellel",auml:"Latin kis a kettР•вЂ�spont Р“В©kezettel",aring:"Latin kis a gyР•В±rР•В± Р“В©kezettel",aelig:"Latin kis Р“В¦ betР•В±",ccedil:"Latin kis c cedillР“РЋval",egrave:"Latin kis e fordР“В­tott Р“В©kezettel",eacute:"Latin kis e normР“РЋl Р“В©kezettel",ecirc:"Latin kis e hajtott Р“В©kezettel",euml:"Latin kis e dupla kettР•вЂ�spont Р“В©kezettel",igrave:"Latin kis i fordР“В­tott Р“В©kezettel",iacute:"Latin kis i normР“РЋl Р“В©kezettel",
icirc:"Latin kis i hajtott Р“В©kezettel",iuml:"Latin kis i kettР•вЂ�spont Р“В©kezettel",eth:"Latin kis eth betР•В±",ntilde:"Latin kis n hullР“РЋmjellel",ograve:"Latin kis o fordР“В­tott Р“В©kezettel",oacute:"Latin kis o normР“РЋl Р“В©kezettel",ocirc:"Latin kis o hajtott Р“В©kezettel",otilde:"Latin kis o hullР“РЋmjellel",ouml:"Latin kis o kettР•вЂ�spont Р“В©kezettel",divide:"OsztР“РЋsjel",oslash:"Latin kis o betР•В± Р“РЋthР“С”zР“РЋssal",ugrave:"Latin kis u fordР“В­tott Р“В©kezettel",uacute:"Latin kis u normР“РЋl Р“В©kezettel",ucirc:"Latin kis u hajtott Р“В©kezettel",
uuml:"Latin kis u kettР•вЂ�spont Р“В©kezettel",yacute:"Latin kis y normР“РЋl Р“В©kezettel",thorn:"Latin kis thorn jel",yuml:"Latin kis y kettР•вЂ�spont Р“В©kezettel",OElig:"Latin nagy OE-jel",oelig:"Latin kis oe-jel",372:"Latin nagy W hajtott Р“В©kezettel",374:"Latin nagy Y hajtott Р“В©kezettel",373:"Latin kis w hajtott Р“В©kezettel",375:"Latin kis y hajtott Р“В©kezettel",sbquo:"NyitР“С– nyomdai szimpla idР“В©zР•вЂ�jel",8219:"ZР“РЋrР“С– nyomdai zР“РЋrР“С– idР“В©zР•вЂ�jel",bdquo:"NyitР“С– nyomdai dupla idР“В©zР•вЂ�jel",hellip:"HР“РЋrom pont",trade:"Kereskedelmi vР“В©djegy jele",
9658:"Jobbra mutatР“С– fekete mutatР“С–",bull:"GolyР“С–",rarr:"Jobbra mutatР“С– nyР“В­l",rArr:"Jobbra mutatР“С– duplanyР“В­l",hArr:"Bal-jobb duplanyР“В­l",diams:"Fekete gyР“В©mР“РЋnt jel",asymp:"Majdnem egyenlР•вЂ� jel"});