РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","lv",{euro:"Euro zР”В«me",lsquo:"KreisР”Рѓ  vienkР”РѓrtР”В«ga pР”вЂњdiР•вЂ a",rsquo:"LabР”Рѓ  vienkР”РѓrtР”В«ga pР”вЂњdiР•вЂ a",ldquo:"KreisР”Рѓ  dubult pР”вЂњdiР•вЂ a",rdquo:"LabР”Рѓ dubult pР”вЂњdiР•вЂ a",ndash:"En svР”В«tra",mdash:"Em svР”В«tra",iexcl:"Apgriezta izsaukuma zР”В«me",cent:"Centu naudas zР”В«me",pound:"SterliР•вЂ u mР”РѓrciР•вЂ u naudas zР”В«me",curren:"ValР•В«tas zР”В«me",yen:"Jenu naudas zР”В«me",brvbar:"VertikР”Рѓla pР”Рѓrrauta lР”В«nija",sect:"ParagrР”Рѓfa zР”В«me",uml:"Diakritiska zР”В«me",copy:"AutortiesР”В«bu zР”В«me",ordf:"SieviР•РЋР”В·as kР”Рѓrtas rР”РѓdР”В«tР”Рѓjs",
laquo:"KreisР”Рѓ dubult stР•В«ra pР”вЂњdiР•вЂ u zР”В«me",not:"NeparakstР”В«ts",reg:"ReР”Р€istrР”вЂњta zР”В«me",macr:"GarumzР”В«me",deg:"GrР”Рѓdu zР”В«me",sup2:"AugР•РЋraksts divi",sup3:"AugР•РЋraksts trР”В«s",acute:"AkР•В«ta uzsvara zР”В«me",micro:"Mikro zР”В«me",para:"Rindkopas zР”В«me ",middot:"VidР”вЂњjs punkts",cedil:"Р”Р‚Р”В·Р”В«tis zem burta",sup1:"AugР•РЋraksts viens",ordm:"VР”В«riР•РЋР”В·Р”В«gas kР”Рѓrtas rР”РѓdР”В«tР”Рѓjs",raquo:"LabР”Рѓ dubult stР•В«ra pР”вЂњdiР•вЂ u zР”В«me",frac14:"VulgР”Рѓra frakcija 1/4",frac12:"VulgР”Рѓra frakcija 1/2",frac34:"VulgР”Рѓra frakcija 3/4",iquest:"Apgriezta jautР”Рѓjuma zР”В«me",Agrave:"Lielais latР”В«Р•вЂ u burts A ar uzsvara zР”В«mi",
Aacute:"Lielais  latР”В«Р•вЂ u burts A ar akР•В«tu uzsvara zР”В«mi",Acirc:"Lielais latР”В«Р•вЂ u burts A ar diakritisku zР”В«mi",Atilde:"Lielais latР”В«Р•вЂ u burts A ar tildi ",Auml:"Lielais latР”В«Р•вЂ u burts A ar diakritisko zР”В«mi",Aring:"Lielais latР”В«Р•вЂ u burts A ar aplР”В«ti augР•РЋР”Рѓ",AElig:"Lielais latР”В«Р•вЂ u burts Р“вЂ ",Ccedil:"Lielais latР”В«Р•вЂ u burts C ar Р”РѓР”В·Р”В«ti zem burta",Egrave:"Lielais latР”В«Р•вЂ u burts E ar apostrofu",Eacute:"Lielais latР”В«Р•вЂ u burts E ar akР•В«tu uzsvara zР”В«mi",Ecirc:"Lielais latР”В«Р•вЂ u burts E ar diakritisko zР”В«mi",Euml:"Lielais latР”В«Р•вЂ u burts E ar diakritisko zР”В«mi",
Igrave:"Lielais latР”В«Р•вЂ u burts I ar uzsvaras  zР”В«mi",Iacute:"Lielais latР”В«Р•вЂ u burts I ar akР•В«tu uzsvara zР”В«mi",Icirc:"Lielais latР”В«Р•вЂ u burts I ar diakritisko zР”В«mi",Iuml:"Lielais latР”В«Р•вЂ u burts I ar diakritisko zР”В«mi",ETH:"Lielais latР”В«Р•вЂ u burts Eth",Ntilde:"Lielais latР”В«Р•вЂ u burts N ar tildi",Ograve:"Lielais latР”В«Р•вЂ u burts O ar uzsvara zР”В«mi",Oacute:"Lielais latР”В«Р•вЂ u burts O ar akР•В«to uzsvara zР”В«mi",Ocirc:"Lielais latР”В«Р•вЂ u burts O ar diakritisko zР”В«mi",Otilde:"Lielais latР”В«Р•вЂ u burts O ar tildi",Ouml:"Lielais latР”В«Р•вЂ u burts O ar diakritisko zР”В«mi",
times:"ReizinР”РѓР•РЋanas zР”В«me ",Oslash:"Lielais latР”В«Р•вЂ u burts O ar iesvР”В«trojumu",Ugrave:"Lielais latР”В«Р•вЂ u burts U ar uzsvaras zР”В«mi",Uacute:"Lielais latР”В«Р•вЂ u burts U ar akР•В«to uzsvars zР”В«mi",Ucirc:"Lielais latР”В«Р•вЂ u burts U ar diakritisko zР”В«mi",Uuml:"Lielais latР”В«Р•вЂ u burts U ar diakritisko zР”В«mi",Yacute:"Lielais latР”В«Р•вЂ u burts Y ar akР•В«to uzsvaras zР”В«mi",THORN:"Lielais latР”В«Р•вЂ u burts torn",szlig:"Mazs latР”В«Р•вЂ u burts ar ligatР•В«ru",agrave:"Mazs latР”В«Р•вЂ u burts a ar uzsvara zР”В«mi",aacute:"Mazs latР”В«Р•вЂ u burts a ar akР•В«to uzsvara zР”В«mi",
acirc:"Mazs latР”В«Р•вЂ u burts a ar diakritisko zР”В«mi",atilde:"Mazs latР”В«Р•вЂ u burts a ar tildi",auml:"Mazs latР”В«Р•вЂ u burts a ar diakritisko zР”В«mi",aring:"Mazs latР”В«Р•вЂ u burts a ar aplР”В«ti augР•РЋР”Рѓ",aelig:"Mazs latР”В«Р•вЂ u burts Р“В¦",ccedil:"Mazs latР”В«Р•вЂ u burts c ar Р”РѓР”В·Р”В«ti zem burta",egrave:"Mazs latР”В«Р•вЂ u burts e ar uzsvara zР”В«mi ",eacute:"Mazs latР”В«Р•вЂ u burts e ar akР•В«tu uzsvara zР”В«mi",ecirc:"Mazs latР”В«Р•вЂ u burts e ar diakritisko zР”В«mi",euml:"Mazs latР”В«Р•вЂ u burts e ar diakritisko zР”В«mi",igrave:"Mazs latР”В«Р•вЂ u burts i ar uzsvara zР”В«mi ",iacute:"Mazs latР”В«Р•вЂ u burts i ar akР•В«tu uzsvara zР”В«mi",
icirc:"Mazs latР”В«Р•вЂ u burts i ar diakritisko zР”В«mi",iuml:"Mazs latР”В«Р•вЂ u burts i ar diakritisko zР”В«mi",eth:"Mazs latР”В«Р•вЂ u burts eth",ntilde:"Mazs latР”В«Р•вЂ u burts n ar tildi",ograve:"Mazs latР”В«Р•вЂ u burts o ar uzsvara zР”В«mi ",oacute:"Mazs latР”В«Р•вЂ u burts o ar akР•В«tu uzsvara zР”В«mi",ocirc:"Mazs latР”В«Р•вЂ u burts o ar diakritisko zР”В«mi",otilde:"Mazs latР”В«Р•вЂ u burts o ar tildi",ouml:"Mazs latР”В«Р•вЂ u burts o ar diakritisko zР”В«mi",divide:"DalР”В«Р•РЋanas zР”В«me",oslash:"Mazs latР”В«Р•вЂ u burts o ar iesvР”В«trojumu",ugrave:"Mazs latР”В«Р•вЂ u burts u ar uzsvara zР”В«mi ",
uacute:"Mazs latР”В«Р•вЂ u burts u ar  akР•В«tu uzsvara zР”В«mi",ucirc:"Mazs latР”В«Р•вЂ u burts u ar diakritisko zР”В«mi",uuml:"Mazs latР”В«Р•вЂ u burts u ar diakritisko zР”В«mi",yacute:"Mazs latР”В«Р•вЂ u burts y ar  akР•В«tu uzsvaras zР”В«mi",thorn:"Mazs latР”В«Р•вЂ u burts torns",yuml:"Mazs latР”В«Р•вЂ u burts y ar diakritisko zР”В«mi",OElig:"Liela latР”В«Р•вЂ u ligatР•В«ra OE",oelig:"Maza latР”В«Р•вЂ u ligatР•В«ra oe",372:"Liels latР”В«Р•вЂ u burts W ar diakritisko zР”В«mi ",374:"Liels latР”В«Р•вЂ u burts Y ar diakritisko zР”В«mi ",373:"Mazs latР”В«Р•вЂ u burts w ar diakritisko zР”В«mi ",375:"Mazs latР”В«Р•вЂ u burts y ar diakritisko zР”В«mi ",
sbquo:"Mazas-9 vienkР”РѓrtР”В«gas pР”вЂњdiР•вЂ as",8219:"Lielas-9 vienkР”РѓrtР”В«gas apgrieztas pР”вЂњdiР•вЂ as",bdquo:"Mazas-9 dubultas pР”вЂњdiР•вЂ as",hellip:"HorizontР”Рѓli daudzpunkti",trade:"PreР”РЊu zР”В«mes zР”В«me",9658:"Melns pa labi pagriezts radР”В«tР”Рѓjs",bull:"Lode",rarr:"Bulta pa labi",rArr:"Dubulta Bulta pa labi",hArr:"Bulta pa kreisi",diams:"Dubulta Bulta pa kreisi",asymp:"GandrР”В«z vienР”Рѓds ar"});