РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","nb",{euro:"Eurosymbol",lsquo:"Venstre enkelt anfР“С‘rselstegn",rsquo:"HР“С‘yre enkelt anfР“С‘rselstegn",ldquo:"Venstre dobbelt anfР“С‘rselstegn",rdquo:"HР“С‘yre anfР“С‘rsesltegn",ndash:"Kort tankestrek",mdash:"Lang tankestrek",iexcl:"Omvendt utropstegn",cent:"Centsymbol",pound:"Pundsymbol",curren:"Valutategn",yen:"Yensymbol",brvbar:"Brutt loddrett strek",sect:"Paragraftegn",uml:"TР“С‘ddel",copy:"Copyrighttegn",ordf:"Feminin ordensindikator",laquo:"Venstre anfР“С‘rselstegn",not:"Negasjonstegn",
reg:"Registrert varemerke-tegn",macr:"Makron",deg:"Gradsymbol",sup2:"Hevet totall",sup3:"Hevet tretall",acute:"Akutt aksent",micro:"Mikrosymbol",para:"Avsnittstegn",middot:"Midtstilt prikk",cedil:"Cedille",sup1:"Hevet ettall",ordm:"Maskulin ordensindikator",raquo:"HР“С‘yre anfР“С‘rselstegn",frac14:"FjerdedelsbrР“С‘k",frac12:"HalvbrР“С‘k",frac34:"Tre fjerdedelers brР“С‘k",iquest:"Omvendt spР“С‘rsmР“Тђlstegn",Agrave:"Stor A med grav aksent",Aacute:"Stor A med akutt aksent",Acirc:"Stor A med cirkumfleks",Atilde:"Stor A med tilde",
Auml:"Stor A med tР“С‘ddel",Aring:"Stor Р“вЂ¦",AElig:"Stor Р“вЂ ",Ccedil:"Stor C med cedille",Egrave:"Stor E med grav aksent",Eacute:"Stor E med akutt aksent",Ecirc:"Stor E med cirkumfleks",Euml:"Stor E med tР“С‘ddel",Igrave:"Stor I med grav aksent",Iacute:"Stor I med akutt aksent",Icirc:"Stor I med cirkumfleks",Iuml:"Stor I med tР“С‘ddel",ETH:"Stor Edd/stungen D",Ntilde:"Stor N med tilde",Ograve:"Stor O med grav aksent",Oacute:"Stor O med akutt aksent",Ocirc:"Stor O med cirkumfleks",Otilde:"Stor O med tilde",Ouml:"Stor O med tР“С‘ddel",
times:"Multiplikasjonstegn",Oslash:"Stor Р“пїЅ",Ugrave:"Stor U med grav aksent",Uacute:"Stor U med akutt aksent",Ucirc:"Stor U med cirkumfleks",Uuml:"Stor U med tР“С‘ddel",Yacute:"Stor Y med akutt aksent",THORN:"Stor Thorn",szlig:"Liten dobbelt-s/Eszett",agrave:"Liten a med grav aksent",aacute:"Liten a med akutt aksent",acirc:"Liten a med cirkumfleks",atilde:"Liten a med tilde",auml:"Liten a med tР“С‘ddel",aring:"Liten Р“Тђ",aelig:"Liten Р“В¦",ccedil:"Liten c med cedille",egrave:"Liten e med grav aksent",eacute:"Liten e med akutt aksent",
ecirc:"Liten e med cirkumfleks",euml:"Liten e med tР“С‘ddel",igrave:"Liten i med grav aksent",iacute:"Liten i med akutt aksent",icirc:"Liten i med cirkumfleks",iuml:"Liten i med tР“С‘ddel",eth:"Liten edd/stungen d",ntilde:"Liten n med tilde",ograve:"Liten o med grav aksent",oacute:"Liten o med akutt aksent",ocirc:"Liten o med cirkumfleks",otilde:"Liten o med tilde",ouml:"Liten o med tР“С‘ddel",divide:"Divisjonstegn",oslash:"Liten Р“С‘",ugrave:"Liten u med grav aksent",uacute:"Liten u med akutt aksent",ucirc:"Liten u med cirkumfleks",
uuml:"Liten u med tР“С‘ddel",yacute:"Liten y med akutt aksent",thorn:"Liten thorn",yuml:"Liten y med tР“С‘ddel",OElig:"Stor ligatur av O og E",oelig:"Liten ligatur av o og e",372:"Stor W med cirkumfleks",374:"Stor Y med cirkumfleks",373:"Liten w med cirkumfleks",375:"Liten y med cirkumfleks",sbquo:"Enkelt lavt 9-anfР“С‘rselstegn",8219:"Enkelt hР“С‘yt reversert 9-anfР“С‘rselstegn",bdquo:"Dobbelt lavt 9-anfР“С‘rselstegn",hellip:"Ellipse",trade:"Varemerkesymbol",9658:"Svart hР“С‘yrevendt peker",bull:"Tykk interpunkt",rarr:"HР“С‘yrevendt pil",
rArr:"Dobbel hР“С‘yrevendt pil",hArr:"Dobbel venstrevendt pil",diams:"Svart ruter",asymp:"Omtrent likhetstegn"});