РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","oc",{euro:"SimbР“Р†l Р“РЃuro",lsquo:"Vergueta simpla dobrenta",rsquo:"Vergueta simpla tampanta",ldquo:"Vergueta dobla dobrenta",rdquo:"Vergueta dobla tampanta",ndash:"Jonhent semi-quadratin",mdash:"Jonhent quadratin",iexcl:"Punt d'exclamacion inversat",cent:"SimbР“Р†l cent",pound:"SimbР“Р†l Liura sterling",curren:"SimbР“Р†l monetari",yen:"SimbР“Р†l iР“РЃn",brvbar:"Barra verticala separada",sect:"Signe de seccion",uml:"TrР“РЃma",copy:"SimbР“Р†l Copyright",ordf:"Indicador ordinal femenin",
laquo:"Vergueta francesa dobrenta",not:"Croquet de negacion",reg:"SimbР“Р†l de marca depausada",macr:"Macron",deg:"SimbР“Р†l gra",sup2:"Exponent 2",sup3:"Exponent 3",acute:"Accent agut",micro:"SimbР“Р†l micro",para:"SimbР“Р†l pР“РЃ de mР“Р†sca",middot:"Punt median",cedil:"Cedilha",sup1:"Exponent 1",ordm:"Indicador ordenal masculin",raquo:"Vergueta francesa tampanta",frac14:"Fraccion un quart",frac12:"Fraccion un miР“РЃg",frac34:"Fraccion tres quarts",iquest:"Punt d'interrogacion inversat",Agrave:"A accent grР“РЃu majuscula",
Aacute:"A accent agut majuscula",Acirc:"A accent circonflР“РЃxe majuscula",Atilde:"A caron majuscula",Auml:"A trР“РЃma majuscula",Aring:"A redond majuscula",AElig:"Ligatura Р“вЂ  majuscula",Ccedil:"C cР“В©dille majuscula",Egrave:"E accent grР“РЃu majuscula",Eacute:"E accent agut majuscula",Ecirc:"E accent circonflР“РЃxe majuscula",Euml:"E trР“РЃma majuscula",Igrave:"I accent grР“РЃu majuscula",Iacute:"I accent agut majuscula",Icirc:"I accent circonflР“РЃxe majuscula",Iuml:"I trР“РЃma majuscula",ETH:"Letra majuscula islandaise ED",
Ntilde:"N caron majuscula",Ograve:"O accent grР“РЃu majuscula",Oacute:"O accent agut majuscula",Ocirc:"O accent circonflР“РЃxe majuscula",Otilde:"O caron majuscula",Ouml:"O trР“РЃma majuscula",times:"SimbР“Р†l de multiplicacion",Oslash:"O raiat majuscula",Ugrave:"U accent grР“РЃu majuscula",Uacute:"U accent agut majuscula",Ucirc:"U accent circonflР“РЃxe majuscula",Uuml:"U trР“РЃma majuscula",Yacute:"Y accent agut majuscula",THORN:"Letra islandesa thorn majuscula",szlig:"Letra minuscula alemanda S dur",agrave:"A accent grР“РЃu minuscula",
aacute:"A accent agut minuscula",acirc:"A accent circonflР“РЃxe minuscula",atilde:"A tilda minuscula",auml:"A trР“РЃma minuscula",aring:"A redond minuscula",aelig:"Ligatura Р“вЂ  minuscula",ccedil:"C cР“В©dille minuscula",egrave:"E accent grР“РЃu minuscula",eacute:"E accent agut minuscula",ecirc:"E accent circonflР“РЃxe minuscula",euml:"E trР“РЃma minuscula",igrave:"I accent grР“РЃu minuscula",iacute:"I accent agut minuscula",icirc:"I accent circonflР“РЃxe minuscula",iuml:"i minuscula trР“РЃma",eth:"Letra minuscula islandaise ED",
ntilde:"N caron minuscula",ograve:"O minuscula accent grР“РЃu",oacute:"O accent agut minuscula",ocirc:"O accent circonflР“РЃxe minuscula",otilde:"O tilda minuscula",ouml:"O trР“РЃma minuscula",divide:"SimbР“Р†l de division",oslash:"O raiat minuscula",ugrave:"U accent grР“РЃu minuscula",uacute:"U accent agut minuscula",ucirc:"U accent circonflР“РЃxe minuscula",uuml:"U trР“РЃma minuscula",yacute:"Y accent agut minuscula",thorn:"Letra islandaise thorn minuscula",yuml:"Y trР“РЃma minuscula",OElig:"Ligatura Р•вЂ™ majuscula",oelig:"Ligatura Р•вЂ™ minuscula",
372:"W accent circonflР“РЃxe majuscula",374:"Y accent circonflР“РЃxe majuscula",373:"W accent circonflР“РЃxe minuscula",375:"Y accent circonflР“РЃxe minuscula",sbquo:"Vergueta simpla tampanta inferior",8219:"Vergueta-virgula superior culbutР“В©",bdquo:"Vergueta-virgula double inferior",hellip:"Punts de suspension",trade:"SimbР“Р†l de marca comerciala",9658:"Sageta negra puntant cap a dreita",bull:"GrР“Р†s punt median",rarr:"Sageta cap a dreita",rArr:"Sageta dobla cap a dreita",hArr:"Sageta dobla cap a esquР“РЃrra",diams:"Lausange negre",
asymp:"Environ egal"});