РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pl",{euro:"Znak euro",lsquo:"CudzysР•вЂљР“С–w pojedynczy otwierajР”вЂ¦cy",rsquo:"CudzysР•вЂљР“С–w pojedynczy zamykajР”вЂ¦cy",ldquo:"CudzysР•вЂљР“С–w apostrofowy otwierajР”вЂ¦cy",rdquo:"CudzysР•вЂљР“С–w apostrofowy zamykajР”вЂ¦cy",ndash:"PР“С–Р•вЂљpauza",mdash:"Pauza",iexcl:"OdwrР“С–cony wykrzyknik",cent:"Znak centa",pound:"Znak funta",curren:"Znak waluty",yen:"Znak jena",brvbar:"Przerwana pionowa kreska",sect:"Paragraf",uml:"Diereza",copy:"Znak praw autorskich",ordf:"WskaР•С”nik rodzaju Р•С�eР•вЂћskiego liczebnika porzР”вЂ¦dkowego",
laquo:"Lewy cudzysР•вЂљР“С–w ostrokР”вЂ¦tny",not:"Znak negacji",reg:"ZastrzeР•С�ony znak towarowy",macr:"Makron",deg:"Znak stopnia",sup2:"Druga potР”в„ўga",sup3:"Trzecia potР”в„ўga",acute:"Akcent ostry",micro:"Znak mikro",para:"Znak akapitu",middot:"Kropka Р•вЂєrodkowa",cedil:"Cedylla",sup1:"Pierwsza potР”в„ўga",ordm:"WskaР•С”nik rodzaju mР”в„ўskiego liczebnika porzР”вЂ¦dkowego",raquo:"Prawy cudzysР•вЂљР“С–w ostrokР”вЂ¦tny",frac14:"UР•вЂљamek zwykР•вЂљy jedna czwarta",frac12:"UР•вЂљamek zwykР•вЂљy jedna druga",frac34:"UР•вЂљamek zwykР•вЂљy trzy czwarte",iquest:"OdwrР“С–cony znak zapytania",
Agrave:"Wielka litera A z akcentem ciР”в„ўР•С�kim",Aacute:"Wielka litera A z akcentem ostrym",Acirc:"Wielka litera A z akcentem przeciР”вЂ¦gР•вЂљym",Atilde:"Wielka litera A z tyldР”вЂ¦",Auml:"Wielka litera A z dierezР”вЂ¦",Aring:"Wielka litera A z kР“С–Р•вЂљkiem",AElig:"Wielka ligatura Р“вЂ ",Ccedil:"Wielka litera C z cedyllР”вЂ¦",Egrave:"Wielka litera E z akcentem ciР”в„ўР•С�kim",Eacute:"Wielka litera E z akcentem ostrym",Ecirc:"Wielka litera E z akcentem przeciР”вЂ¦gР•вЂљym",Euml:"Wielka litera E z dierezР”вЂ¦",Igrave:"Wielka litera I z akcentem ciР”в„ўР•С�kim",
Iacute:"Wielka litera I z akcentem ostrym",Icirc:"Wielka litera I z akcentem przeciР”вЂ¦gР•вЂљym",Iuml:"Wielka litera I z dierezР”вЂ¦",ETH:"Wielka litera Eth",Ntilde:"Wielka litera N z tyldР”вЂ¦",Ograve:"Wielka litera O z akcentem ciР”в„ўР•С�kim",Oacute:"Wielka litera O z akcentem ostrym",Ocirc:"Wielka litera O z akcentem przeciР”вЂ¦gР•вЂљym",Otilde:"Wielka litera O z tyldР”вЂ¦",Ouml:"Wielka litera O z dierezР”вЂ¦",times:"Znak mnoР•С�enia wektorowego",Oslash:"Wielka litera O z przekreР•вЂєleniem",Ugrave:"Wielka litera U z akcentem ciР”в„ўР•С�kim",Uacute:"Wielka litera U z akcentem ostrym",
Ucirc:"Wielka litera U z akcentem przeciР”вЂ¦gР•вЂљym",Uuml:"Wielka litera U z dierezР”вЂ¦",Yacute:"Wielka litera Y z akcentem ostrym",THORN:"Wielka litera Thorn",szlig:"MaР•вЂљa litera ostre s (eszet)",agrave:"MaР•вЂљa litera a z akcentem ciР”в„ўР•С�kim",aacute:"MaР•вЂљa litera a z akcentem ostrym",acirc:"MaР•вЂљa litera a z akcentem przeciР”вЂ¦gР•вЂљym",atilde:"MaР•вЂљa litera a z tyldР”вЂ¦",auml:"MaР•вЂљa litera a z dierezР”вЂ¦",aring:"MaР•вЂљa litera a z kР“С–Р•вЂљkiem",aelig:"MaР•вЂљa ligatura Р“В¦",ccedil:"MaР•вЂљa litera c z cedyllР”вЂ¦",egrave:"MaР•вЂљa litera e z akcentem ciР”в„ўР•С�kim",
eacute:"MaР•вЂљa litera e z akcentem ostrym",ecirc:"MaР•вЂљa litera e z akcentem przeciР”вЂ¦gР•вЂљym",euml:"MaР•вЂљa litera e z dierezР”вЂ¦",igrave:"MaР•вЂљa litera i z akcentem ciР”в„ўР•С�kim",iacute:"MaР•вЂљa litera i z akcentem ostrym",icirc:"MaР•вЂљa litera i z akcentem przeciР”вЂ¦gР•вЂљym",iuml:"MaР•вЂљa litera i z dierezР”вЂ¦",eth:"MaР•вЂљa litera eth",ntilde:"MaР•вЂљa litera n z tyldР”вЂ¦",ograve:"MaР•вЂљa litera o z akcentem ciР”в„ўР•С�kim",oacute:"MaР•вЂљa litera o z akcentem ostrym",ocirc:"MaР•вЂљa litera o z akcentem przeciР”вЂ¦gР•вЂљym",otilde:"MaР•вЂљa litera o z tyldР”вЂ¦",ouml:"MaР•вЂљa litera o z dierezР”вЂ¦",
divide:"Anglosaski znak dzielenia",oslash:"MaР•вЂљa litera o z przekreР•вЂєleniem",ugrave:"MaР•вЂљa litera u z akcentem ciР”в„ўР•С�kim",uacute:"MaР•вЂљa litera u z akcentem ostrym",ucirc:"MaР•вЂљa litera u z akcentem przeciР”вЂ¦gР•вЂљym",uuml:"MaР•вЂљa litera u z dierezР”вЂ¦",yacute:"MaР•вЂљa litera y z akcentem ostrym",thorn:"MaР•вЂљa litera thorn",yuml:"MaР•вЂљa litera y z dierezР”вЂ¦",OElig:"Wielka ligatura OE",oelig:"MaР•вЂљa ligatura oe",372:"Wielka litera W z akcentem przeciР”вЂ¦gР•вЂљym",374:"Wielka litera Y z akcentem przeciР”вЂ¦gР•вЂљym",373:"MaР•вЂљa litera w z akcentem przeciР”вЂ¦gР•вЂљym",
375:"MaР•вЂљa litera y z akcentem przeciР”вЂ¦gР•вЂљym",sbquo:"Pojedynczy apostrof dolny",8219:"Pojedynczy apostrof gР“С–rny",bdquo:"PodwР“С–jny apostrof dolny",hellip:"Wielokropek",trade:"Znak towarowy",9658:"Czarny wskaР•С”nik wskazujР”вЂ¦cy w prawo",bull:"Punktor",rarr:"StrzaР•вЂљka w prawo",rArr:"PodwР“С–jna strzaР•вЂљka w prawo",hArr:"PodwР“С–jna strzaР•вЂљka obustronna",diams:"Czarny znak karo",asymp:"Znak prawie rР“С–wne"});