РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt-br",{euro:"Euro",lsquo:"Aspas simples esquerda",rsquo:"Aspas simples direita",ldquo:"Aspas duplas esquerda",rdquo:"Aspas duplas direita",ndash:"TraР“В§o",mdash:"TravessР“Р€o",iexcl:"Ponto de exclamaР“В§Р“Р€o invertido",cent:"Cent",pound:"Cerquilha",curren:"Dinheiro",yen:"Yen",brvbar:"Bara interrompida",sect:"SР“В­mbolo de ParР“РЋgrafo",uml:"Trema",copy:"Direito de CР“С–pia",ordf:"Indicador ordinal feminino",laquo:"Aspas duplas angulares esquerda",not:"NegaР“В§Р“Р€o",reg:"Marca Registrada",
macr:"MР“РЋcron",deg:"Grau",sup2:"2 Superscrito",sup3:"3 Superscrito",acute:"Acento agudo",micro:"Micro",para:"PР“В© de mosca",middot:"Ponto mediano",cedil:"Cedilha",sup1:"1 Superscrito",ordm:"Indicador ordinal masculino",raquo:"Aspas duplas angulares direita",frac14:"Um quarto",frac12:"Um meio",frac34:"TrР“Р„s quartos",iquest:"InterrogaР“В§Р“Р€o invertida",Agrave:"A maiР“С”sculo com acento grave",Aacute:"A maiР“С”sculo com acento agudo",Acirc:"A maiР“С”sculo com acento circunflexo",Atilde:"A maiР“С”sculo com til",Auml:"A maiР“С”sculo com trema",
Aring:"A maiР“С”sculo com anel acima",AElig:"Р“вЂ  maiР“С”sculo",Ccedil:"Р“вЂЎ maiР“С”lculo",Egrave:"E maiР“С”sculo com acento grave",Eacute:"E maiР“С”sculo com acento agudo",Ecirc:"E maiР“С”sculo com acento circumflexo",Euml:"E maiР“С”sculo com trema",Igrave:"I maiР“С”sculo com acento grave",Iacute:"I maiР“С”sculo com acento agudo",Icirc:"I maiР“С”sculo com acento circunflexo",Iuml:"I maiР“С”sculo com crase",ETH:"Eth maiР“С”sculo",Ntilde:"N maiР“С”sculo com til",Ograve:"O maiР“С”sculo com acento grave",Oacute:"O maiР“С”sculo com acento agudo",Ocirc:"O maiР“С”sculo com acento circunflexo",
Otilde:"O maiР“С”sculo com til",Ouml:"O maiР“С”sculo com trema",times:"MultiplicaР“В§Р“Р€o",Oslash:"DiР“Сћmetro",Ugrave:"U maiР“С”sculo com acento grave",Uacute:"U maiР“С”sculo com acento agudo",Ucirc:"U maiР“С”sculo com acento circunflexo",Uuml:"U maiР“С”sculo com trema",Yacute:"Y maiР“С”sculo com acento agudo",THORN:"Thorn maiР“С”sculo",szlig:"Eszett minР“С”sculo",agrave:"a minР“С”sculo com acento grave",aacute:"a minР“С”sculo com acento agudo",acirc:"a minР“С”sculo com acento circunflexo",atilde:"a minР“С”sculo com til",auml:"a minР“С”sculo com trema",
aring:"a minР“С”sculo com anel acima",aelig:"Р“В¦ minР“С”sculo",ccedil:"Р“В§ minР“С”sculo",egrave:"e minР“С”sculo com acento grave",eacute:"e minР“С”sculo com acento agudo",ecirc:"e minР“С”sculo com acento circunflexo",euml:"e minР“С”sculo com trema",igrave:"i minР“С”sculo com acento grave",iacute:"i minР“С”sculo com acento agudo",icirc:"i minР“С”sculo com acento circunflexo",iuml:"i minР“С”sculo com trema",eth:"eth minР“С”sculo",ntilde:"n minР“С”sculo com til",ograve:"o minР“С”sculo com acento grave",oacute:"o minР“С”sculo com acento agudo",ocirc:"o minР“С”sculo com acento circunflexo",
otilde:"o minР“С”sculo com til",ouml:"o minР“С”sculo com trema",divide:"DivisР“Р€o",oslash:"o minР“С”sculo com cortado ou diР“Сћmetro",ugrave:"u minР“С”sculo com acento grave",uacute:"u minР“С”sculo com acento agudo",ucirc:"u minР“С”sculo com acento circunflexo",uuml:"u minР“С”sculo com trema",yacute:"y minР“С”sculo com acento agudo",thorn:"thorn minР“С”sculo",yuml:"y minР“С”sculo com trema",OElig:"LigaР“В§Р“Р€o tipogrР“РЋfica OE maiР“С”scula",oelig:"LigaР“В§Р“Р€o tipogrР“РЋfica oe minР“С”scula",372:"W maiР“С”sculo com acento circunflexo",374:"Y maiР“С”sculo com acento circunflexo",
373:"w minР“С”sculo com acento circunflexo",375:"y minР“С”sculo com acento circunflexo",sbquo:"Aspas simples inferior direita",8219:"Aspas simples superior esquerda",bdquo:"Aspas duplas inferior direita",hellip:"ReticР“Р„ncias",trade:"Trade mark",9658:"Ponta de seta preta para direita",bull:"Ponto lista",rarr:"Seta para direita",rArr:"Seta dupla para direita",hArr:"Seta dupla direita e esquerda",diams:"Ouros",asymp:"Aproximadamente"});