РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt",{euro:"SР“В­mbolo de Euro",lsquo:"Aspa esquerda simples",rsquo:"Aspa direita simples",ldquo:"Aspa esquerda dupla",rdquo:"Aspa direita dupla",ndash:"TravessР“Р€o simples",mdash:"TravessР“Р€o longo",iexcl:"Ponto de exclamaР“В§Р“Р€o invertido",cent:"SР“В­mbolo de cР“Р„ntimo",pound:"SР“В­mbolo de Libra",curren:"SР“В­mbolo de Moeda",yen:"SР“В­mbolo de Iene",brvbar:"Barra quebrada",sect:"SР“В­mbolo de secР“В§Р“Р€o",uml:"Trema",copy:"SР“В­mbolo de direitos de autor",ordf:"Indicador ordinal feminino",laquo:"Aspa esquerda Р“Сћngulo duplo",
not:"NР“Р€o sР“В­mbolo",reg:"SР“В­mbolo de registado",macr:"MР“РЋcron",deg:"SР“В­mbolo de graus",sup2:"Expoente 2",sup3:"Expoente 3",acute:"Acento agudo",micro:"SР“В­mbolo de micro",para:"SР“В­mbolo de parР“РЋgrafo",middot:"Ponto do meio",cedil:"Cedilha",sup1:"Expoente 1",ordm:"Indicador ordinal masculino",raquo:"Aspas Р“Сћngulo duplo para a direita",frac14:"FraР“В§Р“Р€o vulgar 1/4",frac12:"FraР“В§Р“Р€o vulgar 1/2",frac34:"FraР“В§Р“Р€o vulgar 3/4",iquest:"Ponto de interrogaР“В§Р“Р€o invertido",Agrave:"Letra maiР“С”scula latina A com acento grave",Aacute:"Letra maiР“С”scula latina A com acento agudo",
Acirc:"Letra maiР“С”scula latina A com circunflexo",Atilde:"Letra maiР“С”scula latina A com til",Auml:"Letra maiР“С”scula latina A com trema",Aring:"Letra maiР“С”scula latina A com sinal diacrР“В­tico",AElig:"Letra maiР“С”scula latina Р“вЂ ",Ccedil:"Letra maiР“С”scula latina C com cedilha",Egrave:"Letra maiР“С”scula latina E com acento grave",Eacute:"Letra maiР“С”scula latina E com acento agudo",Ecirc:"Letra maiР“С”scula latina E com circunflexo",Euml:"Letra maiР“С”scula latina E com trema",Igrave:"Letra maiР“С”scula latina I com acento grave",
Iacute:"Letra maiР“С”scula latina I com acento agudo",Icirc:"Letra maiР“С”scula latina I com cincunflexo",Iuml:"Letra maiР“С”scula latina I com trema",ETH:"Letra maiР“С”scula latina Eth (Р“С’Р“В°)",Ntilde:"Letra maiР“С”scula latina N com til",Ograve:"Letra maiР“С”scula latina O com acento grave",Oacute:"Letra maiР“С”scula latina O com acento agudo",Ocirc:"Letra maiР“С”scula latina I com circunflexo",Otilde:"Letra maiР“С”scula latina O com til",Ouml:"Letra maiР“С”scula latina O com trema",times:"SР“В­mbolo de multiplicaР“В§Р“Р€o",Oslash:"Letra maiР“С”scula O com barra",
Ugrave:"Letra maiР“С”scula latina U com acento grave",Uacute:"Letra maiР“С”scula latina U com acento agudo",Ucirc:"Letra maiР“С”scula latina U com circunflexo",Uuml:"Letra maiР“С”scula latina E com trema",Yacute:"Letra maiР“С”scula latina Y com acento agudo",THORN:"Letra maiР“С”scula latina RР“С”nico",szlig:"Letra minР“С”scula latina s forte",agrave:"Letra minР“С”scula latina a com acento grave",aacute:"Letra minР“С”scula latina a com acento agudo",acirc:"Letra minР“С”scula latina a com circunflexo",atilde:"Letra minР“С”scula latina a com til",
auml:"Letra minР“С”scula latina a com trema",aring:"Letra minР“С”scula latina a com sinal diacrР“В­tico",aelig:"Letra minР“С”scula latina Р“В¦",ccedil:"Letra minР“С”scula latina c com cedilha",egrave:"Letra minР“С”scula latina e com acento grave",eacute:"Letra minР“С”scula latina e com acento agudo",ecirc:"Letra minР“С”scula latina e com circunflexo",euml:"Letra minР“С”scula latina e com trema",igrave:"Letra minР“С”scula latina i com acento grave",iacute:"Letra minР“С”scula latina i com acento agudo",icirc:"Letra minР“С”scula latina i com circunflexo",
iuml:"Letra pequena latina i com trema",eth:"Letra minР“С”scula latina eth",ntilde:"Letra minР“С”scula latina n com til",ograve:"Letra minР“С”scula latina o com acento grave",oacute:"Letra minР“С”scula latina o com acento agudo",ocirc:"Letra minР“С”scula latina o com circunflexo",otilde:"Letra minР“С”scula latina o com til",ouml:"Letra minР“С”scula latina o com trema",divide:"SР“В­mbolo de divisР“Р€o",oslash:"Letra minР“С”scula latina o com barra",ugrave:"Letra minР“С”scula latina u com acento grave",uacute:"Letra minР“С”scula latina u com acento agudo",
ucirc:"Letra minР“С”scula latina u com circunflexo",uuml:"Letra minР“С”scula latina u com trema",yacute:"Letra minР“С”scula latina y com acento agudo",thorn:"Letra minР“С”scula latina RР“С”nico",yuml:"Letra minР“С”scula latina y com trema",OElig:"Ligadura maiР“С”scula latina OE",oelig:"Ligadura minР“С”scula latina oe",372:"Letra maiР“С”scula latina W com circunflexo",374:"Letra maiР“С”scula latina Y com circunflexo",373:"Letra minР“С”scula latina w com circunflexo",375:"Letra minР“С”scula latina y com circunflexo",sbquo:"Aspa Simples inferior-9",
8219:"Aspa simples superior invertida-9",bdquo:"Aspa duplas inferior-9",hellip:"Elipse horizontal ",trade:"SР“В­mbolo de marca registada",9658:"Ponteiro preto direito",bull:"Marca",rarr:"Seta para a direita",rArr:"Seta dupla para a direita",hArr:"Seta dupla direita esquerda",diams:"Naipe diamante preto",asymp:"Quase igual a "});