РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sk",{euro:"Znak eura",lsquo:"Р”Р…avР“РЋ jednoduchР“РЋ Р“С”vodzovka",rsquo:"PravР“РЋ jednoduchР“РЋ Р“С”vodzovka",ldquo:"PravР“РЋ dvojitР“РЋ Р“С”vodzovka",rdquo:"PravР“РЋ dvojitР“РЋ Р“С”vodzovka",ndash:"En pomlР”РЊka",mdash:"Em pomlР”РЊka",iexcl:"ObrР“РЋtenР“Р… vР“Р…kriР”РЊnР“В­k",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"PreruР•РЋenР“РЋ zvislР“РЋ Р”РЊiara",sect:"Znak odseku",uml:"PrehlР“РЋska",copy:"Znak copyrightu",ordf:"Р•Р…enskР“Р… indikР“РЋtor rodu",laquo:"Znak dvojitР“Р…ch lomenР“Р…ch Р“С”vodzoviek vР”С•avo",not:"LogistickР“Р… zР“РЋpor",
reg:"Znak registrР“РЋcie",macr:"PomlР”РЊka nad",deg:"Znak stupР•в‚¬a",sup2:"Dvojka ako hornР“Р… index",sup3:"Trojka ako hornР“Р… index",acute:"DР”С”Р•С•eР•в‚¬",micro:"Znak mikro",para:"Znak odstavca",middot:"Bodka uprostred",cedil:"Chvost vР”С•avo",sup1:"Jednotka ako hornР“Р… index",ordm:"MuР•С•skР“Р… indikР“РЋtor rodu",raquo:"Znak dvojitР“Р…ch lomenР“Р…ch Р“С”vodzoviek vpravo",frac14:"ObyР”РЊajnР“Р… zlomok jedna Р•РЋtvrtina",frac12:"ObyР”РЊajnР“Р… zlomok jedna polovica",frac34:"ObyР”РЊajnР“Р… zlomok tri Р•РЋtvrtiny",iquest:"OtoР”РЊenР“Р… otР“РЋznik",Agrave:"VeР”С•kР“В© pР“В­smeno latinky A s accentom",
Aacute:"VeР”С•kР“В© pР“В­smeno latinky A s dР”С”Р•С•Р•в‚¬om",Acirc:"VeР”С•kР“В© pР“В­smeno latinky A s mР“В¤kР”РЊeР•в‚¬om",Atilde:"VeР”С•kР“В© pР“В­smeno latinky A s tildou",Auml:"VeР”С•kР“В© pР“В­smeno latinky A s dvoma bodkami",Aring:"VeР”С•kР“В© pР“В­smeno latinky A s krР“С”Р•С•kom nad",AElig:"VeР”С•kР“В© pР“В­smeno latinky Р“вЂ ",Ccedil:"VeР”С•kР“В© pР“В­smeno latinky C s chvostom vР”С•avo",Egrave:"VeР”С•kР“В© pР“В­smeno latinky E s accentom",Eacute:"VeР”С•kР“В© pР“В­smeno latinky E s dР”С”Р•С•Р•в‚¬om",Ecirc:"VeР”С•kР“В© pР“В­smeno latinky E s mР“В¤kР”РЊeР•в‚¬om",Euml:"VeР”С•kР“В© pР“В­smeno latinky E s dvoma bodkami",Igrave:"VeР”С•kР“В© pР“В­smeno latinky I s accentom",
Iacute:"VeР”С•kР“В© pР“В­smeno latinky I s dР”С”Р•С•Р•в‚¬om",Icirc:"VeР”С•kР“В© pР“В­smeno latinky I s mР“В¤kР”РЊeР•в‚¬om",Iuml:"VeР”С•kР“В© pР“В­smeno latinky I s dvoma bodkami",ETH:"VeР”С•kР“В© pР“В­smeno latinky Eth",Ntilde:"VeР”С•kР“В© pР“В­smeno latinky N s tildou",Ograve:"VeР”С•kР“В© pР“В­smeno latinky O s accentom",Oacute:"VeР”С•kР“В© pР“В­smeno latinky O s dР”С”Р•С•Р•в‚¬om",Ocirc:"VeР”С•kР“В© pР“В­smeno latinky O s mР“В¤kР”РЊeР•в‚¬om",Otilde:"VeР”С•kР“В© pР“В­smeno latinky O s tildou",Ouml:"VeР”С•kР“В© pР“В­smeno latinky O s dvoma bodkami",times:"Znak nР“РЋsobenia",Oslash:"VeР”С•kР“В© pР“В­smeno latinky O preР•РЋkrtnutР“В©",Ugrave:"VeР”С•kР“В© pР“В­smeno latinky U s accentom",
Uacute:"VeР”С•kР“В© pР“В­smeno latinky U s dР”С”Р•С•Р•в‚¬om",Ucirc:"VeР”С•kР“В© pР“В­smeno latinky U s mР“В¤kР”РЊeР•в‚¬om",Uuml:"VeР”С•kР“В© pР“В­smeno latinky U s dvoma bodkami",Yacute:"VeР”С•kР“В© pР“В­smeno latinky Y s dР”С”Р•С•Р•в‚¬om",THORN:"VeР”С•kР“В© pР“В­smeno latinky Thorn",szlig:"MalР“В© pР“В­smeno latinky ostrР“В© s",agrave:"MalР“В© pР“В­smeno latinky a s accentom",aacute:"MalР“В© pР“В­smeno latinky a s dР”С”Р•С•Р•в‚¬om",acirc:"MalР“В© pР“В­smeno latinky a s mР“В¤kР”РЊeР•в‚¬om",atilde:"MalР“В© pР“В­smeno latinky a s tildou",auml:"MalР“В© pР“В­smeno latinky a s dvoma bodkami",aring:"MalР“В© pР“В­smeno latinky a s krР“С”Р•С•kom nad",
aelig:"MalР“В© pР“В­smeno latinky Р“В¦",ccedil:"MalР“В© pР“В­smeno latinky c s chvostom vР”С•avo",egrave:"MalР“В© pР“В­smeno latinky e s accentom",eacute:"MalР“В© pР“В­smeno latinky e s dР”С”Р•С•Р•в‚¬om",ecirc:"MalР“В© pР“В­smeno latinky e s mР“В¤kР”РЊeР•в‚¬om",euml:"MalР“В© pР“В­smeno latinky e s dvoma bodkami",igrave:"MalР“В© pР“В­smeno latinky i s accentom",iacute:"MalР“В© pР“В­smeno latinky i s dР”С”Р•С•Р•в‚¬om",icirc:"MalР“В© pР“В­smeno latinky i s mР“В¤kР”РЊeР•в‚¬om",iuml:"MalР“В© pР“В­smeno latinky i s dvoma bodkami",eth:"MalР“В© pР“В­smeno latinky eth",ntilde:"MalР“В© pР“В­smeno latinky n s tildou",ograve:"MalР“В© pР“В­smeno latinky o s accentom",
oacute:"MalР“В© pР“В­smeno latinky o s dР”С”Р•С•Р•в‚¬om",ocirc:"MalР“В© pР“В­smeno latinky o s mР“В¤kР”РЊeР•в‚¬om",otilde:"MalР“В© pР“В­smeno latinky o s tildou",ouml:"MalР“В© pР“В­smeno latinky o s dvoma bodkami",divide:"Znak delenia",oslash:"MalР“В© pР“В­smeno latinky o preР•РЋkrtnutР“В©",ugrave:"MalР“В© pР“В­smeno latinky u s accentom",uacute:"MalР“В© pР“В­smeno latinky u s dР”С”Р•С•Р•в‚¬om",ucirc:"MalР“В© pР“В­smeno latinky u s mР“В¤kР”РЊeР•в‚¬om",uuml:"MalР“В© pР“В­smeno latinky u s dvoma bodkami",yacute:"MalР“В© pР“В­smeno latinky y s dР”С”Р•С•Р•в‚¬om",thorn:"MalР“В© pР“В­smeno latinky thorn",yuml:"MalР“В© pР“В­smeno latinky y s dvoma bodkami",
OElig:"VeР”С•kР“РЋ ligatР“С”ra latinky OE",oelig:"MalР“РЋ ligatР“С”ra latinky OE",372:"VeР”С•kР“В© pР“В­smeno latinky W s mР“В¤kР”РЊeР•в‚¬om",374:"VeР”С•kР“В© pР“В­smeno latinky Y s mР“В¤kР”РЊeР•в‚¬om",373:"MalР“В© pР“В­smeno latinky w s mР“В¤kР”РЊeР•в‚¬om",375:"MalР“В© pР“В­smeno latinky y s mР“В¤kР”РЊeР•в‚¬om",sbquo:"DolnР“РЋ jednoduchР“РЋ 9-Р“С”vodzovka",8219:"HornР“РЋ jednoduchР“РЋ otoР”РЊenР“РЋ 9-Р“С”vodzovka",bdquo:"DolnР“РЋ dvojitР“РЋ 9-Р“С”vodzovka",hellip:"TrojbodkovР“Р… Р“С”vod",trade:"Znak ibchodnej znaР”РЊky",9658:"Р”РЉierny ukazovateР”С• smerujР“С”ci vpravo",bull:"Kruh",rarr:"Р•В Р“В­pka vpravo",rArr:"DvojitР“РЋ Р•РЋipka vpravo",
hArr:"DvojitР“РЋ Р•РЋipka vР”С•avo a vpravo",diams:"Р”РЉierne piky",asymp:"Skoro sa rovnР“РЋ"});