РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sl",{euro:"Znak za evro",lsquo:"Levi enojni narekovaj",rsquo:"Desni enojni narekovaj",ldquo:"Levi dvojni narekovaj",rdquo:"Desni dvojni narekovaj",ndash:"PomiР•РЋljaj",mdash:"Dolgi pomiР•РЋljaj",iexcl:"Obrnjen klicaj",cent:"Znak za cent",pound:"Znak za funt",curren:"Znak valute",yen:"Znak za jen",brvbar:"Zlomljena Р”РЊrta",sect:"Znak za Р”РЊlen",uml:"Diereza",copy:"Znak avtorskih pravic",ordf:"Р•Р…enski zaporedni kazalnik",laquo:"Levi dvojni lomljeni narekovaj",not:"Znak za ne",
reg:"Registrirani znak",macr:"NadР”РЊrtano",deg:"Znak za stopinje",sup2:"Nadpisano dva",sup3:"Nadpisano tri",acute:"Ostrivec",micro:"Znak za mikro",para:"Znak za odstavek",middot:"Usredinjena pika",cedil:"Cedilla",sup1:"Nadpisano ena",ordm:"MoР•РЋki zaporedni kazalnik",raquo:"Desno obrnjen dvojni kotni narekovaj",frac14:"Ena Р”РЊetrtina",frac12:"Ena polovica",frac34:"Tri Р”РЊetrtine",iquest:"Obrnjen vpraР•РЋaj",Agrave:"Velika latinska Р”РЊrka A s krativcem",Aacute:"Velika latinska Р”РЊrka A z ostrivcem",Acirc:"Velika latinska Р”РЊrka A s streР•РЋico",
Atilde:"Velika latinska Р”РЊrka A z tildo",Auml:"Velika latinska Р”РЊrka A z diaeresis-om",Aring:"Velika latinska Р”РЊrka A z obroР”РЊem",AElig:"Velika latinska Р”РЊrka Р“вЂ ",Ccedil:"Velika latinska Р”РЊrka C s cedillo",Egrave:"Velika latinska Р”РЊrka E s krativcem",Eacute:"Velika latinska Р”РЊrka E z ostrivcem",Ecirc:"Velika latinska Р”РЊrka E s streР•РЋico",Euml:"Velika latinska Р”РЊrka E z diaeresis-om",Igrave:"Velika latinska Р”РЊrka I s krativcem",Iacute:"Velika latinska Р”РЊrka I z ostrivcem",Icirc:"Velika latinska Р”РЊrka I s streР•РЋico",
Iuml:"Velika latinska Р”РЊrka I z diaeresis-om",ETH:"Velika latinska Р”РЊrka Eth",Ntilde:"Velika latinska Р”РЊrka N s tildo",Ograve:"Velika latinska Р”РЊrka O s krativcem",Oacute:"Velika latinska Р”РЊrka O z ostrivcem",Ocirc:"Velika latinska Р”РЊrka O s streР•РЋico",Otilde:"Velika latinska Р”РЊrka O s tildo",Ouml:"Velika latinska Р”РЊrka O z diaeresis-om",times:"Znak za mnoР•С•enje",Oslash:"Velika preР”РЊrtana latinska Р”РЊrka O",Ugrave:"Velika latinska Р”РЊrka U s krativcem",Uacute:"Velika latinska Р”РЊrka U z ostrivcem",Ucirc:"Velika latinska Р”РЊrka U s streР•РЋico",
Uuml:"Velika latinska Р”РЊrka U z diaeresis-om",Yacute:"Velika latinska Р”РЊrka Y z ostrivcem",THORN:"Velika latinska Р”РЊrka Thorn",szlig:"Mala ostra latinska Р”РЊrka s",agrave:"Mala latinska Р”РЊrka a s krativcem",aacute:"Mala latinska Р”РЊrka a z ostrivcem",acirc:"Mala latinska Р”РЊrka a s streР•РЋico",atilde:"Mala latinska Р”РЊrka a s tildo",auml:"Mala latinska Р”РЊrka a z diaeresis-om",aring:"Mala latinska Р”РЊrka a z obroР”РЊem",aelig:"Mala latinska Р”РЊrka Р“В¦",ccedil:"Mala latinska Р”РЊrka c s cedillo",egrave:"Mala latinska Р”РЊrka e s krativcem",
eacute:"Mala latinska Р”РЊrka e z ostrivcem",ecirc:"Mala latinska Р”РЊrka e s streР•РЋico",euml:"Mala latinska Р”РЊrka e z diaeresis-om",igrave:"Mala latinska Р”РЊrka i s krativcem",iacute:"Mala latinska Р”РЊrka i z ostrivcem",icirc:"Mala latinska Р”РЊrka i s streР•РЋico",iuml:"Mala latinska Р”РЊrka i z diaeresis-om",eth:"Mala latinska Р”РЊrka eth",ntilde:"Mala latinska Р”РЊrka n s tildo",ograve:"Mala latinska Р”РЊrka o s krativcem",oacute:"Mala latinska Р”РЊrka o z ostrivcem",ocirc:"Mala latinska Р”РЊrka o s streР•РЋico",otilde:"Mala latinska Р”РЊrka o s tildo",
ouml:"Mala latinska Р”РЊrka o z diaeresis-om",divide:"Znak za deljenje",oslash:"Mala preР”РЊrtana latinska Р”РЊrka o",ugrave:"Mala latinska Р”РЊrka u s krativcem",uacute:"Mala latinska Р”РЊrka u z ostrivcem",ucirc:"Mala latinska Р”РЊrka u s streР•РЋico",uuml:"Mala latinska Р”РЊrka u z diaeresis-om",yacute:"Mala latinska Р”РЊrka y z ostrivcem",thorn:"Mala latinska Р”РЊrka thorn",yuml:"Mala latinska Р”РЊrka y z diaeresis-om",OElig:"Velika latinska ligatura OE",oelig:"Mala latinska ligatura oe",372:"Velika latinska Р”РЊrka W s streР•РЋico",
374:"Velika latinska Р”РЊrka Y s streР•РЋico",373:"Mala latinska Р”РЊrka w s streР•РЋico",375:"Mala latinska Р”РЊrka y s streР•РЋico",sbquo:"Enojni nizki-9 narekovaj",8219:"Enojni visoki-obrnjen-9 narekovaj",bdquo:"Dvojni nizki-9 narekovaj",hellip:"Horizontalni izpust",trade:"Znak blagovne znamke",9658:"Р”РЉrni desno-usmerjen kazalec",bull:"Krogla",rarr:"Desno-usmerjena puР•РЋР”РЊica",rArr:"Desno-usmerjena dvojna puР•РЋР”РЊica",hArr:"Leva in desna dvojna puР•РЋР”РЊica",diams:"Р”РЉrna kara",asymp:"Skoraj enako"});