РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sq",{euro:"Shenja e Euros",lsquo:"ThonjР“В«za majtas me njР“В« vi",rsquo:"ThonjР“В«za djathtas me njР“В« vi",ldquo:"ThonjР“В«za majtas",rdquo:"ThonjР“В«za djathtas",ndash:"En viza lidhР“В«se",mdash:"Em viza lidhР“В«se",iexcl:"PikР“В«Р“В§uditР“В«se e pР“В«rmbysur",cent:"Shenja e Centit",pound:"Shejna e Funtit",curren:"Shenja e valutР“В«s",yen:"Shenja e Jenit",brvbar:"Viza e kР“В«putur",sect:"Shenja e pjesР“В«s",uml:"Diaeresis",copy:"Shenja e tР“В« drejtave tР“В« kopjimit",ordf:"Feminine ordinal indicator",laquo:"Left-pointing double angle quotation mark",
not:"Nuk ka shenjР“В«",reg:"Shenja e tР“В« regjistruarit",macr:"Macron",deg:"Shenja e shkallР“В«s",sup2:"Super-skripta dy",sup3:"Super-skripta tre",acute:"Theks i mprehtР“В«",micro:"Shjenja e Mikros",para:"Pilcrow sign",middot:"Pika e Mesme",cedil:"Hark nР“В«n shkronja",sup1:"Super-skripta njР“В«",ordm:"Masculine ordinal indicator",raquo:"Right-pointing double angle quotation mark",frac14:"Thyesa njР“В« tР“В« katrat",frac12:"Thyesa njР“В« tР“В« dytat",frac34:"Thyesa tre tР“В« katrat",iquest:"PikР“В«pyetje e pР“В«rmbysur",Agrave:"Shkronja e madhe latine A me theks tР“В« rР“В«ndР“В«",
Aacute:"Shkronja e madhe latine A me theks akute",Acirc:"Shkronja e madhe latine A me theks lakor",Atilde:"Shkronja e madhe latine A me tildР“В«",Auml:"Shkronja e madhe latine A me dy pika",Aring:"Shkronja e madhe latine A me unazР“В« mbi",AElig:"Shkronja e madhe latine Р“вЂ ",Ccedil:"Shkronja e madhe latine C me hark poshtР“В«",Egrave:"Shkronja e madhe latine E me theks tР“В« rР“В«ndР“В«",Eacute:"Shkronja e madhe latine E me theks akute",Ecirc:"Shkronja e madhe latine E me theks lakor",Euml:"Shkronja e madhe latine E me dy pika",
Igrave:"Shkronja e madhe latine I me theks tР“В« rР“В«ndР“В«",Iacute:"Shkronja e madhe latine I me theks akute",Icirc:"Shkronja e madhe latine I me theks lakor",Iuml:"Shkronja e madhe latine I me dy pika",ETH:"Shkronja e madhe latine Eth",Ntilde:"Shkronja e madhe latine N me tildР“В«",Ograve:"Shkronja e madhe latine O me theks tР“В« rР“В«ndР“В«",Oacute:"Shkronja e madhe latine O me theks akute",Ocirc:"Shkronja e madhe latine O me theks lakor",Otilde:"Shkronja e madhe latine O me tildР“В«",Ouml:"Shkronja e madhe latine O me dy pika",
times:"Shenja e shumР“В«zimit",Oslash:"Shkronja e madhe latine O me vizР“В« nР“В« mes",Ugrave:"Shkronja e madhe latine U me theks tР“В« rР“В«ndР“В«",Uacute:"Shkronja e madhe latine U me theks akute",Ucirc:"Shkronja e madhe latine U me theks lakor",Uuml:"Shkronja e madhe latine U me dy pika",Yacute:"Shkronja e madhe latine Y me theks akute",THORN:"Shkronja e madhe latine Thorn",szlig:"Shkronja e vogР“В« latine s e mprehtР“В«",agrave:"Shkronja e vogР“В« latine a me theks tР“В« rР“В«ndР“В«",aacute:"Shkronja e vogР“В« latine a me theks tР“В« mprehtР“В«",
acirc:"Shkronja e vogР“В«l latine a me theks lakor",atilde:"Shkronja e vogР“В«l latine a me tildР“В«",auml:"Shkronja e vogР“В«l latine a me dy pika",aring:"Shkronja e vogР“В« latine a me unazР“В« mbi",aelig:"Shkronja e vogР“В« latine Р“В¦",ccedil:"Shkronja e vogР“В«l latine c me hark poshtР“В«",egrave:"Shkronja e vogР“В« latine e me theks tР“В« rР“В«ndР“В«",eacute:"Shkronja e vogР“В« latine e me theks tР“В« mprehtР“В«",ecirc:"Shkronja e vogР“В«l latine e me theks lakor",euml:"Shkronja e vogР“В«l latine e me dy pika",igrave:"Shkronja e vogР“В« latine i me theks tР“В« rР“В«ndР“В«",
iacute:"Shkronja e vogР“В« latine i me theks tР“В« mprehtР“В«",icirc:"Shkronja e vogР“В«l latine i me theks lakor",iuml:"Shkronja e vogР“В«l latine i me dy pika",eth:"Shkronja e vogР“В« latine eth",ntilde:"Shkronja e vogР“В«l latine n me tildР“В«",ograve:"Shkronja e vogР“В« latine o me theks tР“В« rР“В«ndР“В«",oacute:"Shkronja e vogР“В« latine o me theks tР“В« mprehtР“В«",ocirc:"Shkronja e vogР“В«l latine o me theks lakor",otilde:"Shkronja e vogР“В«l latine o me tildР“В«",ouml:"Shkronja e vogР“В«l latine o me dy pika",divide:"Shenja ndarР“В«se",oslash:"Shkronja e vogР“В«l latine o me vizР“В« nР“В« mes",
ugrave:"Shkronja e vogР“В« latine u me theks tР“В« rР“В«ndР“В«",uacute:"Shkronja e vogР“В« latine u me theks tР“В« mprehtР“В«",ucirc:"Shkronja e vogР“В«l latine u me theks lakor",uuml:"Shkronja e vogР“В«l latine u me dy pika",yacute:"Shkronja e vogР“В« latine y me theks tР“В« mprehtР“В«",thorn:"Shkronja e vogР“В«l latine thorn",yuml:"Shkronja e vogР“В«l latine y me dy pika",OElig:"Shkronja e madhe e bashkuar latine OE",oelig:"Shkronja e vogР“В«l e bashkuar latine oe",372:"Shkronja e madhe latine W me theks lakor",374:"Shkronja e madhe latine Y me theks lakor",
373:"Shkronja e vogР“В«l latine w me theks lakor",375:"Shkronja e vogР“В«l latine y me theks lakor",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"Shenja e Simbolit TregtarР“В«",9658:"Black right-pointing pointer",bull:"Pulla",rarr:"Shigjeta djathtas",rArr:"Shenja tР“В« dyfishta djathtas",hArr:"Shigjeta e dyfishР“В« majtas-djathtas",diams:"Black diamond suit",asymp:"Gati e barabar me"});