РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sv",{euro:"Eurotecken",lsquo:"Enkelt vР“В¤nster citattecken",rsquo:"Enkelt hР“В¶ger citattecken",ldquo:"Dubbelt vР“В¤nster citattecken",rdquo:"Dubbelt hР“В¶ger citattecken",ndash:"Snedstreck",mdash:"LР“Тђngt tankstreck",iexcl:"Inverterad utropstecken",cent:"Centtecken",pound:"Pundtecken",curren:"Valutatecken",yen:"Yentecken",brvbar:"Brutet lodrР“В¤tt streck",sect:"Paragraftecken",uml:"Diaeresis",copy:"UpphovsrР“В¤ttstecken",ordf:"Feminit ordningstalsindikator",laquo:"VР“В¤nsterstР“В¤llt dubbelt vinkelcitationstecken",
not:"Icke-tecken",reg:"Registrerad",macr:"Macron",deg:"Grader",sup2:"UpphР“В¶jt tvР“Тђ",sup3:"UpphР“В¶jt tre",acute:"Akut accent",micro:"Mikrotecken",para:"Alinea",middot:"Centrerad prick",cedil:"Cedilj",sup1:"UpphР“В¶jt en",ordm:"Maskulina ordningsР“В¤ndelsen",raquo:"HР“В¶gerstР“В¤llt dubbelt vinkelcitationstecken",frac14:"BrР“Тђktal - en kvart",frac12:"BrР“Тђktal - en halv",frac34:"BrР“Тђktal - tre fjР“В¤rdedelar",iquest:"Inverterat frР“Тђgetecken",Agrave:"Stort A med grav accent",Aacute:"Stort A med akutaccent",Acirc:"Stort A med circumflex",
Atilde:"Stort A med tilde",Auml:"Stort A med diaresis",Aring:"Stort A med ring ovan",AElig:"Stort Р“вЂ ",Ccedil:"Stort C med cedilj",Egrave:"Stort E med grav accent",Eacute:"Stort E med aktuaccent",Ecirc:"Stort E med circumflex",Euml:"Stort E med diaeresis",Igrave:"Stort I med grav accent",Iacute:"Stort I med akutaccent",Icirc:"Stort I med circumflex",Iuml:"Stort I med diaeresis",ETH:"Stort Eth",Ntilde:"Stort N med tilde",Ograve:"Stort O med grav accent",Oacute:"Stort O med aktuaccent",Ocirc:"Stort O med circumflex",
Otilde:"Stort O med tilde",Ouml:"Stort O med diaeresis",times:"Multiplicera",Oslash:"Stor Р“пїЅ",Ugrave:"Stort U med grav accent",Uacute:"Stort U med akutaccent",Ucirc:"Stort U med circumflex",Uuml:"Stort U med diaeresis",Yacute:"Stort Y med akutaccent",THORN:"Stort Thorn",szlig:"Litet dubbel-s/Eszett",agrave:"Litet a med grav accent",aacute:"Litet a med akutaccent",acirc:"Litet a med circumflex",atilde:"Litet a med tilde",auml:"Litet a med diaeresis",aring:"Litet a med ring ovan",aelig:"Bokstaven Р“В¦",
ccedil:"Litet c med cedilj",egrave:"Litet e med grav accent",eacute:"Litet e med akutaccent",ecirc:"Litet e med circumflex",euml:"Litet e med diaeresis",igrave:"Litet i med grav accent",iacute:"Litet i med akutaccent",icirc:"LItet i med circumflex",iuml:"Litet i med didaeresis",eth:"Litet eth",ntilde:"Litet n med tilde",ograve:"LItet o med grav accent",oacute:"LItet o med akutaccent",ocirc:"Litet o med circumflex",otilde:"LItet o med tilde",ouml:"Litet o med diaeresis",divide:"Division",oslash:"Р“С‘",
ugrave:"Litet u med grav accent",uacute:"Litet u med akutaccent",ucirc:"LItet u med circumflex",uuml:"Litet u med diaeresis",yacute:"Litet y med akutaccent",thorn:"Litet thorn",yuml:"Litet y med diaeresis",OElig:"Stor ligatur av OE",oelig:"Liten ligatur av oe",372:"Stort W med circumflex",374:"Stort Y med circumflex",373:"Litet w med circumflex",375:"Litet y med circumflex",sbquo:"Enkelt lР“Тђgt 9-citationstecken",8219:"Enkelt hР“В¶gt bakvР“В¤nt 9-citationstecken",bdquo:"Dubbelt lР“Тђgt 9-citationstecken",hellip:"Horisontellt uteslutningstecken",
trade:"VarumР“В¤rke",9658:"Svart hР“В¶gervР“В¤nd pekare",bull:"Listpunkt",rarr:"HР“В¶gerpil",rArr:"Dubbel hР“В¶gerpil",hArr:"Dubbel vР“В¤nsterpil",diams:"Svart ruter",asymp:"UngefР“В¤r lika med"});