РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","tr",{euro:"Euro iР•Сџareti",lsquo:"Sol tek tР”В±rnak iР•Сџareti",rsquo:"SaР”Сџ tek tР”В±rnak iР•Сџareti",ldquo:"Sol Р“В§ift tР”В±rnak iР•Сџareti",rdquo:"SaР”Сџ Р“В§ift tР”В±rnak iР•Сџareti",ndash:"En tire",mdash:"Em tire",iexcl:"Ters Р“С�nlem iР•Сџareti",cent:"Cent iР•Сџareti",pound:"Pound iР•Сџareti",curren:"Para birimi iР•Сџareti",yen:"Yen iР•Сџareti",brvbar:"KР”В±rР”В±k bar",sect:"BР“В¶lР“С�m iР•Сџareti",uml:"Р”В°ki sesli harfin ayrР”В±lmasР”В±",copy:"Telif hakkР”В± iР•Сџareti",ordf:"DiР•Сџil sР”В±ralР”В± gР“В¶sterge",laquo:"Sol-iР•Сџaret Р“В§ift aР“В§Р”В± tР”В±rnak iР•Сџareti",
not:"Not iР•Сџareti",reg:"KayР”В±tlР”В± iР•Сџareti",macr:"Makron",deg:"Derece iР•Сџareti",sup2:"Р”В°kili Р“С�stsimge",sup3:"Р“СљР“В§lР“С� Р“С�stsimge",acute:"Aksan iР•Сџareti",micro:"Mikro iР•Сџareti",para:"Pilcrow iР•Сџareti",middot:"Orta nokta",cedil:"Kedilla",sup1:"Р“Сљstsimge",ordm:"Eril sР”В±ralР”В± gР“В¶sterge",raquo:"SaР”Сџ iР•Сџaret Р“В§ift aР“В§Р”В± tР”В±rnak iР•Сџareti",frac14:"BayaР”СџР”В± kesrin dР“В¶rtte biri",frac12:"BayaР”СџР”В± kesrin bir yarР”В±m",frac34:"BayaР”СџР”В± kesrin dР“В¶rtte Р“С�Р“В§",iquest:"Ters soru iР•Сџareti",Agrave:"AksanlР”В± latin harfi",Aacute:"AР•СџР”В±rР”В± aksanР”В±yla Latin harfi",
Acirc:"Р“вЂЎarpР”В±k Latin harfi",Atilde:"Tilde latin harfi",Auml:"Sesli harf ayrР”В±lР”В±mlР”В±Р”В± latin harfi",Aring:"HalkalР”В± latin bР“С�yР“С�k A harfi",AElig:"Latin bР“С�yР“С�k Р“вЂ  harfi",Ccedil:"Latin bР“С�yР“С�k C harfi ile kedilla",Egrave:"AksanlР”В± latin bР“С�yР“С�k E harfi",Eacute:"AР•СџР”В±rР”В± vurgulu latin bР“С�yР“С�k E harfi",Ecirc:"Р“вЂЎarpР”В±k latin bР“С�yР“С�k E harfi",Euml:"Sesli harf ayrР”В±lР”В±mlР”В±Р”В± latin bР“С�yР“С�k E harfi",Igrave:"AksanlР”В± latin bР“С�yР“С�k I harfi",Iacute:"AР•СџР”В±rР”В± aksanlР”В± latin bР“С�yР“С�k I harfi",Icirc:"Р“вЂЎarpР”В±k latin bР“С�yР“С�k I harfi",Iuml:"Sesli harf ayrР”В±lР”В±mlР”В±Р”В± latin bР“С�yР“С�k I harfi",
ETH:"Latin bР“С�yР“С�k Eth harfi",Ntilde:"Tildeli latin bР“С�yР“С�k N harfi",Ograve:"AksanlР”В± latin bР“С�yР“С�k O harfi",Oacute:"AР•СџР”В±rР”В± aksanlР”В± latin bР“С�yР“С�k O harfi",Ocirc:"Р“вЂЎarpР”В±k latin bР“С�yР“С�k O harfi",Otilde:"Tildeli latin bР“С�yР“С�k O harfi",Ouml:"Sesli harf ayrР”В±lР”В±mlР”В± latin bР“С�yР“С�k O harfi",times:"Р“вЂЎarpma iР•Сџareti",Oslash:"Vurgulu latin bР“С�yР“С�k O harfi",Ugrave:"AksanlР”В± latin bР“С�yР“С�k U harfi",Uacute:"AР•СџР”В±rР”В± aksanlР”В± latin bР“С�yР“С�k U harfi",Ucirc:"Р“вЂЎarpР”В±k latin bР“С�yР“С�k U harfi",Uuml:"Sesli harf ayrР”В±lР”В±mlР”В± latin bР“С�yР“С�k U harfi",Yacute:"AР•СџР”В±rР”В± aksanlР”В± latin bР“С�yР“С�k Y harfi",
THORN:"Latin bР“С�yР“С�k Thorn harfi",szlig:"Latin kР“С�Р“В§Р“С�k keskin s harfi",agrave:"AksanlР”В± latin kР“С�Р“В§Р“С�k a harfi",aacute:"AР•СџР”В±rР”В± aksanlР”В± latin kР“С�Р“В§Р“С�k a harfi",acirc:"Р“вЂЎarpР”В±k latin kР“С�Р“В§Р“С�k a harfi",atilde:"Tildeli latin kР“С�Р“В§Р“С�k a harfi",auml:"Sesli harf ayrР”В±lР”В±mlР”В± latin kР“С�Р“В§Р“С�k a harfi",aring:"HalkalР”В± latin kР“С�Р“В§Р“С�k a harfi",aelig:"Latin bР“С�yР“С�k Р“В¦ harfi",ccedil:"KedillalР”В± latin kР“С�Р“В§Р“С�k c harfi",egrave:"AksanlР”В± latin kР“С�Р“В§Р“С�k e harfi",eacute:"AР•СџР”В±rР”В± aksanlР”В± latin kР“С�Р“В§Р“С�k e harfi",ecirc:"Р“вЂЎarpР”В±k latin kР“С�Р“В§Р“С�k e harfi",euml:"Sesli harf ayrР”В±lР”В±mlР”В± latin kР“С�Р“В§Р“С�k e harfi",
igrave:"AksanlР”В± latin kР“С�Р“В§Р“С�k i harfi",iacute:"AР•СџР”В±rР”В± aksanlР”В± latin kР“С�Р“В§Р“С�k i harfi",icirc:"Р“вЂЎarpР”В±k latin kР“С�Р“В§Р“С�k i harfi",iuml:"Sesli harf ayrР”В±lР”В±mlР”В± latin kР“С�Р“В§Р“С�k i harfi",eth:"Latin kР“С�Р“В§Р“С�k eth harfi",ntilde:"Tildeli latin kР“С�Р“В§Р“С�k n harfi",ograve:"AksanlР”В± latin kР“С�Р“В§Р“С�k o harfi",oacute:"AР•СџР”В±rР”В± aksanlР”В± latin kР“С�Р“В§Р“С�k o harfi",ocirc:"Р“вЂЎarpР”В±k latin kР“С�Р“В§Р“С�k o harfi",otilde:"Tildeli latin kР“С�Р“В§Р“С�k o harfi",ouml:"Sesli harf ayrР”В±lР”В±mlР”В± latin kР“С�Р“В§Р“С�k o harfi",divide:"BР“В¶lme iР•Сџareti",oslash:"Vurgulu latin kР“С�Р“В§Р“С�k o harfi",ugrave:"AksanlР”В± latin kР“С�Р“В§Р“С�k u harfi",
uacute:"AР•СџР”В±rР”В± aksanlР”В± latin kР“С�Р“В§Р“С�k u harfi",ucirc:"Р“вЂЎarpР”В±k latin kР“С�Р“В§Р“С�k u harfi",uuml:"Sesli harf ayrР”В±lР”В±mlР”В± latin kР“С�Р“В§Р“С�k u harfi",yacute:"AР•СџР”В±rР”В± aksanlР”В± latin kР“С�Р“В§Р“С�k y harfi",thorn:"Latin kР“С�Р“В§Р“С�k thorn harfi",yuml:"Sesli harf ayrР”В±lР”В±mlР”В± latin kР“С�Р“В§Р“С�k y harfi",OElig:"Latin bР“С�yР“С�k baР”СџlР”В± OE harfi",oelig:"Latin kР“С�Р“В§Р“С�k baР”СџlР”В± oe harfi",372:"Р“вЂЎarpР”В±k latin bР“С�yР“С�k W harfi",374:"Р“вЂЎarpР”В±k latin bР“С�yР“С�k Y harfi",373:"Р“вЂЎarpР”В±k latin kР“С�Р“В§Р“С�k w harfi",375:"Р“вЂЎarpР”В±k latin kР“С�Р“В§Р“С�k y harfi",sbquo:"Tek dР“С�Р•СџР“С�k-9 tР”В±rnak iР•Сџareti",8219:"Tek yР“С�ksek-ters-9 tР”В±rnak iР•Сџareti",
bdquo:"Р“вЂЎift dР“С�Р•СџР“С�k-9 tР”В±rnak iР•Сџareti",hellip:"Yatay elips",trade:"Marka tescili iР•Сџareti",9658:"Siyah saР”Сџ iР•Сџaret iР•СџaretР“В§isi",bull:"Koyu nokta",rarr:"SaР”Сџa doР”Сџru ok",rArr:"SaР”Сџa doР”Сџru Р“В§ift ok",hArr:"Sol, saР”Сџ Р“В§ift ok",diams:"Siyah elmas takР”В±mР”В±",asymp:"Hemen hemen eР•Сџit"});