РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","ug",{euro:"Р©Р‰РЁВ§Р«вЂ№РЁВ±Р©в‚¬ РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",lsquo:"Р©Р‰РЁВ§Р©вЂћРЁВ§РЄВ­ Р©С•Р«вЂўРЁТ‘ РЁС–Р©в‚¬Р©вЂћ",rsquo:"Р©Р‰РЁВ§Р©вЂћРЁВ§РЄВ­ Р©С•Р«вЂўРЁТ‘ РЁВ¦Р©в‚¬РЄВ­",ldquo:"Р©вЂљР©в‚¬РЁТ‘ Р©С•Р«вЂўРЁТ‘ РЁС–Р©в‚¬Р©вЂћ",rdquo:"Р©вЂљР©в‚¬РЁТ‘ Р©С•Р«вЂўРЁТ‘ РЁВ¦Р©в‚¬РЄВ­",ndash:"РЁС–Р©вЂ°РЁР†Р©вЂ°Р©вЂљРЄвЂ Р«вЂў",mdash:"РЁС–Р©вЂ°РЁР†Р©вЂ°Р©вЂљ",iexcl:"РЁВ¦Р«в‚¬Р©вЂ РЁР‡Р«вЂўРЁТ‘",cent:"РЁР„Р©вЂ°Р©Р‰Р©вЂ°Р©вЂ  РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",pound:"Р©РѓР©в‚¬Р©вЂ РЁР‡ РЁС–РЁР„Р«С’РЁВ±Р©вЂћР©вЂ°РЄВ­",curren:"Р©С•Р«вЂЎР©вЂћ РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",yen:"Р©Р‰РЁВ§Р©С•Р©в‚¬Р©вЂ Р©вЂ°Р©Р‰Р«вЂў Р©Р‰Р©вЂ°Р©вЂ Р©вЂ°",brvbar:"РЁВ¦Р«в‚¬РЁР†Р«в‚¬Р©С“ РЁРЃРЁВ§Р©вЂћРЁР‡РЁВ§Р©вЂљ",sect:"Р©С•РЁВ§РЁВ±РЁВ§РЄР‡РЁВ±РЁВ§Р©Рѓ РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",uml:"РЁР„РЁВ§Р«вЂ№Р«вЂЎРЁТ‘ РЁВ¦РЁВ§Р©Р‰РЁВ±Р©вЂ°РЁТ‘ РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",copy:"Р©вЂ Р«вЂўРЁТ‘РЁВ± РЄС•Р©в‚¬Р©вЂљР«вЂЎР©вЂљР©вЂ° РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",ordf:"Feminine ordinal indicator",laquo:"Р©вЂљР©в‚¬РЁТ‘ РЁР„Р©вЂ°РЁВ±Р©вЂ РЁВ§Р©вЂљ РЁС–Р©в‚¬Р©вЂћ",not:"РЁС”Р«вЂўР©Р‰РЁВ±Р©вЂ° РЁРЃР«вЂўР©вЂћРЄР‡Р«вЂў",reg:"РЁВ®Р«вЂўРЁР„Р©вЂћР«вЂўРЁР„Р©С“Р«вЂўР©вЂ  РЁР„РЁВ§Р«вЂ№РЁВ§РЁВ± Р©вЂ¦РЁВ§РЁВ±Р©С“Р©вЂ°РЁС–Р©вЂ°",macr:"РЁС–Р©в‚¬РЁР†Р«вЂЎРЁТ‘ РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",
deg:"РЄР‡Р©вЂ°РЁВ±РЁВ§РЁР‡Р«вЂЎРЁС– РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",sup2:"Р©Р‰Р«вЂЎР©вЂљР©вЂ°РЁВ±Р©вЂ° РЁВ¦Р©вЂ°Р©вЂ РЁР‡Р«С’Р©С“Р©вЂ°РЁС– 2",sup3:"Р©Р‰Р«вЂЎР©вЂљР©вЂ°РЁВ±Р©вЂ° РЁВ¦Р©вЂ°Р©вЂ РЁР‡Р«С’Р©С“Р©вЂ°РЁС– 3",acute:"РЁВ¦Р«вЂЎРЁВ±РЁС”Р«вЂЎ РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",micro:"Micro sign",para:"РЁВ¦РЁВ§РЁРЃРЁР†РЁВ§РЁС– РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",middot:"РЁВ¦Р©в‚¬РЁР„РЁР„Р«вЂЎРЁВ±РЁВ§ РЄвЂ Р«С’Р©С“Р©вЂ°РЁР„",cedil:"РЁВ¦РЁВ§РЁС–РЁР„Р©вЂ°РЁС”РЁВ§ Р©вЂљР©в‚¬РЁТ‘Р«вЂЎР©вЂћР©вЂ°РЁР‡Р©вЂ°РЁС”РЁВ§Р©вЂ  РЁРЃР«вЂўР©вЂћРЄР‡Р«вЂў",sup1:"Р©Р‰Р«вЂЎР©вЂљР©вЂ°РЁВ±Р©вЂ° РЁВ¦Р©вЂ°Р©вЂ РЁР‡Р«С’Р©С“Р©вЂ°РЁС– 1",ordm:"Masculine ordinal indicator",raquo:"Р©вЂљР©в‚¬РЁТ‘ РЁР„Р©вЂ°РЁВ±Р©вЂ РЁВ§Р©вЂљ РЁВ¦Р©в‚¬РЄВ­",frac14:"РЁВ¦РЁВ§РЁР‡РЁР‡Р©вЂ°Р©Р‰ Р©С“Р«вЂўРЁС–Р©вЂ°РЁВ± РЁР„Р«вЂ РЁР„РЁР„Р©вЂ°Р©вЂ  РЁРЃР©вЂ°РЁВ±",frac12:"РЁВ¦РЁВ§РЁР‡РЁР‡Р©вЂ°Р©Р‰ Р©С“Р«вЂўРЁС–Р©вЂ°РЁВ± РЁВ¦Р©вЂ°Р©С“Р©С“Р©вЂ°РЁР‡Р©вЂ°Р©вЂ  РЁРЃР©вЂ°РЁВ±",frac34:"РЁВ¦РЁВ§РЁР‡РЁР‡Р©вЂ°Р©Р‰ Р©С“Р«вЂўРЁС–Р©вЂ°РЁВ± РЁВ¦Р«в‚¬РЄвЂ РЁР„Р©вЂ°Р©вЂ  РЁР„Р«вЂ РЁВ±РЁР„",iquest:"Inverted question mark",Agrave:"Latin capital letter A with grave accent",Aacute:"Latin capital letter A with acute accent",
Acirc:"Latin capital letter A with circumflex",Atilde:"Latin capital letter A with tilde",Auml:"Latin capital letter A with diaeresis",Aring:"Latin capital letter A with ring above",AElig:"Latin Capital letter Р“вЂ ",Ccedil:"Latin capital letter C with cedilla",Egrave:"Latin capital letter E with grave accent",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"Latin capital letter I with grave accent",Iacute:"Latin capital letter I with acute accent",
Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",ETH:"Latin capital letter Eth",Ntilde:"Latin capital letter N with tilde",Ograve:"Р©вЂљР©в‚¬РЁТ‘ Р©С•Р«вЂўРЁТ‘ РЁВ¦Р©в‚¬РЄВ­",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",times:"Multiplication sign",Oslash:"Latin capital letter O with stroke",Ugrave:"Latin capital letter U with grave accent",Uacute:"Latin capital letter U with acute accent",
Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",Yacute:"Latin capital letter Y with acute accent",THORN:"Latin capital letter Thorn",szlig:"Latin small letter sharp s",agrave:"Latin small letter a with grave accent",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",auml:"Latin small letter a with diaeresis",aring:"Latin small letter a with ring above",aelig:"Latin small letter Р“В¦",
ccedil:"Latin small letter c with cedilla",egrave:"Latin small letter e with grave accent",eacute:"Latin small letter e with acute accent",ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"Latin small letter i with grave accent",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"Latin small letter eth",ntilde:"РЁР„Р©вЂ°Р©С“ Р©вЂ¦Р©в‚¬Р©вЂћР©вЂћРЁВ§Р©вЂљ РЁС–Р©в‚¬РЁВ¦РЁВ§Р©вЂћ РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",ograve:"Latin small letter o with grave accent",
oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",divide:"РЁРЃР«вЂ Р©вЂћР«в‚¬РЁТ‘ РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",oslash:"Latin small letter o with stroke",ugrave:"Latin small letter u with grave accent",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",thorn:"Latin small letter thorn",
yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"РЁВ®Р«вЂўРЁР„Р©вЂћР«вЂўРЁР„Р©С“Р«вЂўР©вЂ  РЁР„РЁВ§Р«вЂ№РЁВ§РЁВ± Р©вЂ¦РЁВ§РЁВ±Р©С“Р©вЂ°РЁС–Р©вЂ° РЁРЃР«вЂўР©вЂћРЄР‡Р©вЂ°РЁС–Р©вЂ°",9658:"Black right-pointing pointer",
bull:"Bullet",rarr:"РЁВ¦Р©в‚¬РЄВ­ Р©Р‰РЁВ§ РЁВ¦Р©в‚¬Р©вЂљ",rArr:"РЁВ¦Р©в‚¬РЄВ­ Р©вЂљР©в‚¬РЁТ‘ РЁС–Р©вЂ°РЁР†Р©вЂ°Р©вЂљ Р©Р‰РЁВ§ РЁВ¦Р©в‚¬Р©вЂљ",hArr:"РЁВ¦Р©в‚¬РЄВ­ РЁС–Р©в‚¬Р©вЂћ Р©вЂљР©в‚¬РЁТ‘ РЁС–Р©вЂ°РЁР†Р©вЂ°Р©вЂљ Р©Р‰РЁВ§ РЁВ¦Р©в‚¬Р©вЂљ",diams:"РЁВ¦Р«вЂЎР©Р‰Р«вЂЎР©вЂћ РЁС”Р©вЂ°РЄвЂ ",asymp:"РЁР„Р«вЂўРЁВ®Р©вЂ¦Р©вЂ°Р©вЂ Р«вЂўР©вЂ  РЁР„Р«вЂўРЄВ­"});