РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro pР•в„ўР“В­stupnost",contents:"Obsah nР“РЋpovР”вЂєdy. Pro uzavР•в„ўenР“В­ tohoto dialogu stisknР”вЂєte klР“РЋvesu ESC.",legend:[{name:"ObecnР“В©",items:[{name:"Panel nР“РЋstrojР•Р‡ editoru",legend:"StisknР”вЂєte${toolbarFocus} k prochР“РЋzenР“В­ panelu nР“РЋstrojР•Р‡. PР•в„ўejdР”вЂєte na dalР•РЋР“В­ a pР•в„ўedchozР“В­ skupiny pomocР“В­ TAB a SHIFT+TAB. PР•в„ўechod na dalР•РЋР“В­ a pР•в„ўedchozР“В­ tlaР”РЊР“В­tko panelu nР“РЋstrojР•Р‡ je pomocР“В­ Р•В IPKA VPRAVO nebo Р•В IPKA VLEVO. StisknutР“В­m mezernР“В­ku nebo klР“РЋvesy ENTER tlaР”РЊР“В­tko aktivujete."},{name:"DialogovР“В© okno editoru",
legend:"UvnitР•в„ў dialogovР“В©ho okna stisknР”вЂєte TAB pro pР•в„ўesunutР“В­ na dalР•РЋР“В­ prvek okna, stisknР”вЂєte SHIFT+TAB pro pР•в„ўesun na pР•в„ўedchozР“В­ prvek okna, stisknР”вЂєte ENTER pro odeslР“РЋnР“В­ dialogu, stisknР”вЂєte ESC pro jeho zruР•РЋenР“В­. Pro dialogovР“РЋ okna, kterР“РЋ majР“В­ mnoho karet stisknР”вЂєte ALT+F10 pro zamР”вЂєР•в„ўenР“В­ seznamu karet, nebo TAB, pro posun podle poР•в„ўadР“В­ karet.PР•в„ўi zamР”вЂєР•в„ўenР“В­ seznamu karet se mР•Р‡Р•С•ete jimi posouvat pomocР“В­ Р•В IPKY VPRAVO a VLEVO."},{name:"KontextovР“В© menu editoru",legend:"StisknР”вЂєte ${contextMenu} nebo klР“РЋvesu APPLICATION k otevР•в„ўenР“В­ kontextovР“В©ho menu. Pak se pР•в„ўesuР•в‚¬te na dalР•РЋР“В­ moР•С•nost menu pomocР“В­ TAB nebo Р•В IPKY DOLР•В®. PР•в„ўesuР•в‚¬te se na pР•в„ўedchozР“В­ moР•С•nost pomocР“В­  SHIFT+TAB nebo Р•В IPKY NAHORU. StisknР”вЂєte MEZERNР“РЊK nebo ENTER pro zvolenР“В­ moР•С•nosti menu. Podmenu souР”РЊasnР“В© moР•С•nosti otevР•в„ўete pomocР“В­ MEZERNР“РЊKU nebo ENTER Р”РЊi Р•В IPKY DOLEVA. KontextovР“В© menu uzavР•в„ўete stiskem ESC."},
{name:"RР“РЋmeР”РЊek seznamu editoru",legend:"UvnitР•в„ў rР“РЋmeР”РЊku seznamu se pР•в„ўesunete na dalР•РЋР“В­ poloР•С•ku menu pomocР“В­ TAB nebo Р•В IPKA DOLР•В®. Na pР•в„ўedchozР“В­ poloР•С•ku se pР•в„ўesunete SHIFT+TAB nebo Р•В IPKA NAHORU. StisknР”вЂєte MEZERNР“РЊK nebo ENTER pro zvolenР“В­ moР•С•nosti seznamu. StisknР”вЂєte ESC pro uzavР•в„ўenР“В­ seznamu."},{name:"LiР•РЋta cesty prvku v editoru",legend:"StisknР”вЂєte ${elementsPathFocus} pro prochР“РЋzenР“В­ liР•РЋty cesty prvku. Na dalР•РЋР“В­ tlaР”РЊР“В­tko prvku se pР•в„ўesunete pomocР“В­ TAB nebo Р•В IPKA VPRAVO. Na pР•в„ўedchozР“В­ tlaР”РЊР“В­tko se pР•в„ўesunete pomocР“В­ SHIFT+TAB nebo Р•В IPKA VLEVO. StisknР”вЂєte MEZERNР“РЊK nebo ENTER pro vybrР“РЋnР“В­ prvku v editoru."}]},
{name:"PР•в„ўР“В­kazy",items:[{name:" PР•в„ўР“В­kaz ZpР”вЂєt",legend:"StisknР”вЂєte ${undo}"},{name:" PР•в„ўР“В­kaz Znovu",legend:"StisknР”вЂєte ${redo}"},{name:" PР•в„ўР“В­kaz TuР”РЊnР“В©",legend:"StisknР”вЂєte ${bold}"},{name:" PР•в„ўР“В­kaz KurzР“В­va",legend:"StisknР”вЂєte ${italic}"},{name:" PР•в„ўР“В­kaz PodtrР•С•enР“В­",legend:"StisknР”вЂєte ${underline}"},{name:" PР•в„ўР“В­kaz Odkaz",legend:"StisknР”вЂєte ${link}"},{name:" PР•в„ўР“В­kaz SkrР“Р…t panel nР“РЋstrojР•Р‡",legend:"StisknР”вЂєte ${toolbarCollapse}"},{name:"PР•в„ўР“В­kaz pro pР•в„ўР“В­stup k pР•в„ўedchozР“В­mu prostoru zamР”вЂєР•в„ўenР“В­",legend:"StisknР”вЂєte ${accessPreviousSpace} pro pР•в„ўР“В­stup k nejbliР•С•Р•РЋР“В­mu nedosaР•С•itelnР“В©mu prostoru zamР”вЂєР•в„ўenР“В­ pР•в„ўed stР•в„ўР“В­Р•РЋkou, napР•в„ўР“В­klad: dva pР•в„ўilehlР“В© prvky HR. Pro dosaР•С•enР“В­ vzdР“РЋlenР“Р…ch prostorР•Р‡ zamР”вЂєР•в„ўenР“В­ tuto kombinaci klР“РЋves opakujte."},
{name:"PР•в„ўР“В­kaz pro pР•в„ўР“В­stup k dalР•РЋР“В­mu prostoru zamР”вЂєР•в„ўenР“В­",legend:"StisknР”вЂєte ${accessNextSpace} pro pР•в„ўР“В­stup k nejbliР•С•Р•РЋР“В­mu nedosaР•С•itelnР“В©mu prostoru zamР”вЂєР•в„ўenР“В­ po stР•в„ўР“В­Р•РЋce, napР•в„ўР“В­klad: dva pР•в„ўilehlР“В© prvky HR. Pro dosaР•С•enР“В­ vzdР“РЋlenР“Р…ch prostorР•Р‡ zamР”вЂєР•в„ўenР“В­ tuto kombinaci klР“РЋves opakujte."},{name:" NР“РЋpovР”вЂєda pР•в„ўР“В­stupnosti",legend:"StisknР”вЂєte ${a11yHelp}"}]}],tab:"TabulР“РЋtor",pause:"Pauza",capslock:"Caps lock",escape:"Escape",pageUp:"StrР“РЋnka nahoru",pageDown:"StrР“РЋnka dolР•Р‡",leftArrow:"Р•В ipka vlevo",upArrow:"Р•В ipka nahoru",
rightArrow:"Р•В ipka vpravo",downArrow:"Р•В ipka dolР•Р‡",insert:"VloР•С•it",leftWindowKey:"LevР“РЋ klР“РЋvesa Windows",rightWindowKey:"PravР“РЋ klР“РЋvesa Windows",selectKey:"Vyberte klР“РЋvesu",numpad0:"NumerickР“РЋ klР“РЋvesa 0",numpad1:"NumerickР“РЋ klР“РЋvesa 1",numpad2:"NumerickР“РЋ klР“РЋvesa 2",numpad3:"NumerickР“РЋ klР“РЋvesa 3",numpad4:"NumerickР“РЋ klР“РЋvesa 4",numpad5:"NumerickР“РЋ klР“РЋvesa 5",numpad6:"NumerickР“РЋ klР“РЋvesa 6",numpad7:"NumerickР“РЋ klР“РЋvesa 7",numpad8:"NumerickР“РЋ klР“РЋvesa 8",numpad9:"NumerickР“РЋ klР“РЋvesa 9",multiply:"NumerickР“РЋ klР“РЋvesa nР“РЋsobenР“В­",
add:"PР•в„ўidat",subtract:"NumerickР“РЋ klР“РЋvesa odeР”РЊР“В­tР“РЋnР“В­",decimalPoint:"DesetinnР“РЋ teР”РЊka",divide:"NumerickР“РЋ klР“РЋvesa dР”вЂєlenР“В­",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num lock",scrollLock:"Scroll lock",semiColon:"StР•в„ўednР“В­k",equalSign:"RovnР“В­tko",comma:"Р”РЉР“РЋrka",dash:"PomlР”РЊka",period:"TeР”РЊka",forwardSlash:"LomР“В­tko",graveAccent:"PР•в„ўР“В­zvuk",openBracket:"OtevР•в„ўenР“РЋ hranatР“РЋ zР“РЋvorka",backSlash:"ObrР“РЋcenР“В© lomР“В­tko",closeBracket:"UzavР•в„ўenР“РЋ hranatР“РЋ zР“РЋvorka",
singleQuote:"JednoduchР“РЋ uvozovka"});