РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","eo",{title:"Uzindikoj pri atingeblo",contents:"Helpilenhavo. Por fermi tiun dialogon, premu la ESKAPAN klavon.",legend:[{name:"Р”СљeneralaР”Вµoj",items:[{name:"Ilbreto de la redaktilo",legend:"Premu ${toolbarFocus} por atingi la ilbreton. MoviР”Сњu al la sekva aР•В­ antaР•В­a grupoj de la ilbreto per la klavoj TABA kaj MAJUSKLIGA+TABA. MoviР”Сњu al la sekva aР•В­ antaР•В­a butonoj de la ilbreto per la klavoj SAGO DEKSTREN kaj SAGO MALDEKSTREN. Premu la SPACETklavon aР•В­ la ENENklavon por aktivigi la ilbretbutonon."},
{name:"Redaktildialogo",legend:"En dialogo, premu la TABAN klavon por navigi al la sekva dialogelemento, premu la MAJUSKLIGAN+TABAN klavon por iri al la antaР•В­a dialogelemento, premu la ENEN klavon por sendi la dialogon, premu la ESKAPAN klavon por nuligi la dialogon. Kiam dialogo havas multajn langetojn, eblas atingi la langetliston aР•В­ per ALT+F10 aР•В­ per la TABA klavo kiel parton de la dialoga taba ordo. En langetlisto, moviР”Сњu al la sekva kaj antaР•В­a langeto per la klavoj SAGO DEKSTREN KAJ MALDEKSTREN respektive."},
{name:"Kunteksta menuo de la redaktilo",legend:"Premu ${contextMenu} aР•В­ entajpu la KLAVKOMBINAР”Т‘ON por malfermi la kuntekstan menuon. Poste moviР”Сњu al la sekva opcio de la menuo per la klavoj TABA aР•В­ SAGO SUBEN. MoviР”Сњu al la antaР•В­a opcio per la klavoj MAJUSKLGA + TABA aР•В­ SAGO SUPREN. Premu la SPACETklavon aР•В­ ENENklavon por selekti la menuopcion. Malfermu la submenuon de la kuranta opcio per la SPACETklavo aР•В­ la ENENklavo aР•В­ la SAGO DEKSTREN. Revenu al la elemento de la patra menuo per la klavoj ESKAPA aР•В­ SAGO MALDEKSTREN. Fermu la kuntekstan menuon per la ESKAPA klavo."},
{name:"Fallisto de la redaktilo",legend:"En fallisto, moviР”Сњu al la sekva listelemento per la klavoj TABA aР•В­ SAGO SUBEN. MoviР”Сњu al la antaР•В­a listelemento per la klavoj MAJUSKLIGA+TABA aР•В­ SAGO SUPREN. Premu la SPACETklavon aР•В­ ENENklavon por selekti la opcion en la listo. Premu la ESKAPAN klavon por fermi la falmenuon."},{name:"Breto indikanta la vojon al la redaktilelementoj",legend:"Premu ${elementsPathFocus} por navigi al la breto indikanta la vojon al la redaktilelementoj. MoviР”Сњu al la butono de la sekva elemento per la klavoj TABA aР•В­ SAGO DEKSTREN. MoviР”Сњu al la butono de la antaР•В­a elemento per la klavoj MAJUSKLIGA+TABA aР•В­ SAGO MALDEKSTREN. Premu la SPACETklavon aР•В­ ENENklavon por selekti la elementon en la redaktilo."}]},
{name:"Komandoj",items:[{name:"Komando malfari",legend:"Premu ${undo}"},{name:"Komando refari",legend:"Premu ${redo}"},{name:"Komando grasa",legend:"Premu ${bold}"},{name:"Komando kursiva",legend:"Premu ${italic}"},{name:"Komando substreki",legend:"Premu ${underline}"},{name:"Komando ligilo",legend:"Premu ${link}"},{name:"Komando faldi la ilbreton",legend:"Premu ${toolbarCollapse}"},{name:"Komando por atingi la antaР•В­an fokusan spacon",legend:"Press ${accessPreviousSpace} por atingi la plej proksiman neatingeblan fokusan spacon antaР•В­ la kursoro, ekzemple : du kuntuР•СњiР”Сњajn HR elementojn. Ripetu la klavkombinaР”Вµon por atingi malproksimajn fokusajn spacojn."},
{name:"Komando por atingi la sekvan fokusan spacon",legend:"Press ${accessNextSpace} por atingi la plej proksiman neatingeblan fokusan spacon post la kursoro, ekzemple : du kuntuР•СњiР”Сњajn HR elementojn. Ripetu la klavkombinajР“Т‘n por atingi malproksimajn fokusajn spacojn"},{name:"Helpilo pri atingeblo",legend:"Premu ${a11yHelp}"}]}],tab:"Tabo",pause:"PaР•В­zo",capslock:"Majuskla baskulo",escape:"Eskapa klavo",pageUp:"AntaР•В­a PaР”Сњo",pageDown:"Sekva PaР”Сњo",leftArrow:"Sago Maldekstren",upArrow:"Sago Supren",rightArrow:"Sago Dekstren",
downArrow:"Sago Suben",insert:"Enmeti",leftWindowKey:"Maldekstra Windows-klavo",rightWindowKey:"Dekstra Windows-klavo",selectKey:"Selektklavo",numpad0:"Nombra Klavaro 0",numpad1:"Nombra Klavaro 1",numpad2:"Nombra Klavaro 2",numpad3:"Nombra Klavaro 3",numpad4:"Nombra Klavaro 4",numpad5:"Nombra Klavaro 5",numpad6:"Nombra Klavaro 6",numpad7:"Nombra Klavaro 7",numpad8:"Nombra Klavaro 8",numpad9:"Nombra Klavaro 9",multiply:"Obligi",add:"Almeti",subtract:"Subtrahi",decimalPoint:"Dekuma Punkto",divide:"Dividi",
f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Nombra Baskulo",scrollLock:"Ruluma Baskulo",semiColon:"Punktokomo",equalSign:"Egalsigno",comma:"Komo",dash:"Haltostreko",period:"Punkto",forwardSlash:"Oblikvo",graveAccent:"Malakuto",openBracket:"Malferma Krampo",backSlash:"Retroklino",closeBracket:"Ferma Krampo",singleQuote:"Citilo"});