РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","es",{title:"Instrucciones de accesibilidad",contents:"Ayuda. Para cerrar presione ESC.",legend:[{name:"General",items:[{name:"Barra de herramientas del editor",legend:'Presiona ${toolbarFocus} para navegar por la barra de herramientas. Para moverse por los distintos grupos de herramientas usa las teclas TAB y MAY+TAB. Para moverse por las distintas herramientas usa FLECHA DERECHA o FECHA IZQUIERDA. Presiona "espacio" o "intro" para activar la herramienta.'},{name:"Editor de diР“РЋlogo",
legend:"Dentro del diР“РЋlogo, presione TAB para navegar a los siguientes elementos de diР“РЋlogo, presione SHIFT+TAB para moverse a los anteriores elementos de diР“РЋlogo, presione ENTER para enviar el diР“РЋlogo, presiona ESC para cancelar el diР“РЋlogo. Cuando el diР“РЋlogo tiene multiples pestaР“В±as, la lista de pestaР“В±as puede ser abarcada con ALT + F10 or con TAB como parte del orden de pestaР“В±as del diР“РЋlogo. ECon la pestaР“В±a enfocada, puede moverse a la siguiente o anterior pestaР“В±a con las FLECHAS IZQUIRDA y DERECHA respectivamente."},
{name:"Editor del menР“С” contextual",legend:"Presiona ${contextMenu} o TECLA MENР“С™ para abrir el menР“С” contextual. Entonces muР“В©vete a la siguiente opciР“С–n del menР“С” con TAB o FLECHA ABAJO. MuР“В©vete a la opciР“С–n previa con SHIFT + TAB o FLECHA ARRIBA. Presiona ESPACIO o ENTER para seleccionar la opciР“С–n del menР“С”. Abre el submenР“С” de la opciР“С–n actual con ESPACIO o ENTER o FLECHA DERECHA. Regresa al elemento padre del menР“С” con ESC o FLECHA IZQUIERDA. Cierra el menР“С” contextual con ESC."},{name:"Lista del Editor",
legend:"Dentro de una lista, te mueves al siguiente elemento de la lista con TAB o FLECHA ABAJO. Te mueves al elemento previo de la lista con SHIFT+TAB o FLECHA ARRIBA. Presiona ESPACIO o ENTER para elegir la opciР“С–n de la lista. Presiona ESC para cerrar la lista."},{name:"Barra de Ruta del Elemento en el Editor",legend:"Presiona ${elementsPathFocus} para navegar a los elementos de la barra de ruta. Te mueves al siguiente elemento botР“С–n con TAB o FLECHA DERECHA. Te mueves al botР“С–n previo con SHIFT+TAB o FLECHA IZQUIERDA. Presiona ESPACIO o ENTER para seleccionar el elemento en el editor."}]},
{name:"Comandos",items:[{name:"Comando deshacer",legend:"Presiona ${undo}"},{name:"Comando rehacer",legend:"Presiona ${redo}"},{name:"Comando negrita",legend:"Presiona ${bold}"},{name:"Comando itР“РЋlica",legend:"Presiona ${italic}"},{name:"Comando subrayar",legend:"Presiona ${underline}"},{name:"Comando liga",legend:"Presiona ${liga}"},{name:"Comando colapsar barra de herramientas",legend:"Presiona ${toolbarCollapse}"},{name:"Comando accesar el anterior espacio de foco",legend:"Presiona ${accessPreviousSpace} para accesar el espacio de foco no disponible mР“РЋs cercano anterior al cursor, por ejemplo: dos elementos HR adyacentes. Repite la combinaciР“С–n de teclas para alcanzar espacios de foco distantes."},
{name:"Comando accesar el siguiente spacio de foco",legend:"Presiona ${accessNextSpace} para accesar el espacio de foco no disponible mР“РЋs cercano despuР“В©s del cursor, por ejemplo: dos elementos HR adyacentes. Repite la combinaciР“С–n de teclas para alcanzar espacios de foco distantes."},{name:"Ayuda de Accesibilidad",legend:"Presiona ${a11yHelp}"}]}],tab:"Tabulador",pause:"Pausa",capslock:"Bloq. MayР“С”s.",escape:"Escape",pageUp:"Regresar PР“РЋgina",pageDown:"Avanzar PР“РЋgina",leftArrow:"Flecha Izquierda",upArrow:"Flecha Arriba",
rightArrow:"Flecha Derecha",downArrow:"Flecha Abajo",insert:"Insertar",leftWindowKey:"Tecla Windows Izquierda",rightWindowKey:"Tecla Windows Derecha",selectKey:"Tecla de SelecciР“С–n",numpad0:"Tecla 0 del teclado numР“В©rico",numpad1:"Tecla 1 del teclado numР“В©rico",numpad2:"Tecla 2 del teclado numР“В©rico",numpad3:"Tecla 3 del teclado numР“В©rico",numpad4:"Tecla 4 del teclado numР“В©rico",numpad5:"Tecla 5 del teclado numР“В©rico",numpad6:"Tecla 6 del teclado numР“В©rico",numpad7:"Tecla 7 del teclado numР“В©rico",numpad8:"Tecla 8 del teclado numР“В©rico",
numpad9:"Tecla 9 del teclado numР“В©rico",multiply:"Multiplicar",add:"Sumar",subtract:"Restar",decimalPoint:"Punto Decimal",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Punto y coma",equalSign:"Signo de Igual",comma:"Coma",dash:"GuiР“С–n",period:"Punto",forwardSlash:"Diagonal",graveAccent:"Acento Grave",openBracket:"Abrir llave",backSlash:"Diagonal Invertida",closeBracket:"Cerrar llave",
singleQuote:"Comillas simples"});