РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fi",{title:"Saavutettavuus ohjeet",contents:"Ohjeen sisР“В¤llР“В¶t. Sulkeaksesi tР“В¤mР“В¤n dialogin paina ESC.",legend:[{name:"Yleinen",items:[{name:"Editorin tyР“В¶kalupalkki",legend:"Paina ${toolbarFocus} siirtyР“В¤ksesi tyР“В¶kalupalkkiin. Siirry seuraavaan ja edelliseen tyР“В¶kalupalkin ryhmР“В¤Р“В¤n TAB ja SHIFT+TAB nР“В¤ppР“В¤imillР“В¤. Siirry seuraavaan ja edelliseen tyР“В¶kalupainikkeeseen kР“В¤yttР“В¤mР“В¤llР“В¤ NUOLI OIKEALLE tai NUOLI VASEMMALLE nР“В¤ppР“В¤imillР“В¤. Paina VР“вЂћLILYР“вЂ“NTI tai ENTER nР“В¤ppР“В¤intР“В¤ aktivoidaksesi tyР“В¶kalupainikkeen."},
{name:"Editorin dialogi",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editorin oheisvalikko",legend:"Paina ${contextMenu} tai SOVELLUSPAINIKETTA avataksesi oheisvalikon. Liiku seuraavaan valikon vaihtoehtoon TAB tai NUOLI ALAS nР“В¤ppР“В¤imillР“В¤. Siirry edelliseen vaihtoehtoon SHIFT+TAB tai NUOLI YLР“вЂ“S nР“В¤ppР“В¤imillР“В¤. Paina VР“вЂћLILYР“вЂ“NTI tai ENTER valitaksesi valikon kohdan. Avataksesi nykyisen kohdan alivalikon paina VР“вЂћLILYР“вЂ“NTI tai ENTER tai NUOLI OIKEALLE painiketta. SiirtyР“В¤ksesi takaisin valikon ylemmР“В¤lle tasolle paina ESC tai NUOLI vasemmalle. Oheisvalikko suljetaan ESC painikkeella."},
{name:"Editorin listalaatikko",legend:"Listalaatikon sisР“В¤llР“В¤ siirry seuraavaan listan kohtaan TAB tai NUOLI ALAS painikkeilla. Siirry edelliseen listan kohtaan SHIFT+TAB tai NUOLI YLР“вЂ“S painikkeilla. Paina VР“вЂћLILYР“вЂ“NTI tai ENTER valitaksesi listan vaihtoehdon. Paina ESC sulkeaksesi listalaatikon."},{name:"Editorin elementtipolun palkki",legend:"Paina ${elementsPathFocus} siirtyР“В¤ksesi elementtipolun palkkiin. Siirry seuraavaan elementtipainikkeeseen TAB tai NUOLI OIKEALLE painikkeilla. Siirry aiempaan painikkeeseen SHIFT+TAB tai NUOLI VASEMMALLE painikkeilla. Paina VР“вЂћLILYР“вЂ“NTI tai ENTER valitaksesi elementin editorissa."}]},
{name:"Komennot",items:[{name:"Peruuta komento",legend:"Paina ${undo}"},{name:"Tee uudelleen komento",legend:"Paina ${redo}"},{name:"Lihavoi komento",legend:"Paina ${bold}"},{name:"Kursivoi komento",legend:"Paina ${italic}"},{name:"Alleviivaa komento",legend:"Paina ${underline}"},{name:"Linkki komento",legend:"Paina ${link}"},{name:"PienennР“В¤ tyР“В¶kalupalkki komento",legend:"Paina ${toolbarCollapse}"},{name:"Siirry aiempaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiryР“В¤ksesi lР“В¤himpР“В¤Р“В¤n kursorin edellР“В¤ olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekkР“В¤istР“В¤ HR elementtiР“В¤. Toista nР“В¤ppР“В¤inyhdistelmР“В¤Р“В¤ pР“В¤Р“В¤stР“В¤ksesi kauempana oleviin fokustiloihin."},
{name:"Siirry seuraavaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiryР“В¤ksesi lР“В¤himpР“В¤Р“В¤n kursorin jР“В¤lkeen olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekkР“В¤istР“В¤ HR elementtiР“В¤. Toista nР“В¤ppР“В¤inyhdistelmР“В¤Р“В¤ pР“В¤Р“В¤stР“В¤ksesi kauempana oleviin fokustiloihin."},{name:"Saavutettavuus ohjeet",legend:"Paina ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",
downArrow:"Down Arrow",insert:"Insert",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"NumeronР“В¤ppР“В¤imistР“В¶ 0",numpad1:"NumeronР“В¤ppР“В¤imistР“В¶ 1",numpad2:"NumeronР“В¤ppР“В¤imistР“В¶ 2",numpad3:"NumeronР“В¤ppР“В¤imistР“В¶ 3",numpad4:"NumeronР“В¤ppР“В¤imistР“В¶ 4",numpad5:"NumeronР“В¤ppР“В¤imistР“В¶ 5",numpad6:"NumeronР“В¤ppР“В¤imistР“В¶ 6",numpad7:"NumeronР“В¤ppР“В¤imistР“В¶ 7",numpad8:"NumeronР“В¤ppР“В¤imistР“В¶ 8",numpad9:"NumeronР“В¤ppР“В¤imistР“В¶ 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",
divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Puolipiste",equalSign:"Equal Sign",comma:"Pilkku",dash:"Dash",period:"Piste",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});