РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr",{title:"Instructions d'accessibilitР“В©",contents:"Contenu de l'aide. Pour fermer cette fenР“Р„tre, appuyez sur la touche Р“вЂ°chap.",legend:[{name:"GР“В©nР“В©ral",items:[{name:"Barre d'outils de l'Р“В©diteur",legend:"Appuyer sur ${toolbarFocus} pour accР“В©der Р“В  la barre d'outils. Se dР“В©placer vers le groupe suivant ou prР“В©cР“В©dent de la barre d'outils avec les touches Tab et Maj+Tab. Se dР“В©placer vers le bouton suivant ou prР“В©cР“В©dent de la barre d'outils avec les touches FlР“РЃche droite et FlР“РЃche gauche. Appuyer sur la barre d'espace ou la touche EntrР“В©e pour activer le bouton de barre d'outils."},
{name:"FenР“Р„tre de l'Р“В©diteur",legend:"Dans une boР“В®te de dialogue, appuyer sur Tab pour passer Р“В  l'Р“В©lР“В©ment suivant, appuyer sur Maj+Tab pour passer Р“В  l'Р“В©lР“В©ment prР“В©cР“В©dent, appuyer sur EntrР“В©e pour valider, appuyer sur Р“вЂ°chap pour annuler. Quand une boР“В®te de dialogue possР“РЃde des onglets, la liste peut Р“Р„tre atteinte avec Alt+F10 ou avec Tab. Dans la liste des onglets, se dР“В©placer vers le suivant et le prР“В©cР“В©dent avec les touches FlР“РЃche droite et FlР“РЃche gauche respectivement."},{name:"Menu contextuel de l'Р“В©diteur",
legend:"Appuyer sur ${contextMenu} ou sur la touche Menu pour ouvrir le menu contextuel. Se dР“В©placer ensuite vers l'option suivante du menu avec les touches Tab ou FlР“РЃche bas. Se dР“В©placer vers l'option prР“В©cР“В©dente avec les touches Maj+Tab ou FlР“РЃche haut. Appuyer sur la barre d'espace ou la touche EntrР“В©e pour sР“В©lectionner l'option du menu. Appuyer sur la barre d'espace, la touche EntrР“В©e ou FlР“РЃche droite pour ouvrir le sous-menu de l'option sР“В©lectionnР“В©e. Revenir Р“В  l'Р“В©lР“В©ment de menu parent avec la touche Р“вЂ°chap ou FlР“РЃche gauche. Fermer le menu contextuel avec Р“вЂ°chap."},
{name:"Zone de liste de l'Р“В©diteur",legend:"Dans une liste en menu dР“В©roulant, se dР“В©placer vers l'Р“В©lР“В©ment suivant de la liste avec les touches Tab ou FlР“РЃche bas. Se dР“В©placer vers l'Р“В©lР“В©ment prР“В©cР“В©dent de la liste avec les touches Maj+Tab ou FlР“РЃche haut. Appuyer sur la barre d'espace ou sur EntrР“В©e pour sР“В©lectionner l'option dans la liste. Appuyer sur Р“вЂ°chap pour fermer le menu dР“В©roulant."},{name:"Barre du chemin d'Р“В©lР“В©ments de l'Р“В©diteur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre du fil d'Ariane des Р“В©lР“В©ments. Se dР“В©placer vers le bouton de l'Р“В©lР“В©ment suivant avec les touches Tab ou FlР“РЃche droite. Se dР“В©placer vers le bouton prР“В©cР“В©dent avec les touches Maj+Tab ou FlР“РЃche gauche. Appuyer sur la barre d'espace ou sur EntrР“В©e pour sР“В©lectionner l'Р“В©lР“В©ment dans l'Р“В©diteur."}]},
{name:"Commandes",items:[{name:" Annuler la commande",legend:"Appuyer sur ${undo}"},{name:"Commande restaurer",legend:"Appuyer sur ${redo}"},{name:" Commande gras",legend:"Appuyer sur ${bold}"},{name:" Commande italique",legend:"Appuyer sur ${italic}"},{name:" Commande soulignР“В©",legend:"Appuyer sur ${underline}"},{name:" Commande lien",legend:"Appuyer sur ${link}"},{name:" Commande enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"Commande d'accР“РЃs Р“В  l'Р“В©lР“В©ment sР“В©lectionnable prР“В©cР“В©dent",
legend:"Appuyer sur ${accessNextSpace} pour accР“В©der Р“В  l'Р“В©lР“В©ment sР“В©lectionnable inatteignable le plus proche avant le curseur, par exempleР’В : deux lignes horizontales adjacentes. RР“В©pР“В©ter la combinaison de touches pour atteindre les Р“В©lР“В©ments sР“В©lectionnables prР“В©cР“В©dents."},{name:"Commande d'accР“РЃs Р“В  l'Р“В©lР“В©ment sР“В©lectionnable suivant",legend:"Appuyer sur ${accessNextSpace} pour accР“В©der Р“В  l'Р“В©lР“В©ment sР“В©lectionnable inatteignable le plus proche aprР“РЃs le curseur, par exempleР’В : deux lignes horizontales adjacentes. RР“В©pР“В©ter la combinaison de touches pour atteindre les Р“В©lР“В©ments sР“В©lectionnables suivants."},
{name:" Aide sur l'accessibilitР“В©",legend:"Appuyer sur ${a11yHelp}"}]}],tab:"Tabulation",pause:"Pause",capslock:"Verr. Maj.",escape:"Р“вЂ°chap",pageUp:"Page supР“В©rieure",pageDown:"Page suivante",leftArrow:"FlР“РЃche gauche",upArrow:"FlР“РЃche haut",rightArrow:"FlР“РЃche droite",downArrow:"FlР“РЃche basse",insert:"Inser",leftWindowKey:"Touche Windows gauche",rightWindowKey:"Touche Windows droite",selectKey:"Touche SР“В©lectionner",numpad0:"0 du pavР“В© numР“В©rique",numpad1:"1 du pavР“В© numР“В©rique",numpad2:"2 du pavР“В© numР“В©rique",
numpad3:"3 du pavР“В© numР“В©rique",numpad4:"4 du pavР“В© numР“В©rique",numpad5:"5 du pavР“В© numР“В©rique",numpad6:"6 du pavР“В© numР“В©rique",numpad7:"7 du pavР“В© numР“В©rique",numpad8:"PavР“В© numР“В©rique 8",numpad9:"9 du pavР“В© numР“В©rique",multiply:"Multiplier",add:"Plus",subtract:"Moins",decimalPoint:"Point dР“В©cimal",divide:"Diviser",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Verr. Num.",scrollLock:"ArrР“Р„t dР“В©fil.",semiColon:"Point-virgule",equalSign:"Signe Р“В©gal",
comma:"Virgule",dash:"Tiret",period:"Point",forwardSlash:"Barre oblique",graveAccent:"Accent grave",openBracket:"ParenthР“РЃse ouvrante",backSlash:"Barre oblique inverse",closeBracket:"ParenthР“РЃse fermante",singleQuote:"Apostrophe"});