РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","gl",{title:"InstruciР“С–ns de accesibilidade",contents:"Axuda. Para pechar este diР“РЋlogo prema ESC.",legend:[{name:"Xeral",items:[{name:"Barra de ferramentas do editor",legend:"Prema ${toolbarFocus} para navegar pola barra de ferramentas. Para moverse polos distintos grupos de ferramentas use as teclas TAB e MAIР“С™S+TAB. Para moverse polas distintas ferramentas use FRECHA DEREITA ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para activar o botР“С–n da barra de ferramentas."},
{name:"Editor de diР“РЋlogo",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor do menР“С” contextual",legend:"Prema ${contextMenu} ou a TECLA MENР“С™ para abrir o menР“С” contextual. A seguir mР“С–vase Р“РЋ seguinte opciР“С–n do menР“С” con TAB ou FRECHA ABAIXO. MР“С–vase Р“РЋ opciР“С–n anterior con MAIР“С™S + TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para seleccionar a opciР“С–n do menР“С”. Abra o submenР“С” da opciР“С–n actual con ESPAZO ou INTRO ou FRECHA DEREITA. Regrese ao elemento principal do menР“С” con ESC ou FRECHA ESQUERDA. Peche o menР“С” contextual con ESC."},
{name:"Lista do editor",legend:"Dentro dunha lista, mР“С–vase ao seguinte elemento da lista con TAB ou FRECHA ABAIXO. MР“С–vase ao elemento anterior da lista con MAIР“С™S+TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para escoller a opciР“С–n da lista. Prema ESC para pechar a lista."},{name:"Barra da ruta ao elemento no editor",legend:"Prema ${elementsPathFocus} para navegar ata os elementos da barra de ruta. MР“С–vase ao seguinte elemento botР“С–n con TAB ou FRECHA DEREITA. MР“С–vase ao botР“С–n anterior con MAIР“С™S+TAB ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para seleccionar o elemento no editor."}]},
{name:"Ordes",items:[{name:"Orde Р’В«desfacerР’В»",legend:"Prema ${undo}"},{name:"Orde Р’В«refacerР’В»",legend:"Prema ${redo}"},{name:"Orde Р’В«negraР’В»",legend:"Prema ${bold}"},{name:"Orde Р’В«cursivaР’В»",legend:"Prema ${italic}"},{name:"Orde Р’В«subliР“В±arР’В»",legend:"Prema ${underline}"},{name:"Orde Р’В«ligazР“С–nР’В»",legend:"Prema ${link}"},{name:"Orde Р’В«contraer a barra de ferramentasР’В»",legend:"Prema ${toolbarCollapse}"},{name:"Orde Р’В«acceder ao anterior espazo en focoР’В»",legend:"Prema ${accessPreviousSpace} para acceder ao espazo mР“РЋis prР“С–ximo de foco inalcanzР“РЋbel anterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinaciР“С–n de teclas para chegar a espazos de foco distantes."},
{name:"Orde Р’В«acceder ao seguinte espazo en focoР’В»",legend:"Prema ${accessNextSpace} para acceder ao espazo mР“РЋis prР“С–ximo de foco inalcanzР“РЋbel posterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinaciР“С–n de teclas para chegar a espazos de foco distantes."},{name:"Axuda da accesibilidade",legend:"Prema ${a11yHelp}"}]}],tab:"Tabulador",pause:"Pausa",capslock:"Bloq. MaiР“С”s",escape:"Escape",pageUp:"PР“РЋxina arriba",pageDown:"PР“РЋxina abaixo",leftArrow:"Frecha esquerda",upArrow:"Frecha arriba",
rightArrow:"Frecha dereita",downArrow:"Frecha abaixo",insert:"Inserir",leftWindowKey:"Tecla Windows esquerda",rightWindowKey:"Tecla Windows dereita",selectKey:"Escolla a tecla",numpad0:"Tec. numР“В©rico 0",numpad1:"Tec. numР“В©rico 1",numpad2:"Tec. numР“В©rico 2",numpad3:"Tec. numР“В©rico 3",numpad4:"Tec. numР“В©rico 4",numpad5:"Tec. numР“В©rico 5",numpad6:"Tec. numР“В©rico 6",numpad7:"Tec. numР“В©rico 7",numpad8:"Tec. numР“В©rico 8",numpad9:"Tec. numР“В©rico 9",multiply:"Multiplicar",add:"Sumar",subtract:"Restar",decimalPoint:"Punto decimal",
divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Bloq. num.",scrollLock:"Bloq. despraz.",semiColon:"Punto e coma",equalSign:"Signo igual",comma:"Coma",dash:"GuiР“С–n",period:"Punto",forwardSlash:"Barra inclinada",graveAccent:"Acento grave",openBracket:"Abrir corchete",backSlash:"Barra invertida",closeBracket:"Pechar corchete",singleQuote:"ComiР“В±a simple"});