РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"KisegР“В­tР•вЂ� utasР“В­tР“РЋsok",contents:"SР“С”gР“С– tartalmak. A pР“РЋrbeszР“В©dablak bezР“РЋrР“РЋsР“РЋhoz nyomjon ESC-et.",legend:[{name:"Р“РѓltalР“РЋnos",items:[{name:"SzerkesztР•вЂ� EszkР“В¶ztР“РЋr",legend:"Nyomjon ${toolbarFocus} hogy kijelР“В¶lje az eszkР“В¶ztР“РЋrat. A kР“В¶vetkezР•вЂ� Р“В©s elР•вЂ�zР•вЂ� eszkР“В¶ztР“РЋr csoporthoz a TAB Р“В©s SHIFT+TAB-al juthat el. A kР“В¶vetkezР•вЂ� Р“В©s elР•вЂ�zР•вЂ� eszkР“В¶ztР“РЋr gombhoz a BAL NYР“РЊL vagy JOBB NYР“РЊL gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktivР“РЋlja az eszkР“В¶ztР“РЋr gombot."},{name:"SzerkeszР•вЂ� pР“РЋrbeszР“В©d ablak",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"SzerkesztР•вЂ� helyi menР“С�",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZР“РѓS BILLENTYР•В°T a helyi menР“С� megnyitР“РЋsР“РЋhoz. EzutР“РЋn a kР“В¶vetkezР•вЂ� menР“С�pontra lР“В©phet a TAB vagy LEFELР“вЂ° NYР“РЊLLAL. Az elР•вЂ�zР•вЂ� opciР“С–t a SHIFT+TAB vagy FELFELР“вЂ° NYР“РЊLLAL Р“В©rheti el. Nyomjon SPACE-t vagy ENTER-t a menР“С�pont kivР“РЋlasztР“РЋsР“РЋhoz. A jelenlegi menР“С�pont almenР“С�jР“В©nek megnyitР“РЋsР“РЋhoz nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A fР•вЂ�menР“С�hР“В¶z valР“С– visszatР“В©rР“В©shez nyomjon ESC-et vagy BAL NYILAT. A helyi menР“С� bezР“РЋrР“РЋsa az ESC billentyР•В±vel lehetsР“В©ges."},
{name:"SzerkesztР•вЂ� lista",legend:"A listР“РЋn belР“С�l a kР“В¶vetkezР•вЂ� elemre a TAB vagy LEFELР“вЂ° NYР“РЊLLAL mozoghat. Az elР•вЂ�zР•вЂ� elem kivР“РЋlasztР“РЋsР“РЋhoz nyomjon SHIFT+TAB-ot vagy FELFELР“вЂ° NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kivР“РЋlasztР“РЋsР“РЋhoz. Az ESC billentyР•В± megnyomР“РЋsР“РЋval bezР“РЋrhatja a listР“РЋt."},{name:"SzerkesztР•вЂ� elem utak sР“РЋv",legend:"Nyomj ${elementsPathFocus} hogy kijelР“В¶ld a elemek Р“С”t sР“РЋvjР“РЋt. A kР“В¶vetkezР•вЂ� elem gombhoz a TAB-al vagy a JOBB NYР“РЊLLAL juthatsz el. Az elР•вЂ�zР•вЂ� gombhoz a SHIFT+TAB vagy BAL NYР“РЊLLAL mehetsz. A SPACE vagy ENTER billentyР•В±vel kivР“РЋlaszthatod az elemet a szerkesztР•вЂ�ben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavonР“РЋsa",legend:"Nyomj ${undo}"},{name:"Parancs megismР“В©tlР“В©se",legend:"Nyomjon ${redo}"},{name:"FР“В©lkР“В¶vР“В©r parancs",legend:"Nyomjon ${bold}"},{name:"DР•вЂ�lt parancs",legend:"Nyomjon ${italic}"},{name:"AlР“РЋhР“С”zott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"SzerkesztР•вЂ�sР“РЋv Р“В¶sszecsukР“РЋsa parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"HozzР“РЋfР“В©rР“В©s az elР•вЂ�zР•вЂ� fР“С–kusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzР“РЋfР“В©rj a legkР“В¶zelebbi elР“В©rhetetlen fР“С–kusz helyhez a hiР“РЋnyjel elР•вЂ�tt, pР“В©ldР“РЋul: kР“В©t szomszР“В©dos HR elemhez. IsmР“В©teld meg a billentyР•В±kombinР“РЋciР“С–t hogy megtalР“РЋld a tР“РЋvolabbi fР“С–kusz helyeket."},
{name:"HozzР“РЋfР“В©rР“В©s a kР“В¶vetkezР•вЂ� fР“С–kusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzР“РЋfР“В©rj a legkР“В¶zelebbi elР“В©rhetetlen fР“С–kusz helyhez a hiР“РЋnyjel utР“РЋn, pР“В©ldР“РЋul: kР“В©t szomszР“В©dos HR elemhez. IsmР“В©teld meg a billentyР•В±kombinР“РЋciР“С–t hogy megtalР“РЋld a tР“РЋvolabbi fР“С–kusz helyeket."},{name:"KisegР“В­tР•вЂ� sР“С”gР“С–",legend:"Nyomjon ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"balra nyР“В­l",upArrow:"felfelР“В© nyР“В­l",rightArrow:"jobbra nyР“В­l",
downArrow:"lefelР“В© nyР“В­l",insert:"Insert",leftWindowKey:"bal Windows-billentyР•В±",rightWindowKey:"jobb Windows-billentyР•В±",selectKey:"BillentyР•В± vР“РЋlasztР“РЋsa",numpad0:"SzР“РЋmbillentyР•В±k 0",numpad1:"SzР“РЋmbillentyР•В±k 1",numpad2:"SzР“РЋmbillentyР•В±k 2",numpad3:"SzР“РЋmbillentyР•В±k 3",numpad4:"SzР“РЋmbillentyР•В±k 4",numpad5:"SzР“РЋmbillentyР•В±k 5",numpad6:"SzР“РЋmbillentyР•В±k 6",numpad7:"SzР“РЋmbillentyР•В±k 7",numpad8:"SzР“РЋmbillentyР•В±k 8",numpad9:"SzР“РЋmbillentyР•В±k 9",multiply:"SzorzР“РЋs",add:"HozzР“РЋadР“РЋs",subtract:"KivonР“РЋs",decimalPoint:"Tizedespont",
divide:"OsztР“РЋs",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"PontosvesszР•вЂ�",equalSign:"EgyenlР•вЂ�sР“В©gjel",comma:"VesszР•вЂ�",dash:"KР“В¶tР•вЂ�jel",period:"Pont",forwardSlash:"Perjel",graveAccent:"VisszafelР“В© dР•вЂ�lР•вЂ� Р“В©kezet",openBracket:"NyitР“С– szР“В¶gletes zР“РЋrР“С–jel",backSlash:"fordР“В­tott perjel",closeBracket:"ZР“РЋrР“С– szР“В¶gletes zР“РЋrР“С–jel",singleQuote:"szimpla idР“В©zР•вЂ�jel"});