РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","lv",{title:"PieejamР”В«bas instrukcija",contents:"PalР”В«dzР”В«bas saturs. Lai aizvР”вЂњrtu ciet Р•РЋo dialogu nospiediet ESC.",legend:[{name:"Galvenais",items:[{name:"Redaktora rР”В«kjosla",legend:"Nospiediet ${toolbarFocus} lai pР”Рѓrvietotos uz rР”В«kjoslu. Lai pР”Рѓrvietotos uz nР”РѓkoР•РЋo vai iepriekР•РЋР”вЂњjo rР”В«kjoslas grupu izmantojiet pogu TAB un SHIFT+TAB. Lai pР”Рѓrvietotos uz nР”РѓkoР•РЋo vai iepriekР•РЋР”вЂњjo rР”В«kjoslas pogu izmantojiet Kreiso vai Labo bultiР•вЂ u. Nospiediet Atstarpi vai ENTER lai aktivizР”вЂњtu rР”В«kjosla pogu."},
{name:"Redaktora dialoga  logs",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Redaktora satura izvР”вЂњle",legend:"Nospiediet ${contextMenu} vai APPLICATION KEY lai atvР”вЂњrtu satura izvР”вЂњlni. Lai pР”Рѓrvietotos uz nР”РѓkoР•РЋo izvР”вЂњlnes opciju izmantojiet pogu TAB vai pogu BultiР•вЂ u uz leju. Lai pР”Рѓrvietotos uz iepriekР•РЋР”вЂњjo opciju izmantojiet  SHIFT+TAB vai pogu BultiР•вЂ a uz augР•РЋu. Nospiediet SPACE vai ENTER lai izvelР”вЂњtos izvР”вЂњlnes opciju. Atveriet tekoР•РЋajР”Рѓ opcija apakР•РЋizvР”вЂњlni ar SAPCE vai ENTER ka ari to var izdarР”В«t ar Labo bultiР•вЂ u. Lai atgrieztos atpakaР”С� uz sakuma izvР”вЂњlni nospiediet ESC vai Kreiso bultiР•вЂ u. Lai aizvР”вЂњrtu ciet izvР”вЂњlnes saturu nospiediet ESC."},
{name:"Redaktora saraksta lauks",legend:"Saraksta laukР”Рѓ, lai pР”Рѓrvietotos uz nР”РѓkoР•РЋo saraksta elementu nospiediet TAB vai pogu BultiР•вЂ a uz leju. Lai pР”Рѓrvietotos uz iepriekР•РЋР”вЂњjo saraksta elementu nospiediet SHIFT+TAB vai pogu BultiР•вЂ a uz augР•РЋu. Nospiediet SPACE vai ENTER lai izvР”вЂњlР”вЂњtos saraksta opcijas. Nospiediet ESC lai aizvР”вЂњrtu saraksta lauku."},{name:"Redaktora elementa ceР”С�a josla",legend:"Nospiediet ${elementsPathFocus} lai pР”Рѓrvietotos uz elementa ceР”С�a joslu. Lai pР”Рѓrvietotos uz nР”РѓkoР•РЋo elementa pogu izmantojiet TAB vai Labo bultiР•вЂ u. Lai pР”Рѓrvietotos uz iepriekР•РЋР”вЂњjo elementa pogu izmantojiet SHIFT+TAB vai Kreiso bultiР•вЂ u. Nospiediet SPACE vai ENTER lai izvР”вЂњlР”вЂњtos elementu redaktorР”Рѓ."}]},
{name:"Komandas",items:[{name:"Komanda atcelt darbР”В«bu",legend:"Nospiediet ${undo}"},{name:"Komanda atkР”Рѓrtot darbР”В«bu",legend:"Nospiediet ${redo}"},{name:"Treknraksta komanda",legend:"Nospiediet ${bold}"},{name:"KursР”В«va komanda",legend:"Nospiediet ${italic}"},{name:"ApakР•РЋsvР”В«tras komanda ",legend:"Nospiediet ${underline}"},{name:"Hipersaites komanda",legend:"Nospiediet ${link}"},{name:"RР”В«kjoslas aizvР”вЂњrР•РЋanas komanda",legend:"Nospiediet ${toolbarCollapse}"},{name:"PiekР”С�Р•В«t iepriekР•РЋР”вЂњjai fokusa vietas komandai",
legend:"Nospiediet ${accessPreviousSpace} lai piekР”С�Р•В«tu tuvР”Рѓkajai nepieejamajai fokusa vietai pirms kursora. PiemР”вЂњram: diviem blakus esoР•РЋiem lР”В«nijas HR elementiem. AtkР”Рѓrtojiet taustiР•вЂ u kombinР”Рѓciju lai piekР”С�Р•В«tu pie tР”РѓlР”РѓkР”Рѓm vietР”Рѓm."},{name:"PiekР”С�Р•В«t nР”РѓkoР•РЋР”Рѓ fokusa apgabala komandai",legend:"Nospiediet ${accessNextSpace} lai piekР”С�Р•В«tu tuvР”Рѓkajai nepieejamajai fokusa vietai pР”вЂњc kursora. PiemР”вЂњram: diviem blakus esoР•РЋiem lР”В«nijas HR elementiem. AtkР”Рѓrtojiet taustiР•вЂ u kombinР”Рѓciju lai piekР”С�Р•В«tu pie tР”РѓlР”РѓkР”Рѓm vietР”Рѓm."},
{name:"PieejamР”В«bas palР”В«dzР”В«ba",legend:"Nospiediet ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",
numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});