РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","mk",{title:"Р пїЅР Р…РЎРѓРЎвЂљРЎР‚РЎС“Р С”РЎвЂ Р С‘Р С‘ Р В·Р В° Р С—РЎР‚Р С‘РЎРѓРЎвЂљР В°Р С—Р Р…Р С•РЎРѓРЎвЂљ",contents:"Р РЋР С•Р Т‘РЎР‚Р В¶Р С‘Р Р…Р В° Р Р…Р В° Р Т‘Р ВµР В»Р С•РЎвЂљ Р В·Р В° Р С—Р С•Р С�Р С•РЎв‚¬. Р вЂ”Р В° Р Т‘Р В° Р С–Р С• Р В·Р В°РЎвЂљР Р†Р С•РЎР‚Р С‘РЎвЂљР Вµ Р С•Р Р†Р С•РЎпїЅ Р Т‘Р С‘РЎпїЅР В°Р В»Р С•Р С– Р С—РЎР‚Р С‘РЎвЂљР С‘РЎРѓР Р…Р ВµРЎвЂљР Вµ ESC.",legend:[{name:"Р С›Р С—РЎв‚¬РЎвЂљР С•",items:[{name:"Р СљР ВµР Р…Р С‘ Р В·Р В° РЎС“РЎР‚Р ВµР Т‘РЎС“Р Р†Р В°РЎвЂЎР С•РЎвЂљ",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"Р вЂќР С‘РЎпїЅР В°Р В»Р С•РЎвЂљ Р В·Р В° Р ВµР Т‘Р С‘РЎвЂљР С•РЎР‚Р С•РЎвЂљ",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Р С™Р С•Р Р…РЎвЂљР ВµР С”РЎРѓРЎвЂљ-Р С�Р ВµР Р…Р С‘ Р Р…Р В° РЎС“РЎР‚Р ВµР Т‘РЎС“Р Р†Р В°РЎвЂЎР С•РЎвЂљ",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},
{name:"Editor List Box",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},
{name:"Р СњР В°РЎР‚Р ВµР Т‘Р В±Р С‘",items:[{name:" Undo command",legend:"Press ${undo}"},{name:" Redo command",legend:"Press ${redo}"},{name:" Bold command",legend:"Press ${bold}"},{name:" Italic command",legend:"Press ${italic}"},{name:" Underline command",legend:"Press ${underline}"},{name:" Link command",legend:"Press ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Accessibility Help",legend:"Press ${a11yHelp}"}]}],tab:"Tab",pause:"Р СџР В°РЎС“Р В·Р В°",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Up",leftArrow:"Р РЋРЎвЂљРЎР‚Р ВµР В»Р С”Р В° Р В»Р ВµР Р†Р С•",upArrow:"Р РЋРЎвЂљРЎР‚Р ВµР В»Р С”Р В° Р С–Р С•РЎР‚Р Вµ",rightArrow:"Р РЋРЎвЂљРЎР‚Р ВµР В»Р С”Р В° Р Т‘Р ВµРЎРѓР Р…Р С•",downArrow:"Р РЋРЎвЂљРЎР‚Р ВµР В»Р С”Р В° Р Т‘Р С•Р В»Р Вµ",insert:"Insert",
leftWindowKey:"Р вЂєР ВµР Р†Р С• Windows Р С”Р С•Р С—РЎвЂЎР Вµ",rightWindowKey:"Р вЂќР ВµРЎРѓР Р…Р С• Windows Р С”Р С•Р С—РЎвЂЎР Вµ",selectKey:"Select Р С”Р С•Р С—РЎвЂЎР Вµ",numpad0:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 0",numpad1:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 1",numpad2:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 2",numpad3:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 3",numpad4:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 4",numpad5:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 5",numpad6:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 6",numpad7:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 7",numpad8:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 8",numpad9:"Р СњРЎС“Р С�. РЎвЂљР В°РЎРѓРЎвЂљ. 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",
f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});