РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","nb",{title:"Instruksjoner for tilgjengelighet",contents:"Innhold for hjelp. Trykk ESC for Р“Тђ lukke denne dialogen.",legend:[{name:"Generelt",items:[{name:"VerktР“С‘ylinje for editor",legend:"Trykk ${toolbarFocus} for Р“Тђ navigere til verktР“С‘ylinjen. Flytt til neste og forrige verktР“С‘ylinjegruppe med TAB og SHIFT+TAB. Flytt til neste og forrige verktР“С‘ylinjeknapp med HР“пїЅYRE PILTAST og VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for Р“Тђ aktivere verktР“С‘ylinjeknappen."},{name:"Dialog for editor",
legend:"Mens du er i en dialog, trykk TAB for Р“Тђ navigere til neste dialogelement, trykk SHIFT+TAB for Р“Тђ flytte til forrige dialogelement, trykk ENTER for Р“Тђ akseptere dialogen, trykk ESC for Р“Тђ avbryte dialogen. NР“Тђr en dialog har flere faner, kan fanelisten nР“Тђs med enten ALT+F10 eller med TAB. NР“Тђr fanelisten er fokusert, gР“Тђr man til neste og forrige fane med henholdsvis HР“пїЅYRE og VENSTRE PILTAST."},{name:"Kontekstmeny for editor",legend:"Trykk ${contextMenu} eller MENYKNAPP for Р“Тђ Р“Тђpne kontekstmeny. GР“Тђ til neste alternativ i menyen med TAB eller PILTAST NED. GР“Тђ til forrige alternativ med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for Р“Тђ velge menyalternativet. Р“вЂ¦pne undermenyen pР“Тђ valgt alternativ med MELLOMROM eller ENTER eller HР“пїЅYRE PILTAST. GР“Тђ tilbake til overordnet menyelement med ESC eller VENSTRE PILTAST. Lukk kontekstmenyen med ESC."},
{name:"Listeboks for editor",legend:"I en listeboks, gР“Тђ til neste alternativ i listen med TAB eller PILTAST NED. GР“Тђ til forrige alternativ i listen med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for Р“Тђ velge alternativet i listen. Trykk ESC for Р“Тђ lukke listeboksen."},{name:"VerktР“С‘ylinje for elementsti",legend:"Trykk ${elementsPathFocus} for Р“Тђ navigere til verktР“С‘ylinjen som viser elementsti. GР“Тђ til neste elementknapp med TAB eller HР“пїЅYRE PILTAST. GР“Тђ til forrige elementknapp med SHIFT+TAB eller VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for Р“Тђ velge elementet i editoren."}]},
{name:"Hurtigtaster",items:[{name:"Angre",legend:"Trykk ${undo}"},{name:"GjР“С‘r om",legend:"Trykk ${redo}"},{name:"Fet tekst",legend:"Trykk ${bold}"},{name:"Kursiv tekst",legend:"Trykk ${italic}"},{name:"Understreking",legend:"Trykk ${underline}"},{name:"Lenke",legend:"Trykk ${link}"},{name:"Skjul verktР“С‘ylinje",legend:"Trykk ${toolbarCollapse}"},{name:"GР“Тђ til forrige fokusomrР“Тђde",legend:"Trykk ${accessPreviousSpace} for Р“Тђ komme til nР“В¦rmeste fokusomrР“Тђde fР“С‘r skrivemarkР“С‘ren som ikke kan nР“Тђs pР“Тђ vanlig mР“Тђte, for eksempel to tilstР“С‘tende HR-elementer. Gjenta tastekombinasjonen for Р“Тђ komme til fokusomrР“Тђder lenger unna i dokumentet."},
{name:"GР“Тђ til neste fokusomrР“Тђde",legend:"Trykk ${accessNextSpace} for Р“Тђ komme til nР“В¦rmeste fokusomrР“Тђde etter skrivemarkР“С‘ren som ikke kan nР“Тђs pР“Тђ vanlig mР“Тђte, for eksempel to tilstР“С‘tende HR-elementer. Gjenta tastekombinasjonen for Р“Тђ komme til fokusomrР“Тђder lenger unna i dokumentet."},{name:"Hjelp for tilgjengelighet",legend:"Trykk ${a11yHelp}"}]}],tab:"Tabulator",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Venstre piltast",upArrow:"Opp-piltast",
rightArrow:"HР“С‘yre piltast",downArrow:"Ned-piltast",insert:"Insert",leftWindowKey:"Venstre Windows-tast",rightWindowKey:"HР“С‘yre Windows-tast",selectKey:"Velg nР“С‘kkel",numpad0:"Numerisk tastatur 0",numpad1:"Numerisk tastatur 1",numpad2:"Numerisk tastatur 2",numpad3:"Numerisk tastatur 3",numpad4:"Numerisk tastatur 4",numpad5:"Numerisk tastatur 5",numpad6:"Numerisk tastatur 6",numpad7:"Numerisk tastatur 7",numpad8:"Numerisk tastatur 8",numpad9:"Numerisk tastatur 9",multiply:"Multipliser",add:"Legg til",
subtract:"Trekk fra",decimalPoint:"Desimaltegn",divide:"Divider",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Likhetstegn",comma:"Komma",dash:"Bindestrek",period:"Punktum",forwardSlash:"Forover skrР“Тђstrek",graveAccent:"Grav aksent",openBracket:"Р“вЂ¦pne parentes",backSlash:"Bakover skrР“Тђstrek",closeBracket:"Lukk parentes",singleQuote:"Enkelt sitattegn"});