РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","oc",{title:"Instruccions d'accessibilitat",contents:"Contengut de l'ajuda. Per tampar aquesta fenР“РЃstra, quichatz sus la tР“Р†ca Escap.",legend:[{name:"General",items:[{name:"Barra d'aisinas de l'editor",legend:"Quichar sus ${toolbarFocus} per accedir a la barra d'aisinas. Se desplaР“В§ar cap al groupe seguent o precedent de la barra d'aisinas amb las tР“Р†cas Tab e Maj+Tab. Se desplaР“В§ar cap al boton seguent o precedent de la barra d'aisinas amb las tР“Р†cas Sageta dreita e Sageta esquР“РЃrra. Quichar sus la barra d'espaci o la tР“Р†ca Entrada per activer lo boton de barra d'aisinas."},
{name:"FenР“РЃstra de l'editor",legend:"Dins una bР“С–stia de dialР“Р†g, quichar sus Tab per passar a l'element seguent, quichar sus Maj+Tab per passar a l'element precedent, quichar sus Entrada per validar, quichar sus Escap per anullar. Quand una bР“С–stia de dialР“Р†g possedР“В­s des onglets, la lista pР“Р†t Р“РЃsser atenta amb Alt+F10 o amb Tab. Dins la lista dels onglets, se desplaР“В§ar cap al seguent e lo precedent amb las tР“Р†cas Sageta dreita e Sageta esquР“РЃrra respectivament."},{name:"MenР“С” contextual de l'editor",legend:"Quichar sus ${contextMenu} o sus la tР“Р†ca MenР“С” per dobrir lo menР“С” contextual. Se desplaР“В§ar ensuite cap a l'opcion seguenta del menР“С” amb las tР“Р†cas Tab o Sageta bas. Se desplaР“В§ar cap a l'opcion precedenta amb las tР“Р†cas Maj+Tab o Sageta naut. Quichar sus la barra d'espaci o la tР“Р†ca Entrada per seleccionar l'opcion del menu. Quichar sus la barra d'espaci, la tР“Р†ca Entrada o Sageta dreita per dobrir lo sosmenР“С” de l'opcion seleccionada. Tornar a l'element de menР“С” parent amb la tР“Р†ca Escap o Sageta esquР“РЃrra. Tampar lo menР“С” contextual amb Escap."},
{name:"ZР“Р†na de lista de l'editor",legend:"Dins una lista en menР“С” desenrotlant, se desplaР“В§ar cap a l'element seguent de la lista amb las tР“Р†cas Tab o Sageta bas. Se desplaР“В§ar cap a l'element precedent de la lista amb las tР“Р†cas Maj+Tab o Sageta naut. Quichar sus la barra d'espaci o sus Entrada per seleccionar l'opcion dins la lista. Quichar sus Escap per tampar lo menР“С” desenrotlant."},{name:"Barra del camin d'elements de l'editor",legend:"Quichar sus ${elementsPathFocus} per naviguer cap a la barra del fial d'Ariana dels elements. Se desplaР“В§ar cap al boton de l'element seguent amb las tР“Р†cas Tab o Sageta dreita. Se desplaР“В§ar cap al boton precedent amb las tР“Р†cas Maj+Tab o Sageta esquР“РЃrra. Quichar sus la barra d'espaci o sus Entrada per seleccionar l'element dins l'editor."}]},
{name:"Comandas",items:[{name:"Anullar la comanda",legend:"Quichar sus ${undo}"},{name:"Comanda restablir",legend:"Quichar sus ${redo}"},{name:" Comanda gras",legend:"Quichar sus ${bold}"},{name:" Comanda italica",legend:"Quichar sus ${italic}"},{name:" Comanda solinhat",legend:"Quichar sus ${underline}"},{name:" Comanda ligam",legend:"Quichar sus ${link}"},{name:"Comanda enrotlar la barra d'aisinas",legend:"Quichar sus ${toolbarCollapse}"},{name:"Comanda d'accР“РЃs a l'element seleccionable precedent",
legend:"Quichar sus ${accessNextSpace} per accedir a l'element seleccionable inategnible lo mai prР“Р†che abans lo cursor, per exempleР’В : doas linhas orizontalas adjacentas. Repetir la combinason de tР“Р†cas per atР“В©nher los elements seleccionables precedents."},{name:"Comanda d'accР“РЃs a l'element seleccionable seguent",legend:"Quichar sus ${accessNextSpace} per accedir a l'element seleccionable inatenhible lo mai prР“Р†che aprР“РЃp lo cursor, per exempleР’В : doas linhas orizontalas adjacentas. Repetir la combinason de tР“Р†cas per atР“В©nher los elements seleccionables seguents."},
{name:" Ajuda sus l'accessibilitat",legend:"Quichar sus ${a11yHelp}"}]}],tab:"Tabulacion",pause:"Pausa",capslock:"Verr. Maj.",escape:"Escap",pageUp:"Pagina superiora",pageDown:"Pagina seguenta",leftArrow:"Sageta esquР“РЃrra",upArrow:"Sageta naut",rightArrow:"Sageta dreita",downArrow:"Sageta bassa",insert:"Inser",leftWindowKey:"TР“Р†ca Windows esquР“РЃrra",rightWindowKey:"TР“Р†ca Windows dreita",selectKey:"TР“Р†ca Seleccionar",numpad0:"0 del pavat numeric",numpad1:"1 del pavat numeric",numpad2:"2 del pavat numeric",
numpad3:"3 del pavat numeric",numpad4:"4 del pavat numeric",numpad5:"5 del pavat numeric",numpad6:"6 del pavat numeric",numpad7:"7 del pavat numeric",numpad8:"Pavat numeric 8",numpad9:"9 del pavat numeric",multiply:"Multiplicar",add:"Plus",subtract:"Mens",decimalPoint:"Punt decimal",divide:"Devesir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Verr. Num.",scrollLock:"ArrР“РЃst desfil.",semiColon:"Punt-virgula",equalSign:"Signe egal",comma:"Virgula",
dash:"Jonhent",period:"Punt",forwardSlash:"Barra oblica",graveAccent:"Accent grР“РЃu",openBracket:"ParentР“РЃsi dobР“РЃrta",backSlash:"Barra oblica invР“РЃrsa",closeBracket:"ParentР“РЃsi tampanta",singleQuote:"ApostrР“Р†fa"});