РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pl",{title:"Instrukcje dotyczР”вЂ¦ce dostР”в„ўpnoР•вЂєci",contents:"ZawartoР•вЂєР”вЂЎ pomocy. WciР•вЂєnij ESC, aby zamknР”вЂ¦Р”вЂЎ to okno.",legend:[{name:"Informacje ogР“С–lne",items:[{name:"Pasek narzР”в„ўdzi edytora",legend:"NaciР•вЂєnij ${toolbarFocus}, by przejР•вЂєР”вЂЎ do paska narzР”в„ўdzi. PrzejdР•С” do nastР”в„ўpnej i poprzedniej grupy narzР”в„ўdzi uР•С�ywajР”вЂ¦c TAB oraz SHIFT+TAB. PrzejdР•С” do nastР”в„ўpnego i poprzedniego przycisku paska narzР”в„ўdzi za pomocР”вЂ¦ STRZAР•РѓKI W PRAWO lub STRZAР•РѓKI W LEWO. NaciР•вЂєnij SPACJР”пїЅ lub ENTER by aktywowaР”вЂЎ przycisk paska narzР”в„ўdzi."},
{name:"Okno dialogowe edytora",legend:"WewnР”вЂ¦trz okna dialogowego naciР•вЂєnij TAB, by przejР•вЂєР”вЂЎ do kolejnego elementu tego okna lub SHIFT+TAB, by przejР•вЂєР”вЂЎ do poprzedniego elementu okna. NaciР•вЂєnij ENTER w celu zatwierdzenia opcji okna dialogowego lub ESC w celu anulowania zmian. JeР•вЂєli okno dialogowe ma kilka zakР•вЂљadek, do listy zakР•вЂљadek moР•С�na przejР•вЂєР”вЂЎ za pomocР”вЂ¦ ALT+F10 lub TAB. Gdy lista zakР•вЂљadek jest aktywna, moР•С�esz przejР•вЂєР”вЂЎ do kolejnej i poprzedniej zakР•вЂљadki za pomocР”вЂ¦ STRZAР•РѓKI W PRAWO i STRZAР•РѓKI W LEWO."},
{name:"Menu kontekstowe edytora",legend:"WciР•вЂєnij ${contextMenu} lub PRZYCISK APLIKACJI aby otworzyР”вЂЎ menu kontekstowe. PrzejdР•С” do nastР”в„ўpnej pozycji menu wciskajР”вЂ¦c TAB lub STRZAР•РѓKР”пїЅ W DР“вЂњР•Рѓ. PrzejdР•С” do poprzedniej pozycji menu wciskajР”вЂ¦c SHIFT + TAB lub STRZAР•РѓKР”пїЅ W GР“вЂњRР”пїЅ. WciР•вЂєnij SPACJР”пїЅ lub ENTER aby wygraР”вЂЎ pozycjР”в„ў menu. OtwР“С–rz pod-menu obecnej pozycji wciskajР”вЂ¦c SPACJР”пїЅ lub ENTER lub STRZAР•РѓKР”пїЅ W PRAWO. WrР“С–Р”вЂЎ do pozycji nadrzР”в„ўdnego menu wciskajР”вЂ¦c ESC lub STRZAР•РѓKР”пїЅ W LEWO. Zamknij menu wciskajР”вЂ¦c ESC."},{name:"Lista w edytorze",
legend:"WewnР”вЂ¦trz listy przejdР•С” do kolejnego elementu listy za pomocР”вЂ¦ przycisku TAB lub STRZAР•РѓKI W DР“вЂњР•Рѓ. PrzejdР•С” do poprzedniego elementu listy za pomocР”вЂ¦ SHIFT+TAB lub STRZAР•РѓKI W GР“вЂњRР”пїЅ. NaciР•вЂєnij SPACJР”пїЅ lub ENTER w celu wybrania opcji z listy. NaciР•вЂєnij ESC, by zamknР”вЂ¦Р”вЂЎ listР”в„ў."},{name:"Pasek Р•вЂєcieР•С�ki elementР“С–w edytora",legend:"NaciР•вЂєnij ${elementsPathFocus} w celu przejР•вЂєcia do paska Р•вЂєcieР•С�ki elementР“С–w edytora. W celu przejР•вЂєcia do kolejnego elementu naciР•вЂєnij klawisz TAB lub STRZAР•РѓKI W PRAWO. W celu przejР•вЂєcia do poprzedniego elementu naciР•вЂєnij klawisze SHIFT+TAB lub STRZAР•РѓKI W LEWO. By wybraР”вЂЎ element w edytorze, uР•С�yj klawisza SPACJI lub ENTER."}]},
{name:"Polecenia",items:[{name:"Polecenie Cofnij",legend:"NaciР•вЂєnij ${undo}"},{name:"Polecenie PonР“С–w",legend:"NaciР•вЂєnij ${redo}"},{name:"Polecenie Pogrubienie",legend:"NaciР•вЂєnij ${bold}"},{name:"Polecenie Kursywa",legend:"NaciР•вЂєnij ${italic}"},{name:"Polecenie PodkreР•вЂєlenie",legend:"NaciР•вЂєnij ${underline}"},{name:"Polecenie Wstaw/ edytuj odnoР•вЂєnik",legend:"NaciР•вЂєnij ${link}"},{name:"Polecenie schowaj pasek narzР”в„ўdzi",legend:"NaciР•вЂєnij ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"Pomoc dotyczР”вЂ¦ca dostР”в„ўpnoР•вЂєci",legend:"NaciР•вЂєnij ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"StrzaР•вЂљka w lewo",upArrow:"StrzaР•вЂљka w gР“С–rР”в„ў",rightArrow:"StrzaР•вЂљka w prawo",downArrow:"StrzaР•вЂљka w dР“С–Р•вЂљ",
insert:"Insert",leftWindowKey:"Lewy klawisz Windows",rightWindowKey:"Prawy klawisz Windows",selectKey:"Klawisz wyboru",numpad0:"Klawisz 0 na klawiaturze numerycznej",numpad1:"Klawisz 1 na klawiaturze numerycznej",numpad2:"Klawisz 2 na klawiaturze numerycznej",numpad3:"Klawisz 3 na klawiaturze numerycznej",numpad4:"Klawisz 4 na klawiaturze numerycznej",numpad5:"Klawisz 5 na klawiaturze numerycznej",numpad6:"Klawisz 6 na klawiaturze numerycznej",numpad7:"Klawisz 7 na klawiaturze numerycznej",numpad8:"Klawisz 8 na klawiaturze numerycznej",
numpad9:"Klawisz 9 na klawiaturze numerycznej",multiply:"PrzemnР“С–Р•С�",add:"Plus",subtract:"Minus",decimalPoint:"Separator dziesiР”в„ўtny",divide:"Podziel",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Р•С™rednik",equalSign:"Znak rР“С–wnoР•вЂєci",comma:"Przecinek",dash:"Pauza",period:"Kropka",forwardSlash:"UkoР•вЂєnik prawy",graveAccent:"Akcent sР•вЂљaby",openBracket:"Nawias kwadratowy otwierajР”вЂ¦cy",backSlash:"UkoР•вЂєnik lewy",
closeBracket:"Nawias kwadratowy zamykajР”вЂ¦cy",singleQuote:"Apostrof"});