РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt-br",{title:"InstruР“В§Р“Вµes de Acessibilidade",contents:"ConteР“С”do da Ajuda. Para fechar este diР“РЋlogo pressione ESC.",legend:[{name:"Geral",items:[{name:"Barra de Ferramentas do Editor",legend:"Pressione ${toolbarFocus} para navegar para a barra de ferramentas. Mova para o anterior ou prР“С–ximo grupo de ferramentas com TAB e SHIFT+TAB. Mova para o anterior ou prР“С–ximo botР“Р€o com SETA PARA DIREITA or SETA PARA ESQUERDA. Pressione ESPAР“вЂЎO ou ENTER para ativar o botР“Р€o da barra de ferramentas."},
{name:"DiР“РЋlogo do Editor",legend:"Dentro de um diР“РЋlogo, pressione TAB para navegar para o prР“С–ximo elemento. Pressione SHIFT+TAB para mover para o elemento anterior. Pressione ENTER ara enviar o diР“РЋlogo. pressione ESC para cancelar o diР“РЋlogo. Quando um diР“РЋlogo tem mР“С”ltiplas abas, a lista de abas pode ser acessada com ALT+F10 ou TAB, como parte da ordem de tabulaР“В§Р“Р€o do diР“РЋlogo. Com a lista de abas em foco, mova para a prР“С–xima aba e para a aba anterior com a SETA DIREITA ou SETA ESQUERDA, respectivamente."},
{name:"Menu de Contexto do Editor",legend:"Pressione ${contextMenu} ou TECLA DE MENU para abrir o menu de contexto, entР“Р€o mova para a prР“С–xima opР“В§Р“Р€o com TAB ou SETA PARA BAIXO. Mova para a anterior com SHIFT+TAB ou SETA PARA CIMA. Pressione ESPAР“вЂЎO ou ENTER para selecionar a opР“В§Р“Р€o do menu. Abra o submenu da opР“В§Р“Р€o atual com ESPAР“вЂЎO ou ENTER ou SETA PARA DIREITA. Volte para o menu pai com ESC ou SETA PARA ESQUERDA. Feche o menu de contexto com ESC."},{name:"Caixa de Lista do Editor",legend:"Dentro de uma caixa de lista, mova para o prР“С–ximo item com TAB ou SETA PARA BAIXO. Mova para o item anterior com SHIFT+TAB ou SETA PARA CIMA. Pressione ESPAР“вЂЎO ou ENTER para selecionar uma opР“В§Р“Р€o na lista. Pressione ESC para fechar a caixa de lista."},
{name:"Barra de Caminho do Elementos do Editor",legend:"Pressione ${elementsPathFocus} para a barra de caminho dos elementos. Mova para o prР“С–ximo botР“Р€o de elemento com TAB ou SETA PARA DIREITA. Mova para o botР“Р€o anterior com SHIFT+TAB ou SETA PARA ESQUERDA. Pressione ESPAР“вЂЎO ou ENTER para selecionar o elemento no editor."}]},{name:"Comandos",items:[{name:" Comando Desfazer",legend:"Pressione ${undo}"},{name:" Comando Refazer",legend:"Pressione ${redo}"},{name:" Comando Negrito",legend:"Pressione ${bold}"},
{name:" Comando ItР“РЋlico",legend:"Pressione ${italic}"},{name:" Comando Sublinhado",legend:"Pressione ${underline}"},{name:" Comando Link",legend:"Pressione ${link}"},{name:" Comando Fechar Barra de Ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Acessar o comando anterior de spaР“В§o de foco",legend:"Pressione ${accessNextSpace} para acessar o espaР“В§o de foco nР“Р€o alcanР“В§Р“РЋvel mais prР“С–ximo antes do cursor, por exemplo: dois elementos HR adjacentes. Repita a combinaР“В§Р“Р€o de teclas para alcanР“В§ar espaР“В§os de foco distantes."},
{name:"Acessar prР“С–ximo fomando de spaР“В§o de foco",legend:"Pressione ${accessNextSpace} para acessar o espaР“В§o de foco nР“Р€o alcanР“В§Р“РЋvel mais prР“С–ximo apР“С–s o cursor, por exemplo: dois elementos HR adjacentes. Repita a combinaР“В§Р“Р€o de teclas para alcanР“В§ar espaР“В§os de foco distantes."},{name:" Ajuda de Acessibilidade",legend:"Pressione ${a11yHelp}"}]}],tab:"Tecla Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Seta Р“В  Esquerda",upArrow:"Seta Р“В  Cima",rightArrow:"Seta Р“В  Direita",
downArrow:"Seta Р“В  Baixo",insert:"Insert",leftWindowKey:"Tecla do Windows Esquerda",rightWindowKey:"Tecla do Windows Direita",selectKey:"Tecla Selecionar",numpad0:"0 do Teclado NumР“В©rico",numpad1:"1 do Teclado NumР“В©rico",numpad2:"2 do Teclado NumР“В©rico",numpad3:"3 do Teclado NumР“В©rico",numpad4:"4 do Teclado NumР“В©rico",numpad5:"5 do Teclado NumР“В©rico",numpad6:"6 do Teclado NumР“В©rico",numpad7:"7 do Teclado NumР“В©rico",numpad8:"8 do Teclado NumР“В©rico",numpad9:"9 do Teclado NumР“В©rico",multiply:"Multiplicar",add:"Mais",
subtract:"Subtrair",decimalPoint:"Ponto",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Ponto-e-vР“В­rgula",equalSign:"Igual",comma:"VР“В­rgula",dash:"HР“В­fen",period:"Ponto",forwardSlash:"Barra",graveAccent:"Acento Grave",openBracket:"Abrir Conchetes",backSlash:"Contra-barra",closeBracket:"Fechar Colchetes",singleQuote:"Aspas Simples"});