РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt",{title:"InstruР“В§Р“Вµes de acessibilidade",contents:"ConteР“С”do de ajuda. Use a tecla ESC para fechar esta janela.",legend:[{name:"Geral",items:[{name:"Barra de ferramentas do editor",legend:"Clique em ${toolbarFocus} para navegar na barra de ferramentas. Para navegar entre o grupo da barra de ferramentas anterior e seguinte use TAB e SHIFT+TAB. Para navegar entre o botР“Р€o da barra de ferramentas seguinte e anterior use a SETA DIREITA ou SETA ESQUERDA. Carregue em ESPAР“вЂЎO ou ENTER para ativar o botР“Р€o da barra de ferramentas."},
{name:"Janela do editor",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Menu de contexto do editor",legend:"Clique em ${contextMenu} ou TECLA APLICAР“вЂЎР“С“O para abrir o menu de contexto. Depois vР“РЋ para a opР“В§Р“Р€o do menu seguinte com TAB ou SETA PARA BAIXO. VР“РЋ para a opР“В§Р“Р€o anterior com  SHIFT+TAB ou SETA PARA CIMA. Pressione ESPAР“вЂЎO ou ENTER para selecionar a opР“В§Р“Р€o do menu.  Abra o submenu da opР“В§Р“Р€o atual com ESPAР“вЂЎO, ENTER ou SETA DIREITA. GVР“РЋ para o item do menu parente  com ESC ou SETA ESQUERDA. Feche o menu de contexto com ESC."},
{name:"Editor de caixa em lista",legend:"Dentro de uma lista, para navegar para o item seguinte da lista use TAB ou SETA PARA BAIXO. Para o item anterior da lista use SHIFT+TAB ou SETA PARA BAIXO. Carregue em ESPAР“вЂЎO ou ENTER para selecionar a opР“В§Р“Р€o lista. Carregue em ESC para fechar a caixa da lista."},{name:"Editor da barra de caminho dos elementos",legend:"Clique em ${elementsPathFocus} para navegar na barra de caminho dos elementos. Para o botР“Р€o do elemento seguinte use TAB ou SETA DIREITA. para o botР“Р€o anterior use SHIFT+TAB ou SETA ESQUERDA. Carregue em ESPAР“вЂЎO ou ENTER para selecionar o elemento no editor."}]},
{name:"Comandos",items:[{name:"Comando de anular",legend:"Carregar ${undo}"},{name:"Comando de refazer",legend:"Clique ${redo}"},{name:"Comando de negrito",legend:"Pressione ${bold}"},{name:"Comando de itР“РЋlico",legend:"Pressione ${italic}"},{name:"Comando de sublinhado",legend:"Pressione ${underline}"},{name:"Comando de hiperligaР“В§Р“Р€o",legend:"Pressione ${link}"},{name:"Comando de ocultar barra de ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Aceder ao comando espaР“В§o de foco anterior",
legend:"Clique em ${accessPreviousSpace} para aceder ao espaР“В§o do focos inalcanР“В§Р“РЋvel mais perto antes do sinal de omissР“Р€o, por exemplo: dois elementos HR adjacentes. Repetir a combinaР“В§Р“Р€o da chave para alcanР“В§ar os espaР“В§os dos focos distantes."},{name:"Acesso comando do espaР“В§o focus seguinte",legend:"Pressione ${accessNextSpace} para aceder ao espaР“В§o do focos inalcanР“В§Р“РЋvel mais perto depois do sinal de omissР“Р€o, por exemplo: dois elementos HR adjacentes. Repetir a combinaР“В§Р“Р€o da chave para alcanР“В§ar os espaР“В§os dos focos distantes."},
{name:"Ajuda a acessibilidade",legend:"Pressione ${a11yHelp}"}]}],tab:"Tab",pause:"Pausa",capslock:"MaiР“С”sculas",escape:"Esc",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Seta esquerda",upArrow:"Seta para cima",rightArrow:"Seta direita",downArrow:"Seta para baixo",insert:"Inserir",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",
numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiplicar",add:"Adicionar",subtract:"Subtrair",decimalPoint:"Decimal Point",divide:"Separar",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"VР“В­rgula",dash:"Cardinal",period:"Ponto",forwardSlash:"Forward Slash",graveAccent:"Acento grave",openBracket:"Open Bracket",backSlash:"Backslash",
closeBracket:"Close Bracket",singleQuote:"Plica"});