РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","ro",{title:"InstrucР�вЂєiuni de accesibilitate",contents:"Cuprins. Pentru a Р“В®nchide acest dialog, apР”С“saР�вЂєi tasta ESC.",legend:[{name:"General",items:[{name:"EditeazР”С“ bara instrumente.",legend:"ApasР”С“ ${toolbarFocus} pentru a naviga prin bara de instrumente. Pentru a te miР�в„ўca prin grupurile de instrumente foloseР�в„ўte tastele TAB Р�в„ўi SHIFT+TAB. Pentru a te miР�в„ўca intre diverse instrumente foloseР�в„ўte tastele SР”вЂљGEATР”вЂљ DREAPTA sau SР”вЂљGEATР”вЂљ STР“вЂљNGA. ApasР”С“ butonul SPAР�С™IU sau ENTER pentru activarea instrumentului."},
{name:"Dialog editor",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor meniu contextual",legend:"ApasР”С“ ${contextMenu} sau TASTA MENIU pentru a deschide meniul contextual. Treci la urmР”С“toarea opР�вЂєiune din meniu cu TAB sau SР”вЂљGEATР”вЂљ JOS. Treci la opР�вЂєiunea anterioarР”С“ cu  SHIFT+TAB sau SР”вЂљGEATР”вЂљ SUS. ApasР”С“ SPAР�С™IU sau ENTER pentru a selecta opР�вЂєiunea din meniu. Deschide sub-meniul opР�вЂєiunii curente cu SPAР�С™IU sau ENTER sau SР”вЂљGEATР”вЂљ DREAPTA. Revino la elementul din meniul pР”С“rinte cu ESC sau SР”вЂљGEATР”вЂљ STР“вЂљNGA. Р“Р‹nchide meniul de context cu ESC."},
{name:"Editor CasetР”С“ ListР”С“",legend:"Р“Р‹n interiorul unei liste, treci la urmР”С“torull element cu TAB sau SР”вЂљGEATР”вЂљ JOS. Treci la elementul anterior din listР”С“ cu SHIFT+TAB sau SР”вЂљGEATР”вЂљ SUS. ApasР”С“ SPAР�С™IU sau ENTER pentru a selecta opР�вЂєiunea din listР”С“. ApasР”С“ ESC pentru a Р“В®nchide lista."},{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},
{name:"Comenzi",items:[{name:" Undo command",legend:"ApasР”С“ ${undo}"},{name:"Comanda precedentР”С“",legend:"ApasР”С“ ${redo}"},{name:"Comanda Р“Р‹ngroР�в„ўat",legend:"ApasР”С“ ${bold}"},{name:"Comanda Inclinat",legend:"ApasР”С“ ${italic}"},{name:"Comanda Subliniere",legend:"ApasР”С“ ${underline}"},{name:"Comanda LegaturР”С“",legend:"ApasР”С“ ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Accessibility Help",legend:"Press ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert",leftWindowKey:"Left Windows key",
rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",
equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});