РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"InР•РЋtrukcie prР“В­stupnosti",contents:"PomocnР“Р… obsah. Pre zatvorenie tohto okna, stlaР”РЊte ESC.",legend:[{name:"VР•РЋeobecne",items:[{name:"LiР•РЋta nР“РЋstrojov editora",legend:"StlaР”РЊte ${toolbarFocus} pre navigР“РЋciu na liР•РЋtu nР“РЋstrojov. Medzi Р”РЏalР•РЋou a predchР“РЋdzajР“С”cou liР•РЋtou nР“РЋstrojov sa pohybujete s TAB a SHIFT+TAB. Medzi Р”РЏalР•РЋР“В­m a predchР“РЋdzajР“С”cim tlaР”РЊidlom na liР•РЋte nР“РЋstrojov sa pohybujete s pravou Р•РЋР“В­pkou a Р”С•avou Р•РЋР“В­pkou. StlaР”РЊte medzernР“В­k alebo ENTER pre aktivР“РЋciu tlaР”РЊidla liР•РЋty nР“РЋstrojov."},
{name:"EditorovР“Р… dialР“С–g",legend:"V dialР“С–govom okne stlaР”РЊte TAB pre presun na Р”РЏalР•РЋР“В­ prvok, SHIFT+TAB pre presun na predchР“РЋdzajР“С”ci prvok, ENTER pre odoslanie, ESC pre zruР•РЋenie. KeР”РЏ mР“РЋ dialР“С–govР“В© okno viacero kariet, zoznam kariet dosiahnete buР”РЏ stlaР”РЊenР“В­m ALT+F10 alebo s TAB v prР“В­sluР•РЋnom poradР“В­ kariet. So zameranР“Р…m zoznamom kariet sa pohybujte k Р”РЏalР•РЋej alebo predchР“РЋdzajР“С”cej karte cez PRAVР“С™ a Р”Р…AVР“С™ Р•В Р“РЊPKU."},{name:"EditorovР“В© kontextovР“В© menu",legend:"StlaР”РЊte ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextovР“В©ho menu. Potom sa presР“С”vajte na Р”РЏalР•РЋie moР•С•nosti menu s TAB alebo dolnou Р•РЋР“В­pkou. Presunte sa k predchР“РЋdzajР“С”cej moР•С•nosti s SHIFT+TAB alebo hornou Р•РЋР“В­pkou. StlaР”РЊte medzernР“В­k alebo ENTER pre vР“Р…ber moР•С•nosti menu. Otvorte pod-menu danej moР•С•nosti s medzernР“В­kom, alebo ENTER, alebo pravou Р•РЋР“В­pkou. VrР“РЋР•Тђte sa spР“В¤Р•Тђ do poloР•С•ky rodiР”РЊovskР“В©ho menu s ESC alebo Р”С•avou Р•РЋР“В­pkou. Zatvorte kontextovР“В© menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presuР•в‚¬te sa na Р”РЏalР•РЋiu poloР•С•ku v zozname s TAB alebo dolnou Р•РЋР“В­pkou. PresuР•в‚¬te sa k predchР“РЋdzajР“С”cej poloР•С•ke v zozname so SHIFT+TAB alebo hornou Р•РЋР“В­pkou. StlaР”РЊte medzernР“В­k alebo ENTER pre vР“Р…ber moР•С•nosti zoznamu. StlaР”РЊte ESC pre zatvorenie boxu zoznamu."},{name:"Editorove pР“РЋsmo cesty prvku",legend:"StlaР”РЊte ${elementsPathFocus} pre navigovanie na pР“РЋsmo cesty elementu. PresuР•в‚¬te sa na tlaР”РЊidlo Р”РЏalР•РЋieho prvku s TAB alebo pravou Р•РЋР“В­pkou. PresuР•в‚¬te sa k predchР“РЋdzajР“С”cemu tlaР”РЊidlu s SHIFT+TAB alebo Р”С•avou Р•РЋР“В­pkou. StlaР”РЊte medzernР“В­k alebo ENTER pre vР“Р…ber prvku v editore."}]},
{name:"PrР“В­kazy",items:[{name:"VrР“РЋtiР•Тђ prР“В­kazy",legend:"StlaР”РЊte ${undo}"},{name:"Nanovo vrР“РЋtiР•Тђ prР“В­kaz",legend:"StlaР”РЊte ${redo}"},{name:"PrР“В­kaz na stuР”РЊnenie",legend:"StlaР”РЊte ${bold}"},{name:"PrР“В­kaz na kurzР“В­vu",legend:"StlaР”РЊte ${italic}"},{name:"PrР“В­kaz na podР”РЊiarknutie",legend:"StlaР”РЊte ${underline}"},{name:"PrР“В­kaz na odkaz",legend:"StlaР”РЊte ${link}"},{name:"PrР“В­kaz na zbalenie liР•РЋty nР“РЋstrojov",legend:"StlaР”РЊte ${toolbarCollapse}"},{name:"PrejsР•Тђ na predchР“РЋdzajР“С”cu zamerateР”С•nР“С” medzeru prР“В­kazu",legend:"StlaР”РЊte ${accessPreviousSpace} pre prР“В­stup na najbliР•С•Р•РЋie nedosiahnuteР”С•nР“В© zamerateР”С•nР“В© medzery pred vsuvkuo. NaprР“В­klad: dve za sebou idР“С”ce horizontР“РЋlne Р”РЊiary. Opakujte kombinР“РЋciu klР“РЋvesov pre dosiahnutie vzdialenР“Р…ch zamerateР”С•nР“Р…ch medzier."},
{name:"PrejsР•Тђ na Р”РЏalР•РЋР“В­ ",legend:"StlaР”РЊte ${accessNextSpace} pre prР“В­stup na najbliР•С•Р•РЋie nedosiahnuteР”С•nР“В© zamerateР”С•nР“В© medzery po vsuvke. NaprР“В­klad: dve za sebou idР“С”ce horizontР“РЋlne Р”РЊiary. Opakujte kombinР“РЋciu klР“РЋvesov pre dosiahnutie vzdialenР“Р…ch zamerateР”С•nР“Р…ch medzier."},{name:"Pomoc prР“В­stupnosti",legend:"StlaР”РЊte ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"StrР“РЋnka hore",pageDown:"StrР“РЋnka dole",leftArrow:"Р•В Р“В­pka naР”С•avo",upArrow:"Р•В Р“В­pka hore",rightArrow:"Р•В Р“В­pka napravo",
downArrow:"Р•В Р“В­pka dole",insert:"Insert",leftWindowKey:"Р”Р…avР“В© Windows tlaР”РЊidlo",rightWindowKey:"PravР“В© Windows tlaР”РЊidlo",selectKey:"TlaР”РЊidlo Select",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"NР“РЋsobenie",add:"SР”РЊР“В­tanie",subtract:"OdР”РЊР“В­tanie",decimalPoint:"DesatinnР“РЋ Р”РЊiarka",divide:"Delenie",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",
f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"BodkoР”РЊiarka",equalSign:"RovnР“РЋ sa",comma:"Р”РЉiarka",dash:"PomР”С”Р”РЊka",period:"Bodka",forwardSlash:"LomР“В­tko",graveAccent:"ZdР“Т‘razР•в‚¬ovanie prР“В­zvuku",openBracket:"HranatР“РЋ zР“РЋtvorka otvР“РЋracia",backSlash:"Backslash",closeBracket:"HranatР“РЋ zР“РЋtvorka zatvР“РЋracia",singleQuote:"JednoduchР“В© Р“С”vodzovky"});