РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sl",{title:"Navodila za dostopnost",contents:"Vsebina pomoР”РЊi. Р”РЉe Р•С•elite zapreti pogovorno okno, pritisnite ESC.",legend:[{name:"SploР•РЋno",items:[{name:"Orodna vrstica urejevalnika",legend:"Pritisnite ${toolbarFocus} za pomik v orodno vrstico. Z TAB in SHIFT+TAB se pomikate na naslednjo in prejР•РЋnjo skupino orodne vrstice. Z DESNO PUР•В Р”РЉICO ali LEVO PUР•В Р”РЉICO se pomikate na naslednji in prejР•РЋnji gumb orodne vrstice. Pritisnite SPACE ali ENTER, da aktivirate gumb orodne vrstice."},
{name:"Urejevalno Pogovorno Okno",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Kontekstni meni urejevalnika",legend:"Pritisnite ${contextMenu} ali APPLICATION KEY, da odprete kontekstni meni. Nato se premaknite na naslednjo moР•С•nost menija s tipko TAB ali PUР•В Р”РЉICA DOL. Premakniti se na prejР•РЋnjo moР•С•nost z SHIFT + TAB ali PUР•В Р”РЉICA GOR. Pritisnite SPACE ali ENTER za izbiro moР•С•nosti menija. Odprite podmeni trenutne moР•С•nosti menija s tipko SPACE ali ENTER ali DESNA PUР•В Р”РЉICA. Vrnite se na matiР”РЊni element menija s tipko ESC ali LEVA PUР•В Р”РЉICA. Zaprite kontekstni meni z ESC."},
{name:"Urejevalno Seznamsko Polje",legend:"Znotraj seznama, se premaknete na naslednji element seznama s tipko TAB ali PUР•В Р”РЉICO DOL. Z SHIFT+TAB ali PUР•В Р”РЉICO GOR se premaknete na prejР•РЋnji element seznama. Pritisnite tipko SPACE ali ENTER za izbiro elementa. Pritisnite tipko ESC, da zaprete seznam."},{name:"Urejevalna vrstica poti elementa",legend:"Pritisnite ${elementsPathFocus} za pomikanje po vrstici elementnih poti. S TAB ali DESNA PUР•В Р”РЉICA se premaknete na naslednji gumb elementa. Z SHIFT+TAB ali LEVO PUР•В Р”РЉICO se premaknete na prejР•РЋnji gumb elementa. Pritisnite SPACE ali ENTER za izbiro elementa v urejevalniku."}]},
{name:"Ukazi",items:[{name:"Razveljavi ukaz",legend:"Pritisnite ${undo}"},{name:"Ponovi ukaz",legend:"Pritisnite ${redo}"},{name:"Krepki ukaz",legend:"Pritisnite ${bold}"},{name:"LeР•С•eР”РЊi ukaz",legend:"Pritisnite ${italic}"},{name:"Poudarni ukaz",legend:"Pritisnite ${underline}"},{name:"Ukaz povezave",legend:"Pritisnite ${link}"},{name:"SkrР”РЊi Orodno Vrstico Ukaz",legend:"Pritisnite ${toolbarCollapse}"},{name:"Dostop do prejР•РЋnjega ukaza ostrenja",legend:"Pritisnite ${accessPreviousSpace} za dostop do najbliР•С•jega nedosegljivega osredotoР”РЊenega prostora pred streР•РЋico, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da doseР•С•ete oddaljene osredotoР”РЊene prostore."},
{name:"Dostop do naslednjega ukaza ostrenja",legend:"Pritisnite ${accessNextSpace} za dostop do najbliР•С•jega nedosegljivega osredotoР”РЊenega prostora po streР•РЋici, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da doseР•С•ete oddaljene osredotoР”РЊene prostore."},{name:"PomoР”РЊ dostopnosti",legend:"Pritisnite ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"PuР•РЋР”РЊica levo",upArrow:"PuР•РЋР”РЊica gor",rightArrow:"PuР•РЋР”РЊica desno",
downArrow:"PuР•РЋР”РЊica dol",insert:"Insert",leftWindowKey:"Leva tipka Windows",rightWindowKey:"Desna tipka Windows",selectKey:"Select tipka",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"ZmnoР•С•i",add:"Dodaj",subtract:"OdР•РЋtej",decimalPoint:"Decimalna vejica",divide:"Deli",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",
f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"PodpiР”РЊje",equalSign:"EnaР”РЊaj",comma:"Vejica",dash:"Vezaj",period:"Pika",forwardSlash:"Desna poР•РЋevnica",graveAccent:"Krativec",openBracket:"Oklepaj",backSlash:"Leva poР•РЋevnica",closeBracket:"Zaklepaj",singleQuote:"OpuР•РЋР”РЊaj"});