РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sv",{title:"HjР“В¤lpmedelsinstruktioner",contents:"HjР“В¤lpinnehР“Тђll. FР“В¶r att stР“В¤nga denna dialogruta trycker du pР“Тђ ESC.",legend:[{name:"AllmР“В¤nt",items:[{name:"Editor verktygsfР“В¤lt",legend:"Tryck pР“Тђ ${toolbarFocus} fР“В¶r att navigera till verktygsfР“В¤ltet. Flytta till nР“В¤sta och fР“В¶regР“Тђende verktygsfР“В¤ltsgrupp med TAB och SHIFT+TAB. Flytta till nР“В¤sta och fР“В¶regР“Тђende knapp i verktygsfР“В¤ltet med HР“вЂ“GERPIL eller VР“вЂћNSTERPIL. Tryck SPACE eller ENTER fР“В¶r att aktivera knappen i verktygsfР“В¤ltet."},
{name:"Dialogeditor",legend:"Inuti en dialogruta, tryck TAB fР“В¶r att navigera till nР“В¤sta fР“В¤lt i dialogrutan, tryck SKIFT+TAB fР“В¶r att flytta till fР“В¶regР“Тђende fР“В¤lt, tryck ENTER fР“В¶r att skicka. Du avbryter och stР“В¤nger dialogen med ESC. FР“В¶r dialogrutor som har flera flikar, tryck ALT+F10 eller TAB fР“В¶r att navigera till fliklistan. med fliklistan vald flytta till nР“В¤sta och fР“В¶regР“Тђende flik med HР“вЂ“GER- eller VР“вЂћNSTERPIL."},{name:"Editor fР“В¶r innehР“Тђllsmeny",legend:"Tryck pР“Тђ $ {contextMenu} eller PROGRAMTANGENTEN fР“В¶r att Р“В¶ppna snabbmenyn. Flytta sedan till nР“В¤sta menyalternativ med TAB eller NEDPIL. Flytta till fР“В¶regР“Тђende alternativ med SHIFT + TABB eller UPPIL. Tryck Space eller ENTER fР“В¶r att vР“В¤lja menyalternativ. Р“вЂ“ppna undermeny av nuvarande alternativ med SPACE eller ENTER eller HР“вЂ“GERPIL. GР“Тђ tillbaka till Р“В¶verordnade menyalternativ med ESC eller VР“вЂћNSTERPIL. StР“В¤ng snabbmenyn med ESC."},
{name:"Editor fР“В¶r list-box",legend:"Inuti en list-box, gР“Тђ till nР“В¤sta listobjekt med TAB eller NEDPIL. Flytta till fР“В¶regР“Тђende listobjekt med SHIFT+TAB eller UPPIL. Tryck SPACE eller ENTER fР“В¶r att vР“В¤lja listan alternativet. Tryck ESC fР“В¶r att stР“В¤nga list-boxen."},{name:"Editor fР“В¶r elementens sР“В¶kvР“В¤g",legend:"Tryck pР“Тђ ${elementsPathFocus} fР“В¶r att navigera till verktygsfР“В¤ltet fР“В¶r elementens sР“В¶kvР“В¤gar. Flytta till nР“В¤sta elementknapp med TAB eller HР“вЂ“GERPIL. Flytta till fР“В¶regР“Тђende knapp med SKIFT+TAB eller VР“вЂћNSTERPIL. Tryck SPACE eller ENTER fР“В¶r att vР“В¤lja element i redigeraren."}]},
{name:"Kommandon",items:[{name:"Р“вЂ¦ngra kommando",legend:"Tryck pР“Тђ ${undo}"},{name:"GР“В¶r om kommando",legend:"Tryck pР“Тђ ${redo}"},{name:"Kommandot fet stil",legend:"Tryck pР“Тђ ${bold}"},{name:"Kommandot kursiv",legend:"Tryck pР“Тђ ${italic}"},{name:"Kommandot understruken",legend:"Tryck pР“Тђ ${underline}"},{name:"Kommandot lР“В¤nk",legend:"Tryck pР“Тђ ${link}"},{name:"VerktygsfР“В¤lt DР“В¶lj kommandot",legend:"Tryck pР“Тђ ${toolbarCollapse}"},{name:"GР“Тђ till fР“В¶regР“Тђende fokus plats",legend:"Tryck pР“Тђ ${accessPreviousSpace} fР“В¶r att gР“Тђ till nР“В¤rmast onР“Тђbara utrymme fР“В¶re markР“В¶ren, exempel: tvР“Тђ intilliggande HR element. Repetera tangentkombinationen fР“В¶r att gР“Тђ till nР“В¤sta."},
{name:"TillgР“Тђ nР“В¤sta fokuskommandots utrymme",legend:"Tryck ${accessNextSpace} pР“Тђ fР“В¶r att komma Р“Тђt den nР“В¤rmaste onР“Тђbar fokus utrymme efter cirkumflex, till exempel: tvР“Тђ intilliggande HR element. Upprepa tangentkombinationen fР“В¶r att nР“Тђ avlР“В¤gsna fokus utrymmen."},{name:"HjР“В¤lp om tillgР“В¤nglighet",legend:"Tryck ${a11yHelp}"}]}],tab:"Tab",pause:"Paus",capslock:"Caps lock",escape:"Escape",pageUp:"Sida Up",pageDown:"Sida Ned",leftArrow:"VР“В¤nsterpil",upArrow:"Uppil",rightArrow:"HР“В¶gerpil",downArrow:"NedР“Тђtpil",
insert:"Infoga",leftWindowKey:"VР“В¤nster Windowstangent",rightWindowKey:"HР“В¶ger Windowstangent",selectKey:"VР“В¤lj tangent",numpad0:"Nummer 0",numpad1:"Nummer 1",numpad2:"Nummer 2",numpad3:"Nummer 3",numpad4:"Nummer 4",numpad5:"Nummer 5",numpad6:"Nummer 6",numpad7:"Nummer 7",numpad8:"Nummer 8",numpad9:"Nummer 9",multiply:"Multiplicera",add:"Addera",subtract:"Minus",decimalPoint:"Decimalpunkt",divide:"Dividera",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",
numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Lika med tecken",comma:"Komma",dash:"Minus",period:"Punkt",forwardSlash:"Snedstreck framР“Тђt",graveAccent:"Accent",openBracket:"Р“вЂ“ppningsparentes",backSlash:"Snedstreck bakР“Тђt",closeBracket:"Slutparentes",singleQuote:"Enkelt Citattecken"});