РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tr",{title:"EriР•Сџilebilirlik TalimatlarР”В±",contents:"YardР”В±m iР“В§eriР”Сџi. Bu pencereyi kapatmak iР“В§in ESC tuР•Сџuna basР”В±n.",legend:[{name:"Genel",items:[{name:"DР“С�zenleyici AraР“В§ Р“вЂЎubuР”Сџu",legend:"AraР“В§ Р“В§ubuР”Сџunda gezinmek iР“В§in ${toolbarFocus} basР”В±n. TAB ve SHIFT+TAB ile Р“В¶nceki ve sonraki araР“В§ Р“В§ubuР”Сџu grubuna taР•СџР”В±yР”В±n. SAР”С› OK veya SOL OK ile Р“В¶nceki ve sonraki bir araР“В§ Р“В§ubuР”Сџu dР“С�Р”Сџmesini hareket ettirin. SPACE tuР•Сџuna basР”В±n veya araР“В§ Р“В§ubuР”Сџu dР“С�Р”Сџmesini etkinleР•Сџtirmek iР“В§in ENTER tuР•Сџna basР”В±n."},
{name:"Diyalog DР“С�zenleyici",legend:"Dialog penceresi iР“В§inde, sonraki iletiР•Сџim alanР”В±na gitmek iР“В§in SEKME tuР•Сџuna basР”В±n, Р“В¶nceki alana geР“В§mek iР“В§in SHIFT + TAB tuР•Сџuna basР”В±n, pencereyi gР“В¶ndermek iР“В§in ENTER tuР•Сџuna basР”В±n, dialog penceresini iptal etmek iР“В§in ESC tuР•Сџuna basР”В±n. Birden Р“В§ok sekme sayfalarР”В± olan diyaloglarР”В±n, sekme listesine gitmek iР“В§in ALT + F10 tuР•СџlarР”В±na basР”В±n. Sonra TAB veya SAР”С› OK sonraki sekmeye taР•СџР”В±yР”В±n. SHIFT + TAB veya SOL OK ile Р“В¶nceki sekmeye geР“В§in. Sekme sayfayР”В± seР“В§mek iР“В§in SPACE veya ENTER tuР•Сџuna basР”В±n."},
{name:"Р”В°Р“В§erik MenР“С� EditР“В¶rР“С�",legend:"Р”В°Р“В§erik menР“С�sР“С�nР“С� aР“В§mak iР“В§in ${contextMenu} veya UYGULAMA TUР•С›U'na basР”В±n. Daha sonra SEKME veya AР•С›AР”С›I OK ile bir sonraki menР“С� seР“В§eneР”Сџi taР•СџР”В±yР”В±n. SHIFT + TAB veya YUKARI OK ile Р“В¶nceki seР“В§eneР”Сџe gider. MenР“С� seР“В§eneР”Сџini seР“В§mek iР“В§in SPACE veya ENTER tuР•Сџuna basР”В±n. SeР“В§ili seР“В§eneР”Сџin alt menР“С�sР“С�nР“С� SPACE ya da ENTER veya SAР”С› OK aР“В§Р”В±n. Р“Сљst menР“С� Р“В¶Р”Сџesini geР“В§mek iР“В§in ESC veya SOL OK ile geri dР“В¶nР“С�n. ESC ile baР”Сџlam menР“С�sР“С�nР“С� kapatР”В±n."},{name:"Liste Kutusu EditР“В¶rР“С�",legend:"Liste kutusu iР“В§inde, bir sonraki liste Р“В¶Р”Сџesine SEKME VEYA AР•С›AР”С›I OK ile taР•СџР”В±yР”В±n. SHIFT+TAB veya YUKARI Р“В¶nceki liste Р“В¶Р”Сџesi taР•СџР”В±yР”В±n. Liste seР“В§eneР”Сџi seР“В§mek iР“В§in SPACE veya ENTER tuР•Сџuna basР”В±n. Liste kutusunu kapatmak iР“В§in ESC tuР•Сџuna basР”В±n."},
{name:"Element Yol Р“вЂЎubuР”Сџu EditР“В¶rР“С�",legend:"Elementlerin yol Р“В§ubuР”Сџunda gezinmek iР“В§in ${ElementsPathFocus} basР”В±n. SEKME veya SAР”С› OK ile sonraki element dР“С�Р”Сџmesine taР•СџР”В±yР”В±n. SHIFT+TAB veya SOL OK Р“В¶nceki dР“С�Р”Сџmeye hareket ettirin. EditР“В¶r iР“В§indeki elementi seР“В§mek iР“В§in ENTER veya SPACE tuР•Сџuna basР”В±n."}]},{name:"Komutlar",items:[{name:"Komutu geri al",legend:"$(undo)'ya basР”В±n"},{name:"Komutu geri al",legend:"${redo} basР”В±n"},{name:" KalР”В±n komut",legend:"${bold} basР”В±n"},{name:" Р”В°talik komutu",legend:"${italic} basР”В±n"},
{name:" Alttan Р“В§izgi komutu",legend:"${underline} basР”В±n"},{name:" BaР”СџlantР”В± komutu",legend:"${link} basР”В±n"},{name:" AraР“В§ Р“В§ubuР”Сџu Toplama komutu",legend:"${toolbarCollapse} basР”В±n"},{name:"Р“вЂ“nceki komut alanР”В±na odaklan",legend:"DР“С�zeltme imleР“В§inden Р“В¶nce, en yakР”В±n uzaktaki alana eriР•Сџmek iР“В§in ${accessPreviousSpace} basР”В±n, Р“В¶rneР”Сџin: iki birleР•Сџik HR elementleri. AynР”В± tuР•Сџ kombinasyonu tekrarР”В±yla diР”Сџer alanlarada ulaР•СџР”В±n."},{name:"Sonraki komut alanР”В±na odaklan",legend:"DР“С�zeltme imleР“В§inden sonra, en yakР”В±n uzaktaki alana eriР•Сџmek iР“В§in ${accessNextSpace} basР”В±n, Р“В¶rneР”Сџin: iki birleР•Сџik HR elementleri. AynР”В± tuР•Сџ kombinasyonu tekrarР”В±yla diР”Сџer alanlarada ulaР•СџР”В±n."},
{name:"EriР•Сџilebilirlik YardР”В±mР”В±",legend:"${a11yHelp}'e basР”В±n"}]}],tab:"Sekme tuР•Сџu",pause:"Durdurma tuР•Сџu",capslock:"BР“С�yР“С�k harf tuР•Сџu",escape:"VazgeР“В§ tuР•Сџu",pageUp:"Sayfa YukarР”В±",pageDown:"Sayfa AР•СџaР”СџР”В±",leftArrow:"Sol ok",upArrow:"YukarР”В± ok",rightArrow:"SaР”Сџ ok",downArrow:"AР•СџaР”СџР”В± ok",insert:"Araya gir",leftWindowKey:"Sol windows tuР•Сџu",rightWindowKey:"SaР”Сџ windows tuР•Сџu",selectKey:"SeР“В§me tuР•Сџu",numpad0:"NР“С�merik 0",numpad1:"NР“С�merik 1",numpad2:"NР“С�merik 2",numpad3:"NР“С�merik 3",numpad4:"NР“С�merik 4",numpad5:"NР“С�merik 5",
numpad6:"NР“С�merik 6",numpad7:"NР“С�merik 7",numpad8:"NР“С�merik 8",numpad9:"NР“С�merik 9",multiply:"Р“вЂЎarpma",add:"Toplama",subtract:"Р“вЂЎР”В±karma",decimalPoint:"OndalР”В±k iР•Сџareti",divide:"BР“В¶lme",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lk",scrollLock:"Scr Lk",semiColon:"NoktalР”В± virgР“С�l",equalSign:"EР•Сџittir",comma:"VirgР“С�l",dash:"Eksi",period:"Nokta",forwardSlash:"Р”В°leri eР”Сџik Р“В§izgi",graveAccent:"Р“Сљst tР”В±rnak",openBracket:"Parantez aР“В§",backSlash:"Ters eР”Сџik Р“В§izgi",
closeBracket:"Parantez kapa",singleQuote:"Tek tР”В±rnak"});