РїВ»С—/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tt",{title:"Accessibility Instructions",contents:"Help Contents. To close this dialog press ESC.",legend:[{name:"Р вЂњР С•Р С�РЎС“Р С�Р С‘",items:[{name:"Editor Toolbar",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"Editor Dialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"Editor Context Menu",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"Editor List Box",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"Р С™Р С•Р С�Р В°Р Р…Р Т‘Р В°Р В»Р В°РЎР‚",items:[{name:"Р С™Р В°Р в„–РЎвЂљР В°РЎР‚РЎС“",legend:"${undo} Р В±Р В°РЎРѓРЎвЂ№Р С–РЎвЂ№Р В·"},{name:"Р С™Р В°Р В±Р В°РЎвЂљР В»Р В°РЎС“",legend:"${redo} Р В±Р В°РЎРѓРЎвЂ№Р С–РЎвЂ№Р В·"},{name:"Р С™Р В°Р В»РЎвЂ№Р Р…",legend:"${bold} Р В±Р В°РЎРѓРЎвЂ№Р С–РЎвЂ№Р В·"},{name:"Р С™РЎС“РЎР‚РЎРѓР С‘Р Р†",legend:"${italic} Р В±Р В°РЎРѓРЎвЂ№Р С–РЎвЂ№Р В·"},{name:"Р С’РЎРѓРЎвЂљРЎвЂ№Р Р…Р В° РЎРѓРЎвЂ№Р В·РЎвЂ№Р В»Р С–Р В°Р Р…",legend:"${underline} Р В±Р В°РЎРѓРЎвЂ№Р С–РЎвЂ№Р В·"},
{name:"Р РЋРЎвЂ№Р В»РЎвЂљР В°Р В»Р В°Р С�Р В°",legend:"${link} Р В±Р В°РЎРѓРЎвЂ№Р С–РЎвЂ№Р В·"},{name:" Toolbar Collapse command",legend:"${toolbarCollapse} Р В±Р В°РЎРѓРЎвЂ№Р С–РЎвЂ№Р В·"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Accessibility Help",legend:"${a11yHelp} Р В±Р В°РЎРѓРЎвЂ№Р С–РЎвЂ№Р В·"}]}],tab:"Tab",pause:"Р СћРЎвЂ№Р Р…РЎвЂ№РЎв‚¬",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Р РЋРЎС“Р В» РЎРЏР С”Р С”Р В° РЎС“Р С”",upArrow:"РЈРЃРЎРѓР С”РЈв„ў РЎвЂљР В°Р В±Р В° РЎС“Р С”",rightArrow:"Р Р€РўР€ РЎРЏР С”Р С”Р В° РЎС“Р С”",downArrow:"Р С’РЎРѓР С”Р В° РЎвЂљР В°Р В±Р В° РЎС“Р С”",insert:"РЈРЃРЎРѓРЎвЂљРЈв„ўРўР‡",leftWindowKey:"Р РЋРЎС“Р В» Windows РЎвЂљРЈВ©Р в„–Р С�Р™в„ўРЎРѓР Вµ",rightWindowKey:"Р Р€РўР€ Windows РЎвЂљРЈВ©Р в„–Р С�Р™в„ўРЎРѓР Вµ",selectKey:"Select РЎвЂљРЈВ©Р в„–Р С�Р™в„ўРЎРѓР Вµ",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",
numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Р СћР В°Р С—Р С”РЎвЂ№РЎР‚Р В»Р В°РЎС“",add:"Р С™РЎС“РЎв‚¬РЎС“",subtract:"Р С’Р В»РЎС“",decimalPoint:"Р Р€Р Р…Р В°РЎР‚Р В»РЎвЂ№ Р Р…Р С•Р С”РЎвЂљР В°",divide:"Р вЂ�РўР‡Р В»РўР‡",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Р СњР С•Р С”РЎвЂљР В°Р В»РЎвЂ№ РЈВ©РЎвЂљР ВµРЎР‚",equalSign:"Р СћР С‘Р С–Р ВµР В·Р В»Р ВµР С” Р В±Р С‘Р В»Р С–Р ВµРЎРѓР Вµ",comma:"РЈРЃРЎвЂљР ВµРЎР‚",dash:"Р РЋРЎвЂ№Р В·РЎвЂ№Р С”",period:"Р вЂќРЈв„ўРЎР‚РЈв„ўРўвЂ”РЈв„ў",forwardSlash:"Р С™РЎвЂ№Р ВµР С” РЎРѓРЎвЂ№Р В·РЎвЂ№Р С”",graveAccent:"Р вЂњРЎР‚Р В°Р Р†Р С‘РЎРѓ",openBracket:"РўвЂ“РЈв„ўРЎРЏ Р В°РЎвЂЎРЎС“",backSlash:"Р С™Р С‘РЎР‚Р Вµ Р С”РЎвЂ№Р ВµР С” РЎРѓРЎвЂ№Р В·РЎвЂ№Р С”",closeBracket:"РўвЂ“РЈв„ўРЎРЏ РЎРЏР В±РЎС“",
singleQuote:"Р вЂ�Р ВµРЎР‚ Р С‘РўР€Р В»Р Вµ Р С”РЎС“РЎв‚¬РЎвЂљРЎвЂ№РЎР‚Р Р…Р В°Р С”Р В»Р В°РЎР‚"});